/**
 * Arabic renderings of the attributions and benefits the content already
 * carries in English.
 *
 * The app is Arabic-first, but every one of the 146 gradings and most of the
 * benefits existed only in English — so an Arabic reader met an Arabic
 * narration under an English citation. These are translations of claims that
 * were already reviewed, not new claims: no grading is added, softened or
 * strengthened here, and the English remains the authority. Where a rendering
 * is wrong it can be corrected here without touching reviewed content.
 *
 * Keyed by the exact English string rather than by zikr id, because the same
 * attribution serves many azkar — thirty-seven distinct gradings cover all 146
 * — and a shared key keeps one wording in one place. Generated by zipping the
 * two lists so no English key was ever retyped by hand.
 *
 * Names follow their canonical Arabic forms (صحيح البخاري، الألباني، حصن
 * المسلم), and the grading vocabulary stays technical: صحيح، حسن، ضعيف، جيد،
 * موضوع.
 */

/** English authenticity note to its Arabic rendering. */
export const AUTHENTICITY_ARABIC: Readonly<Record<string, string>> = Object.freeze({
  "Authentic/Hasan as cited by Hisn al-Muslim/Sunnah.com.": "صحيح/حسن، كما في حصن المسلم وموقع Sunnah.com.",
  "Authenticated by Ibn Hibban and al-Albani.": "صححه ابن حبان والألباني.",
  "Authenticated by al-Albani in Sahih al-Targhib wa al-Tarhib as cited in Hisn al-Muslim/Sunnah.com.":
    "صححه الألباني في صحيح الترغيب والترهيب، كما في حصن المسلم وموقع Sunnah.com.",
  "Authenticated by al-Albani in Sahih al-Tirmidhi as cited in Hisn al-Muslim/Sunnah.com.":
    "صححه الألباني في صحيح الترمذي، كما في حصن المسلم وموقع Sunnah.com.",
  "Authenticated by al-Albani.": "صححه الألباني.",
  "Authenticated.": "حديث صحيح.",
  "Graded Hasan by Al-Albani; Sahih Ibn Hibban.": "حسّنه الألباني؛ وهو في صحيح ابن حبان.",
  "Graded Sahih by al-Albani and Da‘if by Darussalam (Jami‘ at-Tirmidhi 2892).":
    "صححه الألباني وضعّفه دار السلام (جامع الترمذي ٢٨٩٢).",
  "Graded Sahih by al-Albani.": "صححه الألباني.",
  "Graded Sahih/Hasan by al-Albani.": "حكم عليه الألباني بالصحة أو الحسن.",
  "Hasan (Abu Dawud & At-Tirmidhi).": "حسن (أبو داود والترمذي).",
  "Hasan (Abu Dawud & Ibn Majah).": "حسن (أبو داود وابن ماجه).",
  "Hasan (Darussalam).": "حسن (دار السلام).",
  "Hasan (Jami‘ at-Tirmidhi 2891).": "حسن (جامع الترمذي ٢٨٩١).",
  "Hasan according to Al-Albani.": "حسن عند الألباني.",
  "Hasan according to Ibn Baz as cited in Hisn al-Muslim/Sunnah.com.":
    "حسن عند ابن باز، كما في حصن المسلم وموقع Sunnah.com.",
  "Hasan according to al-Albani as cited in Hisn al-Muslim/Sunnah.com.":
    "حسن عند الألباني، كما في حصن المسلم وموقع Sunnah.com.",
  "Hasan by al-Albani.": "حسّنه الألباني.",
  "Hasan chain according to Ibn al-Qayyim as cited in Hisn al-Muslim/Sunnah.com.":
    "إسناده حسن عند ابن القيم، كما في حصن المسلم وموقع Sunnah.com.",
  "Hasan/Sahih as cited by Hisn al-Muslim/Sunnah.com.": "حسن/صحيح، كما في حصن المسلم وموقع Sunnah.com.",
  "Included in Hisn al-Muslim; grading not displayed on the Sunnah.com page.":
    "مذكور في حصن المسلم، ولم تُذكر درجته في صفحة Sunnah.com.",
  "One chain reliable (Jayyid) as cited by Hisn al-Muslim/Sunnah.com.":
    "أحد أسانيده جيد، كما في حصن المسلم وموقع Sunnah.com.",
  "Qur’an 9:129; Abu Dawud 5081 is graded fabricated by al-Albani and is not used.":
    "القرآن الكريم ٩:١٢٩؛ وحديث أبي داود ٥٠٨١ حكم عليه الألباني بالوضع فلم يُعتمد.",
  "Sahih (Abu Dawud & At-Tirmidhi).": "صحيح (أبو داود والترمذي).",
  "Sahih (Abu Dawud).": "صحيح (أبو داود).",
  "Sahih (al-Albani).": "صحيح (الألباني).",
  "Sahih (al-Albani); also established in Sahih al-Bukhari and Sahih Muslim.":
    "صحيح (الألباني)، وهو ثابت أيضاً في صحيح البخاري وصحيح مسلم.",
  "Sahih Muslim and Abu Dawud (Sahih Al-Albani).": "صحيح مسلم وأبو داود (صححه الألباني).",
  "Sahih Muslim and Sahih al-Bukhari.": "صحيح مسلم وصحيح البخاري.",
  "Sahih Muslim.": "صحيح مسلم.",
  "Sahih according to Al-Albani.": "صحيح عند الألباني.",
  "Sahih al-Bukhari and Sahih Muslim.": "صحيح البخاري وصحيح مسلم.",
  "Sahih al-Bukhari and Sunan Abu Dawud.": "صحيح البخاري وسنن أبي داود.",
  "Sahih al-Bukhari.": "صحيح البخاري.",
  "Sahih by al-Albani.": "صححه الألباني.",
  "Sahih.": "حديث صحيح.",
  "Sahih/Hasan as cited by Hisn al-Muslim/Sunnah.com.": "صحيح/حسن، كما في حصن المسلم وموقع Sunnah.com.",
});

/** English benefit to its Arabic rendering. */
export const BENEFIT_ARABIC: Readonly<Record<string, string>> = Object.freeze({
  "Protection from the jinn until evening.": "حفظ من الجن حتى المساء.",
  "Whoever says it with certainty and dies that day will enter Paradise.":
    "من قالها موقناً بها فمات من يومه دخل الجنة.",
  "Prophetic supplication for bodily, hearing, and sight well-being; recited three times.":
    "دعاء نبوي بالعافية في البدن والسمع والبصر، يُقال ثلاثاً.",
  "A Qur’anic declaration that Allah alone is sufficient and worthy of reliance.":
    "إعلان قرآني بأن الله وحده هو الكافي المستحق للتوكل عليه.",
  "A comprehensive daily request for pardon, well-being, and protection.": "سؤال جامع كل يوم للعفو والعافية والحفظ.",
  "Said three times; by Allah’s permission, nothing will cause harm.": "تُقال ثلاثاً، فلا يضره بإذن الله شيء.",
  "Said three times; a pledge of contentment with Allah, Islam, and Muhammad ﷺ.":
    "تُقال ثلاثاً، وهي رضاً بالله رباً وبالإسلام ديناً وبمحمد ﷺ نبياً.",
  "A plea for Allah to set every affair right and not leave one to oneself.":
    "سؤال الله أن يصلح الشأن كله وألا يَكِل العبد إلى نفسه.",
  "Said one hundred times; sins are erased even if like the foam of the sea.":
    "تُقال مئة مرة، فتُحط الخطايا وإن كانت مثل زبد البحر.",
  "Three repetitions outweigh a long morning spent in remembrance.": "ثلاث تسبيحات تعدل ما قيل من الذكر منذ الصباح.",
  "A request after Fajr for beneficial knowledge, lawful provision, and accepted deeds.":
    "سؤال بعد الفجر علماً نافعاً ورزقاً طيباً وعملاً متقبلاً.",
  "Hisn notes: recite 100 times during the day.": "جاء في حصن المسلم: تُقال مئة مرة في اليوم.",
  "Ten blessings upon the Prophet ﷺ in the morning; reported as a means to his intercession.":
    "عشر صلوات على النبي ﷺ في الصباح، وقد ورد أنها سبب لشفاعته.",
  "Said three times in the evening for protection from poisonous harm that night.":
    "تُقال ثلاثاً في المساء حفظاً من ضرر السموم تلك الليلة.",
  "Included as the opening item of the morning/evening chapter.": "أول ما يُفتتح به باب أذكار الصباح والمساء.",
  "Protection from the jinn until morning.": "حفظ من الجن حتى الصباح.",
  "The Prophet ﷺ used this remembrance upon entering the evening.": "كان النبي ﷺ يقول هذا الذكر إذا أمسى.",
  "A Prophetic remembrance affirming that life, death, and return are to Allah.":
    "ذكر نبوي فيه إقرار بأن المحيا والممات والمرجع إلى الله.",
  "Whoever says it with certainty and dies that night will enter Paradise.":
    "من قالها موقناً بها فمات من ليلته دخل الجنة.",
  "Said four times in the evening; a reported means of freedom from the Fire.":
    "تُقال أربعاً في المساء، وقد ورد أنها سبب للعتق من النار.",
  "Said in the evening as gratitude for the blessings of the night.": "تُقال في المساء شكراً لله على نعم الليل.",
  "A comprehensive evening request for the good of the night and protection from its evil.":
    "سؤال جامع في المساء لخير الليلة والاستعاذة من شرها.",
  "An evening testimony to faith in Allah and the religion of Islam.": "شهادة في المساء بالإيمان بالله وبدين الإسلام.",
  "Ten blessings upon the Prophet ﷺ in the evening; reported as a means to his intercession.":
    "عشر صلوات على النبي ﷺ في المساء، وقد ورد أنها سبب لشفاعته.",
  "Gathers palms, blows lightly into them, recites the 3 Surahs, then wipes over as much of the body as possible. Repeated 3 times.":
    "يجمع كفيه وينفث فيهما ويقرأ السور الثلاث ثم يمسح ما استطاع من جسده، ثلاث مرات.",
  "Whoever recites it when lying down to sleep, a guardian from Allah will remain with him and no devil will approach him until morning.":
    "من قرأها عند نومه لم يزل عليه من الله حافظ ولا يقربه شيطان حتى يصبح.",
  "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him.":
    "من قرأ الآيتين من آخر سورة البقرة في ليلة كفتاه.",
  "Reciting Surah Al-Kafirun before sleeping is a disavowal and immunity from shirk (polytheism).":
    "قراءة سورة الكافرون قبل النوم براءة من الشرك.",
  "A report mentions reciting As-Sajdah and Al-Mulk before sleep; scholars differ over its grading.":
    "ورد ذكر قراءة السجدة والملك قبل النوم، وقد اختلف أهل العلم في درجته.",
  "This thirty-verse surah intercedes for its companion until he is forgiven.":
    "هذه السورة ذات الثلاثين آية تشفع لصاحبها حتى يُغفر له.",
  "Recited 33 times before sleeping (Hadith of Ali & Fatima).":
    "تُقال ثلاثاً وثلاثين قبل النوم (حديث علي وفاطمة رضي الله عنهما).",
  "Recited 33 times before sleeping.": "تُقال ثلاثاً وثلاثين قبل النوم.",
  "Recited 34 times before sleeping.": "تُقال أربعاً وثلاثين قبل النوم.",
  "Recited when lying down to sleep.": "تُقال عند الاضطجاع للنوم.",
  "Standard supplication when sleeping.": "الدعاء المشروع عند النوم.",
  "Recited 3 times with right hand under cheek.": "تُقال ثلاثاً واليد اليمنى تحت الخد.",
  "Expresses gratitude for life, food, and shelter before sleep.": "شكر لله على الحياة والطعام والمأوى قبل النوم.",
  "Deep supplication for debt clearance and spiritual protection.": "دعاء عظيم لقضاء الدين وحفظ القلب.",
  "Protects against self-harm, Satan, and wronging others.": "حفظ من أذى النفس ومن الشيطان ومن ظلم الآخرين.",
  "Make it the last supplication before sleep. If you die that night, you die upon natural faith (al-Fitrah).":
    "اجعله آخر ما تقول قبل النوم، فإن مت من ليلتك مت على الفطرة.",
  "Sahih al-Bukhari.": "صحيح البخاري.",
  "Whoever says this will be forgiven, and if he supplicates Allah, his prayer will be answered; if he performs ablution and prays, his prayer will be accepted.":
    "من قال ذلك غُفر له، فإن دعا الله استُجيب له، فإن توضأ وصلى قُبلت صلاته.",
  "When you say this, it will be said to you: 'You are guided, defended and protected.' The devil will go far away from you.":
    "إذا قلت ذلك قيل لك: هُديت وكُفيت ووُقيت، وتنحّى عنك الشيطان.",
  "To be said upon entering the home. The person should then greet his family.":
    "تُقال عند دخول البيت، ثم يسلّم على أهله.",
  "Upon entering the mosque. He will be protected from Satan for the rest of the day.":
    "عند دخول المسجد، فيُحفظ من الشيطان بقية يومه.",
  "To be said upon leaving the mosque.": "تُقال عند الخروج من المسجد.",
  "Recited 3 times after every obligatory prayer.": "تُقال ثلاثاً بعد كل صلاة مفروضة.",
  "Recited immediately after prayer.": "تُقال عقب الصلاة مباشرة.",
  "Whoever recites Ayat Al-Kursi after each obligatory prayer, nothing prevents him from entering Paradise except death.":
    "من قرأ آية الكرسي دبر كل صلاة مكتوبة لم يمنعه من دخول الجنة إلا الموت.",
  "Affirmation of Tawhid following prayer.": "إقرار بالتوحيد عقب الصلاة.",
  "Declares complete submission to Allah's decree after prayer.": "إعلان التسليم التام لقضاء الله عقب الصلاة.",
  "Recited 33 times after obligatory prayer.": "تُقال ثلاثاً وثلاثين بعد الصلاة المفروضة.",
  "Completed to 100 with Tawhid following the 99 Tasbeehs.": "تمام المئة بالتوحيد بعد التسع والتسعين.",
  "Advised by the Prophet to Mu'adh bin Jabal to recite after every prayer.":
    "أوصى بها النبي ﷺ معاذ بن جبل أن يقولها دبر كل صلاة.",
  "Recited 10 times after Fajr and Maghrib before speaking; grants 10 good deeds, erases 10 sins, raises 10 degrees, and protects from Satan and harm.":
    "تُقال عشراً بعد الفجر والمغرب قبل الكلام، فيها عشر حسنات ومحو عشر سيئات ورفع عشر درجات وحفظ من الشيطان ومن السوء.",
  "Comprehensive supplication after prayer.": "دعاء جامع بعد الصلاة.",
  "Recited after Fajr prayer.": "تُقال بعد صلاة الفجر.",
  "Said before wudu.": "تُقال قبل الوضوء.",
  "Supplication during purification.": "دعاء أثناء الطهارة.",
  "Recited before entering the toilet.": "تُقال قبل دخول الخلاء.",
  "Recited upon leaving the toilet.": "تُقال عند الخروج من الخلاء.",
  "Recited after completing wudu — opens all eight gates of Paradise.":
    "تُقال بعد تمام الوضوء، فتُفتح لها أبواب الجنة الثمانية.",
  "Recited after wudu.": "تُقال بعد الوضوء.",
  "Recited before eating.": "تُقال قبل الطعام.",
  "Recited if forgotten at the start of eating.": "تُقال إذا نسي التسمية في أول الطعام.",
  "Recited after eating.": "تُقال بعد الطعام.",
  "Recited after completing a meal.": "تُقال بعد الفراغ من الطعام.",
  "Recited when served food.": "تُقال إذا قُدّم إليه الطعام.",
  "Dua for the host who served food/drink.": "دعاء لمن قدّم الطعام أو الشراب.",
  "Recited when hosted for Iftar or a meal.": "تُقال إذا أفطر عند أحد أو دُعي إلى طعام.",
  "Said when wearing a garment.": "تُقال عند لبس الثوب.",
  "Said when putting on a new garment.": "تُقال عند لبس الثوب الجديد.",
  "Said to someone wearing a new garment.": "تُقال لمن لبس ثوباً جديداً.",
  "Said before undressing to shield from jinn.": "تُقال قبل خلع الثياب ستراً من الجن.",
  "Recited when mounting a transport and setting out on travel — full supplication from Sahih Muslim.":
    "تُقال عند ركوب الدابة والخروج للسفر، وهو الدعاء التام في صحيح مسلم.",
  "Recited when returning from travel to home or city.": "تُقال عند الرجوع من السفر إلى البيت أو البلد.",
  "Recited when entering a town, city, or new destination.": "تُقال عند دخول قرية أو بلدة أو مكان جديد.",
  "Comprehensive refuge against grief, debt, and hardship.": "استعاذة جامعة من الهم والدين وشدة العيش.",
  "No Muslim supplicates with this in any distress except that Allah relieves him.":
    "ما دعا بها مسلم في كرب إلا فرّج الله عنه.",
  "Remedy during severe emotional or spiritual distress.": "دواء عند اشتداد الكرب والضيق.",
  "Dua of the distressed person.": "دعاء المكروب.",
  "Removes anxiety and replaces sorrow with joy.": "يُذهب الهم ويبدل الحزن فرحاً.",
  "Place hand on painful area and repeat 7 times.": "يضع يده على موضع الألم ويكررها سبعاً.",
  "Ruqyah dua for visiting a sick person.": "دعاء رقية لعيادة المريض.",
  "Prophetic ruqyah for healing and protection.": "رقية نبوية للشفاء والحفظ.",
  "Recited 7 times when visiting the sick.": "تُقال سبعاً عند عيادة المريض.",
  "Prophetic practice before sleep or when feeling ill.": "هدي نبوي قبل النوم أو عند الشكوى من علة.",
  "Ruqyah Jibril recited for the Prophet ﷺ.": "رقية جبريل عليه السلام التي رقى بها النبي ﷺ.",
  "Complete Islamic greeting earning 30 rewards.": "تمام السلام، وفيه ثلاثون حسنة.",
  "Complete response to Islamic greeting.": "تمام رد السلام.",
  "Obligatory response when a brother praises Allah after sneezing.": "حق واجب إذا حمد أخوك الله بعد العطاس.",
  "Sneezer's response to 'Yarhamukallah'.": "رد العاطس على من قال له: يرحمك الله.",
  "Best expression of gratitude to someone doing a favor.": "أحسن ما يُكافأ به من صنع معروفاً.",
  "Prophetic supplication of blessing for a Muslim.": "دعاء نبوي بالبركة للمسلم.",
  "Dua for a newly married couple.": "دعاء لمن تزوج حديثاً.",
  "Recited upon experiencing a calamity or loss.": "تُقال عند المصيبة أو الفقد.",
  "Dua upon visiting or hearing of a deceased Muslim.": "دعاء عند زيارة قبر مسلم أو سماع خبر وفاته.",
  "Recited when strong winds blow.": "تُقال عند اشتداد الريح.",
  "Recited when rain starts falling.": "تُقال عند نزول المطر.",
  "Recited after rain stops.": "تُقال بعد انقطاع المطر.",
  "Recited upon hearing thunder.": "تُقال عند سماع الرعد.",
  "Recited upon sighting the new crescent moon.": "تُقال عند رؤية الهلال.",
  "Authentic guidance when an eclipse occurs: supplicate, magnify Allah, pray, and give charity.":
    "هدي ثابت عند الكسوف: الدعاء والتكبير والصلاة والصدقة.",
  "Prophetic supplication for divine guidance and firmness.": "دعاء نبوي بالهداية والثبات.",
  "100 times daily — equals freeing 10 slaves, grants 100 good deeds, erases 100 sins, shields from Shaytan.":
    "مئة مرة في اليوم، تعدل عتق عشر رقاب، وتُكتب بها مئة حسنة، وتُمحى بها مئة سيئة، وتكون حرزاً من الشيطان.",
  "Forgives sins even if they are as abundant as the foam of the sea.": "تُغفر بها الذنوب وإن كانت مثل زبد البحر.",
  "Two phrases light on the tongue, heavy on the balance, beloved to the Most Merciful.":
    "كلمتان خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن.",
  "Most comprehensive plea for protection in life and the afterlife.": "أجمع ما يُسأل به الحفظ في الدنيا والآخرة.",
  "A treasure from the treasures of Paradise.": "كنز من كنوز الجنة.",
  "Gathers all goodness of this life and the next.": "تجمع خير الدنيا والآخرة.",
  "The Master Supplication for Forgiveness. Whoever recites it with conviction during day or night and dies will enter Paradise.":
    "سيد الاستغفار، من قاله موقناً به في نهاره أو ليله فمات دخل الجنة.",
  "Whoever recites it 3 times, nothing will harm him.": "من قالها ثلاثاً لم يضره شيء.",
});

/** The Arabic rendering where one exists, otherwise the reviewed English. */
export function toArabicAttribution(englishNote: string | undefined): string | undefined {
  if (!englishNote) return undefined;
  return AUTHENTICITY_ARABIC[englishNote] ?? englishNote;
}

/** The Arabic rendering where one exists, otherwise the reviewed English. */
export function toArabicBenefit(englishBenefit: string | undefined): string | undefined {
  if (!englishBenefit) return undefined;
  return BENEFIT_ARABIC[englishBenefit] ?? englishBenefit;
}

/**
 * English source reference to its Arabic rendering.
 *
 * A citation is a locator, so these were produced by substitution rather than
 * by hand: collection names map to their canonical Arabic (with the genitive
 * where the construct requires it — "Sunan Abu Dawud" is سنن أبي داود, not
 * أبو), and the volume and page numbers are transformed to Arabic-Indic digits
 * programmatically. No number was retyped, which is the one error that would
 * send a reader to the wrong hadith. A trailing letter on a number is
 * Sunnah.com's own sub-reference and stays as it is.
 */
export const SOURCE_REFERENCE_ARABIC: Readonly<Record<string, string>> = Object.freeze({
  "Abu Dawud no. 3667; Hisn al-Muslim 75a.": "أبو داود رقم ٣٦٦٧؛ حصن المسلم ٧٥a.",
  "Qur’an 2:255; Al-Hakim 1/562; Hisn al-Muslim 75.": "القرآن ٢:٢٥٥؛ الحاكم ١/٥٦٢؛ حصن المسلم ٧٥.",
  "Abu Dawud 4/322; At-Tirmidhi 5/567; Hisn al-Muslim 76.": "أبو داود ٤/٣٢٢؛ الترمذي ٥/٥٦٧؛ حصن المسلم ٧٦.",
  "Muslim 4/2088; Hisn al-Muslim 77.": "مسلم ٤/٢٠٨٨؛ حصن المسلم ٧٧.",
  "At-Tirmidhi 5/466; Abu Dawud 4/317; Ibn Majah; Hisn al-Muslim 78.":
    "الترمذي ٥/٤٦٦؛ أبو داود ٤/٣١٧؛ ابن ماجه؛ حصن المسلم ٧٨.",
  "Al-Bukhari 7/150; Hisn al-Muslim 79.": "البخاري ٧/١٥٠؛ حصن المسلم ٧٩.",
  "Abu Dawud 4/317; Al-Bukhari in Al-Adab al-Mufrad; An-Nasa’i; Ibn as-Sunni; Hisn al-Muslim 80.":
    "أبو داود ٤/٣١٧؛ البخاري في الأدب المفرد؛ النسائي؛ ابن السني؛ حصن المسلم ٨٠.",
  "Abu Dawud 4/318; An-Nasa’i Amal al-Yawm wa al-Laylah no. 7; Ibn as-Sunni no. 41; Ibn Hibban no. 2361; Hisn al-Muslim 81.":
    "أبو داود ٤/٣١٨؛ النسائي عمل اليوم والليلة رقم ٧؛ ابن السني رقم ٤١؛ ابن حبان رقم ٢٣٦١؛ حصن المسلم ٨١.",
  "Abu Dawud 4/324; Ahmad 5/42; An-Nasa’i; Ibn as-Sunni; Al-Adab al-Mufrad; Hisn al-Muslim 82.":
    "أبو داود ٤/٣٢٤؛ أحمد ٥/٤٢؛ النسائي؛ ابن السني؛ الأدب المفرد؛ حصن المسلم ٨٢.",
  "Qur’an 9:129.": "القرآن ٩:١٢٩.",
  "Abu Dawud; Ibn Majah; Ahmad; An-Nasa’i; Hisn al-Muslim 84.": "أبو داود؛ ابن ماجه؛ أحمد؛ النسائي؛ حصن المسلم ٨٤.",
  "At-Tirmidhi; Abu Dawud 4/317; Hisn al-Muslim 85/109.": "الترمذي؛ أبو داود ٤/٣١٧؛ حصن المسلم ٨٥/١٠٩.",
  "Abu Dawud 4/323; At-Tirmidhi 5/465; Ibn Majah; Ahmad; Hisn al-Muslim 86.":
    "أبو داود ٤/٣٢٣؛ الترمذي ٥/٤٦٥؛ ابن ماجه؛ أحمد؛ حصن المسلم ٨٦.",
  "Ahmad 4/337; An-Nasa’i; Ibn as-Sunni; At-Tirmidhi 5/465; Hisn al-Muslim 87.":
    "أحمد ٤/٣٣٧؛ النسائي؛ ابن السني؛ الترمذي ٥/٤٦٥؛ حصن المسلم ٨٧.",
  "Al-Hakim; Al-Albani, Sahih al-Jamiʿ; Hisn al-Muslim 88.": "الحاكم؛ الألباني, صحيح الجامعʿ؛ حصن المسلم ٨٨.",
  "Abu Dawud 4/322; Hisn al-Muslim 89.": "أبو داود ٤/٣٢٢؛ حصن المسلم ٨٩.",
  "Ahmad 3/406-407 and 5/123; An-Nasa’i Amal al-Yawm wa al-Laylah no. 34; At-Tirmidhi 4/209; Hisn al-Muslim 90.":
    "أحمد ٣/٤٠٦-٤٠٧ و٥/١٢٣؛ النسائي عمل اليوم والليلة رقم ٣٤؛ الترمذي ٤/٢٠٩؛ حصن المسلم ٩٠.",
  "Al-Bukhari 4/2071; Hisn al-Muslim 91.": "البخاري ٤/٢٠٧١؛ حصن المسلم ٩١.",
  "Al-Bukhari 4/95; Muslim 4/2071; Hisn al-Muslim 93.": "البخاري ٤/٩٥؛ مسلم ٤/٢٠٧١؛ حصن المسلم ٩٣.",
  "Muslim 4/2090; Hisn al-Muslim 94.": "مسلم ٤/٢٠٩٠؛ حصن المسلم ٩٤.",
  "Ibn as-Sunni no. 54; Ibn Majah no. 925; Hisn al-Muslim 95.": "ابن السني رقم ٥٤؛ ابن ماجه رقم ٩٢٥؛ حصن المسلم ٩٥.",
  "Al-Bukhari; Muslim 4/2075; Hisn al-Muslim 96.": "البخاري؛ مسلم ٤/٢٠٧٥؛ حصن المسلم ٩٦.",
  "At-Tabarani; Haythami Majmaʿ az-Zawa’id 10/120; Hisn al-Muslim 98.":
    "الطبراني؛ الهيثمي مجمع الزوائد ١٠/١٢٠؛ حصن المسلم ٩٨.",
  "Ahmad 2/290; An-Nasa’i; At-Tirmidhi 3/187; Ibn as-Sunni; Hisn al-Muslim 97.":
    "أحمد ٢/٢٩٠؛ النسائي؛ الترمذي ٣/١٨٧؛ ابن السني؛ حصن المسلم ٩٧.",
  "Al-Bukhari 3293; Muslim 2691; Hisn al-Muslim 92–93.": "البخاري ٣٢٩٣؛ مسلم ٢٦٩١؛ حصن المسلم ٩٢–٩٣.",
  "Sahih al-Bukhari 5017; Sahih Muslim 2192; Hisn al-Muslim 99.": "صحيح البخاري ٥٠١٧؛ صحيح مسلم ٢١٩٢؛ حصن المسلم ٩٩.",
  "Sahih al-Bukhari 2311; Hisn al-Muslim 100.": "صحيح البخاري ٢٣١١؛ حصن المسلم ١٠٠.",
  "Sahih al-Bukhari 5009; Sahih Muslim 807; Hisn al-Muslim 101.": "صحيح البخاري ٥٠٠٩؛ صحيح مسلم ٨٠٧؛ حصن المسلم ١٠١.",
  "Sunan Abu Dawud 5055; Jami' at-Tirmidhi 3403.": "سنن أبي داود ٥٠٥٥؛ جامع الترمذي ٣٤٠٣.",
  "Jami' at-Tirmidhi 2892; Sunan an-Nasa'i 10043.": "جامع الترمذي ٢٨٩٢؛ سنن النسائي ١٠٠٤٣.",
  "Jami' at-Tirmidhi 2891 (Hasan).": "جامع الترمذي ٢٨٩١ (حسن).",
  "Sahih al-Bukhari 3113; Sahih Muslim 2727; Hisn al-Muslim 106.": "صحيح البخاري ٣١١٣؛ صحيح مسلم ٢٧٢٧؛ حصن المسلم ١٠٦.",
  "Sahih al-Bukhari 6320; Sahih Muslim 2714; Hisn al-Muslim 102.": "صحيح البخاري ٦٣٢٠؛ صحيح مسلم ٢٧١٤؛ حصن المسلم ١٠٢.",
  "Sahih al-Bukhari 6312; Sahih Muslim 2711; Hisn al-Muslim 105.": "صحيح البخاري ٦٣١٢؛ صحيح مسلم ٢٧١١؛ حصن المسلم ١٠٥.",
  "Sunan Abu Dawud 5045; Jami' at-Tirmidhi 3398; Hisn al-Muslim 104.":
    "سنن أبي داود ٥٠٤٥؛ جامع الترمذي ٣٣٩٨؛ حصن المسلم ١٠٤.",
  "Sahih Muslim 2715; Hisn al-Muslim 108.": "صحيح مسلم ٢٧١٥؛ حصن المسلم ١٠٨.",
  "Sahih Muslim 2713; Hisn al-Muslim 107.": "صحيح مسلم ٢٧١٣؛ حصن المسلم ١٠٧.",
  "Sunan Abu Dawud 5067; Jami' at-Tirmidhi 3392; Hisn al-Muslim 109.":
    "سنن أبي داود ٥٠٦٧؛ جامع الترمذي ٣٣٩٢؛ حصن المسلم ١٠٩.",
  "Sahih al-Bukhari 247; Sahih Muslim 2710; Hisn al-Muslim 111.": "صحيح البخاري ٢٤٧؛ صحيح مسلم ٢٧١٠؛ حصن المسلم ١١١.",
  "Al-Bukhari 11/113; Muslim 4/2083; Hisn al-Muslim 1.": "البخاري ١١/١١٣؛ مسلم ٤/٢٠٨٣؛ حصن المسلم ١.",
  "Al-Bukhari 3/39; Hisn al-Muslim 2.": "البخاري ٣/٣٩؛ حصن المسلم ٢.",
  "Abu Dawud 4/325; At-Tirmidhi 5/490; Hisn al-Muslim 15.": "أبو داود ٤/٣٢٥؛ الترمذي ٥/٤٩٠؛ حصن المسلم ١٥.",
  "Abu Dawud 4/325; Hisn al-Muslim 16.": "أبو داود ٤/٣٢٥؛ حصن المسلم ١٦.",
  "Abu Dawud; Muslim 1/494; Hisn al-Muslim 20.": "أبو داود؛ مسلم ١/٤٩٤؛ حصن المسلم ٢٠.",
  "Muslim 1/494; Ibn Majah; Hisn al-Muslim 21.": "مسلم ١/٤٩٤؛ ابن ماجه؛ حصن المسلم ٢١.",
  "Sahih Muslim 591; Hisn al-Muslim 66.": "صحيح مسلم ٥٩١؛ حصن المسلم ٦٦.",
  "Sahih Muslim 592; Hisn al-Muslim 66.": "صحيح مسلم ٥٩٢؛ حصن المسلم ٦٦.",
  "Sunan an-Nasa'i 9928; Ibn Hibban 2004; Hisn al-Muslim 31.": "سنن النسائي ٩٩٢٨؛ ابن حبان ٢٠٠٤؛ حصن المسلم ٣١.",
  "Sahih al-Bukhari 6329; Sahih Muslim 595; Hisn al-Muslim 25.": "صحيح البخاري ٦٣٢٩؛ صحيح مسلم ٥٩٥؛ حصن المسلم ٢٥.",
  "Sahih al-Bukhari 844; Sahih Muslim 593; Hisn al-Muslim 26.": "صحيح البخاري ٨٤٤؛ صحيح مسلم ٥٩٣؛ حصن المسلم ٢٦.",
  "Sahih Muslim 597; Hisn al-Muslim 27.": "صحيح مسلم ٥٩٧؛ حصن المسلم ٢٧.",
  "Jami' at-Tirmidhi 3474; Sunan an-Nasa'i 10234; Hisn al-Muslim 29.":
    "جامع الترمذي ٣٤٧٤؛ سنن النسائي ١٠٢٣٤؛ حصن المسلم ٢٩.",
  "Jami' at-Tirmidhi 3233 (Hasan).": "جامع الترمذي ٣٢٣٣ (حسن).",
  "Sunan Ibn Majah 925; Hisn al-Muslim 32.": "سنن ابن ماجه ٩٢٥؛ حصن المسلم ٣٢.",
  "Sunan Abu Dawud 101; Sunan Ibn Majah 399; Hisn al-Muslim 8.": "سنن أبي داود ١٠١؛ سنن ابن ماجه ٣٩٩؛ حصن المسلم ٨.",
  "Sunan Ibn Majah 299.": "سنن ابن ماجه ٢٩٩.",
  "Sahih al-Bukhari 142; Sahih Muslim 375; Hisn al-Muslim 6.": "صحيح البخاري ١٤٢؛ صحيح مسلم ٣٧٥؛ حصن المسلم ٦.",
  "Sunan Abu Dawud 30; Jami' at-Tirmidhi 7; Hisn al-Muslim 7.": "سنن أبي داود ٣٠؛ جامع الترمذي ٧؛ حصن المسلم ٧.",
  "Sahih Muslim 234; Hisn al-Muslim 9.": "صحيح مسلم ٢٣٤؛ حصن المسلم ٩.",
  "Jami' at-Tirmidhi 3/153; Sunan an-Nasa'i; Hisn al-Muslim 10.": "جامع الترمذي ٣/١٥٣؛ سنن النسائي؛ حصن المسلم ١٠.",
  "Sunan Abu Dawud 3/347; Jami' at-Tirmidhi 4/288; Hisn al-Muslim 178.":
    "سنن أبي داود ٣/٣٤٧؛ جامع الترمذي ٤/٢٨٨؛ حصن المسلم ١٧٨.",
  "Sunan Abu Dawud 3767; Jami' at-Tirmidhi 1858; Hisn al-Muslim 178.":
    "سنن أبي داود ٣٧٦٧؛ جامع الترمذي ١٨٥٨؛ حصن المسلم ١٧٨.",
  "Sunan Abu Dawud 3850; Jami' at-Tirmidhi 3457; Hisn al-Muslim 179.":
    "سنن أبي داود ٣٨٥٠؛ جامع الترمذي ٣٤٥٧؛ حصن المسلم ١٧٩.",
  "Sahih al-Bukhari 7/84; Hisn al-Muslim 180.": "صحيح البخاري ٧/٨٤؛ حصن المسلم ١٨٠.",
  "Jami' at-Tirmidhi 5/506; Hisn al-Muslim 181.": "جامع الترمذي ٥/٥٠٦؛ حصن المسلم ١٨١.",
  "Sahih Muslim 2055; Hisn al-Muslim 182.": "صحيح مسلم ٢٠٥٥؛ حصن المسلم ١٨٢.",
  "Sunan Abu Dawud 3854; Sunan Ibn Majah 1747; Hisn al-Muslim 183.":
    "سنن أبي داود ٣٨٥٤؛ سنن ابن ماجه ١٧٤٧؛ حصن المسلم ١٨٣.",
  "Sunan Abu Dawud 4023; Jami' at-Tirmidhi 3458; Hisn al-Muslim 2.":
    "سنن أبي داود ٤٠٢٣؛ جامع الترمذي ٣٤٥٨؛ حصن المسلم ٢.",
  "Sunan Abu Dawud 4020; Jami' at-Tirmidhi 1767; Hisn al-Muslim 3.":
    "سنن أبي داود ٤٠٢٠؛ جامع الترمذي ١٧٦٧؛ حصن المسلم ٣.",
  "Sunan Abu Dawud 4020; Hisn al-Muslim 4.": "سنن أبي داود ٤٠٢٠؛ حصن المسلم ٤.",
  "Sunan Ibn Majah 297; Jami' at-Tirmidhi; Hisn al-Muslim 5.": "سنن ابن ماجه ٢٩٧؛ جامع الترمذي؛ حصن المسلم ٥.",
  "Sahih Muslim 1342; Sunan Abu Dawud 2599; Hisn al-Muslim 75–76.":
    "صحيح مسلم ١٣٤٢؛ سنن أبي داود ٢٥٩٩؛ حصن المسلم ٧٥–٧٦.",
  "Sahih Muslim 1343; Sahih al-Bukhari 3084; Hisn al-Muslim 77–78.":
    "صحيح مسلم ١٣٤٣؛ صحيح البخاري ٣٠٨٤؛ حصن المسلم ٧٧–٧٨.",
  "Sahih Ibn Hibban 2697; Al-Hakim 1/442; Hisn al-Muslim 80.": "صحيح ابن حبان ٢٦٩٧؛ الحاكم ١/٤٤٢؛ حصن المسلم ٨٠.",
  "Sahih al-Bukhari 6363; Sunan Abu Dawud 1555; Hisn al-Muslim 120.":
    "صحيح البخاري ٦٣٦٣؛ سنن أبي داود ١٥٥٥؛ حصن المسلم ١٢٠.",
  "Jami' at-Tirmidhi 3505; Quran 21:87; Hisn al-Muslim 121.": "جامع الترمذي ٣٥٠٥؛ القرآن ٢١:٨٧؛ حصن المسلم ١٢١.",
  "Sunan Abu Dawud 1525; Hisn al-Muslim 122.": "سنن أبي داود ١٥٢٥؛ حصن المسلم ١٢٢.",
  "Sunan Abu Dawud 5090; Hisn al-Muslim 123.": "سنن أبي داود ٥٠٩٠؛ حصن المسلم ١٢٣.",
  "Musnad Ahmad 3712; Hisn al-Muslim 120.": "مسند أحمد ٣٧١٢؛ حصن المسلم ١٢٠.",
  "Sahih Muslim 2202; Hisn al-Muslim 131.": "صحيح مسلم ٢٢٠٢؛ حصن المسلم ١٣١.",
  "Sahih al-Bukhari 7/131; Sahih Muslim 2191; Hisn al-Muslim 129.":
    "صحيح البخاري ٧/١٣١؛ صحيح مسلم ٢١٩١؛ حصن المسلم ١٢٩.",
  "Sahih Muslim 2186; Hisn al-Muslim 130.": "صحيح مسلم ٢١٨٦؛ حصن المسلم ١٣٠.",
  "Sunan Abu Dawud 3106; Jami' at-Tirmidhi 2083; Hisn al-Muslim 128.":
    "سنن أبي داود ٣١٠٦؛ جامع الترمذي ٢٠٨٣؛ حصن المسلم ١٢٨.",
  "Sahih al-Bukhari 5017; Sahih Muslim 2192; Hisn al-Muslim 132.": "صحيح البخاري ٥٠١٧؛ صحيح مسلم ٢١٩٢؛ حصن المسلم ١٣٢.",
  "Sahih Muslim 2186; Hisn al-Muslim 133.": "صحيح مسلم ٢١٨٦؛ حصن المسلم ١٣٣.",
  "Sunan Abu Dawud 5195; Hisn al-Muslim 72.": "سنن أبي داود ٥١٩٥؛ حصن المسلم ٧٢.",
  "Sahih al-Bukhari 7/125; Hisn al-Muslim 188.": "صحيح البخاري ٧/١٢٥؛ حصن المسلم ١٨٨.",
  "Jami' at-Tirmidhi 2035.": "جامع الترمذي ٢٠٣٥.",
  "Various Sahih narrations.": "روايات صحيحة متعددة.",
  "Sunan Abu Dawud 2130; Jami' at-Tirmidhi 1091; Hisn al-Muslim 98.":
    "سنن أبي داود ٢١٣٠؛ جامع الترمذي ١٠٩١؛ حصن المسلم ٩٨.",
  "Sahih Muslim 918; Hisn al-Muslim 134.": "صحيح مسلم ٩١٨؛ حصن المسلم ١٣٤.",
  "Sahih Muslim 920; Hisn al-Muslim 135.": "صحيح مسلم ٩٢٠؛ حصن المسلم ١٣٥.",
  "Sahih Muslim 899; Hisn al-Muslim 170.": "صحيح مسلم ٨٩٩؛ حصن المسلم ١٧٠.",
  "Sahih al-Bukhari 2/518; Hisn al-Muslim 171.": "صحيح البخاري ٢/٥١٨؛ حصن المسلم ١٧١.",
  "Sahih al-Bukhari 846; Sahih Muslim 71; Hisn al-Muslim 172.": "صحيح البخاري ٨٤٦؛ صحيح مسلم ٧١؛ حصن المسلم ١٧٢.",
  "Muwatta Imam Malik 2/992; Hisn al-Muslim 173.": "موطأ الإمام مالك ٢/٩٩٢؛ حصن المسلم ١٧٣.",
  "Jami' at-Tirmidhi 3451; Hisn al-Muslim 168.": "جامع الترمذي ٣٤٥١؛ حصن المسلم ١٦٨.",
  "Sunan Abu Dawud 1191; Sahih al-Bukhari 1044; Sahih Muslim 901.":
    "سنن أبي داود ١١٩١؛ صحيح البخاري ١٠٤٤؛ صحيح مسلم ٩٠١.",
  "Sahih Muslim 2725; Hisn al-Muslim 127.": "صحيح مسلم ٢٧٢٥؛ حصن المسلم ١٢٧.",
  "Sahih al-Bukhari 3293; Sahih Muslim 2691; Hisn al-Muslim 152.": "صحيح البخاري ٣٢٩٣؛ صحيح مسلم ٢٦٩١؛ حصن المسلم ١٥٢.",
  "Sahih al-Bukhari 6042; Sahih Muslim 2691; Hisn al-Muslim 153.": "صحيح البخاري ٦٠٤٢؛ صحيح مسلم ٢٦٩١؛ حصن المسلم ١٥٣.",
  "Sahih al-Bukhari 7563; Sahih Muslim 2694; Hisn al-Muslim 154.": "صحيح البخاري ٧٥٦٣؛ صحيح مسلم ٢٦٩٤؛ حصن المسلم ١٥٤.",
  "Sunan Ibn Majah 3871; Hisn al-Muslim 126.": "سنن ابن ماجه ٣٨٧١؛ حصن المسلم ١٢٦.",
  "Sahih al-Bukhari 4409; Sahih Muslim 2704; Hisn al-Muslim 155.": "صحيح البخاري ٤٤٠٩؛ صحيح مسلم ٢٧٠٤؛ حصن المسلم ١٥٥.",
  "Sahih Muslim 2696; Hisn al-Muslim 156.": "صحيح مسلم ٢٦٩٦؛ حصن المسلم ١٥٦.",
  "Sahih al-Bukhari 6306; Hisn al-Muslim 69.": "صحيح البخاري ٦٣٠٦؛ حصن المسلم ٦٩.",
  "Sunan Abu Dawud 5088; Jami' at-Tirmidhi 3388; Hisn al-Muslim 70.":
    "سنن أبي داود ٥٠٨٨؛ جامع الترمذي ٣٣٨٨؛ حصن المسلم ٧٠.",
});

/** The Arabic rendering where one exists, otherwise the reviewed English. */
export function toArabicSourceReference(englishSource: string | undefined): string | undefined {
  if (!englishSource) return undefined;
  return SOURCE_REFERENCE_ARABIC[englishSource] ?? englishSource;
}
