import type { CategoryId } from "../types";

/** Lightweight identity index used by startup-state validation without loading the devotional corpus. */
export const CATEGORY_ZIKR_IDS: Partial<Record<CategoryId, readonly string[]>> = {
  morning: [
    "m-hm-77m",
    "m-hm-78m",
    "m-hm-89m",
    "m-hm-75",
    "m-hm-76a",
    "m-hm-76b",
    "m-hm-76c",
    "m-hm-97",
    "m-hm-86",
    "m-hm-84",
    "m-hm-82",
    "m-hm-85",
    "m-hm-83",
    "m-hm-79",
    "m-hm-87",
    "m-hm-90m",
    "m-hm-80m",
    "m-hm-81m",
    "m-hm-88",
    "m-hm-95",
    "m-hm-91",
    "m-hm-93",
    "m-hm-94",
    "m-hm-96",
    "m-hm-98",
  ],
  evening: [
    "e-hm-77e",
    "e-hm-78e",
    "e-hm-89e",
    "e-hm-75",
    "e-hm-76a",
    "e-hm-76b",
    "e-hm-76c",
    "e-hm-86",
    "e-hm-97",
    "e-hm-84",
    "e-hm-82",
    "e-hm-85",
    "e-hm-83",
    "e-hm-79",
    "e-hm-87",
    "e-hm-90e",
    "e-hm-80e",
    "e-hm-81e",
    "e-hm-88",
    "e-hm-91",
    "e-hm-92",
    "e-hm-96",
    "e-hm-98",
  ],
  before_sleep: [
    "s-hm-100",
    "s-hm-101",
    "s-hm-99-ikhlas",
    "s-hm-99-falaq",
    "s-hm-99-nas",
    "s-hm-109a",
    "s-hm-110a",
    "s-hm-110b",
    "s-hm-102",
    "s-hm-105",
    "s-hm-104",
    "s-hm-108",
    "s-hm-107",
    "s-hm-109",
    "s-hm-106-subhanallah",
    "s-hm-106-alhamdulillah",
    "s-hm-106-allahu-akbar",
    "s-hm-111",
  ],
  waking_up: ["wu-hm-1", "wu-hm-2", "wu-hm-3", "wu-hm-4"],
  home: ["home-hm-15", "home-hm-16", "home-hm-17", "home-hm-18"],
  mosque: ["msq-hm-20", "msq-hm-21", "msq-hm-22", "msq-hm-23"],
  after_prayer: [
    "ap-ref-1",
    "ap-ref-2",
    "ap-ref-9",
    "ap-ref-12a",
    "ap-ref-12b",
    "ap-ref-12c",
    "ap-ref-3",
    "ap-ref-4",
    "ap-tasbeeh-subhanallah",
    "ap-tasbeeh-alhamdulillah",
    "ap-tasbeeh-allahuakbar",
    "ap-tasbeeh-tawhid",
    "ap-ref-6",
    "ap-ref-8",
    "ap-ref-7",
    "ap-ref-10",
  ],
  in_prayer: [
    "in-prayer-opening-forgiveness",
    "in-prayer-opening-praise",
    "in-prayer-ruku-tasbih",
    "in-prayer-ruku-submission",
    "in-prayer-ruku-sujud-forgiveness",
    "in-prayer-ruku-sujud-holy",
    "in-prayer-ruku-sujud-majesty",
    "in-prayer-rising-praise",
    "in-prayer-rising-abundant-praise",
    "in-prayer-sujud-tasbih",
    "in-prayer-sujud-submission",
    "in-prayer-sujud-complete-forgiveness",
    "in-prayer-sujud-refuge",
    "in-prayer-sujud-tilawah",
    "in-prayer-between-prostrations",
    "in-prayer-between-prostrations-brief",
    "in-prayer-tashahhud",
    "in-prayer-ibrahimiyyah",
    "in-prayer-before-salam-refuge",
    "in-prayer-before-salam-self-forgiveness",
    "in-prayer-before-salam-comprehensive",
    "in-prayer-before-salam-forgiveness",
    "in-prayer-witr-qunut",
  ],
  fasting_ramadan: [
    "fasting-suhur-blessing",
    "fasting-iftar-supplication",
    "fasting-affront-response",
    "fasting-laylat-al-qadr",
    "fasting-witr-completion",
    "fasting-iftar-host",
  ],
  restroom: ["pur-ref-1", "pur-ref-2", "pur-ref-3", "pur-ref-4", "pur-ref-5", "pur-ref-6"],
  food_drink: [
    "fd-ref-1",
    "fd-ref-2",
    "fd-ref-3",
    "fd-ref-4",
    "fd-ref-5",
    "fd-ref-6",
    "fd-ref-7",
    "fd-ref-8",
    "fd-ref-9",
  ],
  clothing: ["clo-ref-1", "clo-ref-2", "clo-ref-3", "clo-ref-4"],
  travel: ["tr-ref-1", "tr-ref-2", "tr-ref-3", "tr-ref-5", "tr-ref-6", "tr-ref-7", "tr-ref-8", "tr-ref-4", "tr-ref-9"],
  distress_anxiety: ["da-ref-1", "da-ref-2", "da-ref-3", "da-ref-4", "da-ref-5", "da-ref-6", "da-ref-7", "da-ref-8"],
  illness_ruqyah: ["ir-ref-1", "ir-ref-2", "ir-ref-3", "ir-ref-4", "ir-ref-5", "ir-ref-6", "ir-ref-7", "ir-baqarah"],
  social_community: [
    "sc-ref-1",
    "sc-ref-2",
    "sc-ref-3",
    "sc-ref-4",
    "sc-ref-5",
    "sc-ref-6",
    "sc-ref-7",
    "sc-ref-8",
    "sc-ref-9",
    "sc-ref-10",
    "sc-ref-11",
    "sc-ref-12",
    "sc-ref-13",
    "sc-ref-14",
  ],
  natural_events: ["ne-ref-1", "ne-ref-2", "ne-ref-3", "ne-ref-4", "ne-ref-5", "ne-ref-6", "ne-ref-7"],
  miscellaneous: [
    "misc-ref-1",
    "misc-ref-2",
    "misc-ref-3",
    "misc-ref-4",
    "misc-ref-5",
    "misc-ref-6",
    "misc-ref-7",
    "misc-ref-8",
    "misc-ref-9",
    "misc-ref-10",
    "misc-ref-11",
    "misc-ref-12",
    "misc-ref-13",
    "misc-ref-14",
  ],
};

export const ALL_STATIC_ZIKR_IDS = new Set([
  ...Object.values(CATEGORY_ZIKR_IDS).flat(),
  "m-hm-75a",
  "e-hm-75a",
  "in-prayer-introduction",
  "fasting-introduction",
]);
