import type { CategoryId, Zikr } from "../types";

const MORNING_AZKAR: Zikr[] = [
  { id:"m1", category:"morning", orderIndex:0,
    arabicText:"اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ\nلَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ",
    transliteration:"Allahu la ilaha illa huwal-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm",
    translation:"Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.",
    benefit:"Whoever recites Ayat al-Kursi in the morning will be protected by Allah until evening, and whoever recites it in the evening will be protected until morning.",
    repetitionCount:1, sourceReference:"Bukhari · 5010" },
  { id:"m2", category:"morning", orderIndex:1,
    arabicText:"أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ\nوَالْحَمْدُ لِلَّهِ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    transliteration:"Asbahna wa asbahal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah",
    translation:"We have reached the morning and at this very time unto Allah belongs all sovereignty, and all praise is for Allah.",
    benefit:"The Prophet ﷺ used to say this every morning. It is a declaration of Allah's ownership of all things at the start of the day.",
    repetitionCount:1, sourceReference:"Muslim · 2723" },
  { id:"m3", category:"morning", orderIndex:2,
    arabicText:"اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا\nوَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    transliteration:"Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu, wa ilaykan-nushur",
    translation:"O Allah, by Your leave we have reached the morning and by Your leave we reach the evening, by You we live and by You we die, and unto You is our resurrection.",
    benefit:"This supplication acknowledges Allah's complete control over our lives — morning, evening, life and death.",
    repetitionCount:1, sourceReference:"Tirmidhi · 3391" },
  { id:"m4", category:"morning", orderIndex:3,
    arabicText:"سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration:"Subhanallahi wa bihamdih",
    translation:"Glory is to Allah and praise is to Him.",
    benefit:"Whoever says this 100 times in the morning will have his sins forgiven even if they are like the foam of the sea.",
    repetitionCount:100, sourceReference:"Bukhari · 6405" },
  { id:"m5", category:"morning", orderIndex:4,
    arabicText:"اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ",
    transliteration:"Allahumma salli wa sallim 'ala nabiyyina Muhammad",
    translation:"O Allah, send prayers and peace upon our Prophet Muhammad.",
    benefit:"Whoever sends blessings upon me once, Allah sends blessings upon him tenfold and erases ten sins from him.",
    repetitionCount:10, sourceReference:"Muslim · 408" },
  { id:"m6", category:"morning", orderIndex:5,
    arabicText:"رَضِيتُ بِاللَّهِ رَبًّا وَبِالإِسْلَامِ دِينًا\nوَبِمُحَمَّدٍ ﷺ نَبِيًّا",
    transliteration:"Radeetu billahi rabban, wa bil-islami deenan, wa bi-muhammadin sallallahu 'alayhi wa sallama nabiyya",
    translation:"I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as my Prophet.",
    benefit:"It is the right of Allah upon every Muslim who says this three times each morning and evening that He should please them on the Day of Resurrection.",
    repetitionCount:3, sourceReference:"Abu Dawud · 5072" },
  { id:"m7", category:"morning", orderIndex:6,
    arabicText:"يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ\nأَصْلِحْ لِي شَأْنِي كُلَّهُ",
    transliteration:"Ya Hayyu ya Qayyumu, birahmatika astaghith, aslih li sha'ni kullahu",
    translation:"O Ever-Living, O Self-Sustaining, by Your mercy I seek assistance. Rectify for me all of my affairs.",
    benefit:"The Prophet ﷺ taught this to Fatimah (may Allah be pleased with her) to recite every morning and evening.",
    repetitionCount:1, sourceReference:"Hakim · 1/545" },
  { id:"m8", category:"morning", orderIndex:7,
    arabicText:"أَصْبَحْتُ أُشْهِدُ اللَّهَ وَحَمَلَةَ عَرْشِهِ\nوَمَلَائِكَتَهُ وَجَمِيعَ خَلْقِهِ أَنَّهُ لَا إِلَهَ إِلَّا هُوَ",
    transliteration:"Asbahtu ushhidullaha wa hamalata 'arshih, wa mala'ikatahu wa jami'a khalqih, annahu la ilaha illa hu",
    translation:"I take as witness Allah and His angels who carry the Throne, and all of His creation: that there is no deity except Him.",
    benefit:"Whoever says this four times in the morning, Allah frees a quarter of them from the Fire for each recitation.",
    repetitionCount:4, sourceReference:"Abu Dawud · 5069" },
  { id:"m9", category:"morning", orderIndex:8,
    arabicText:"اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ\nفِي الدُّنْيَا وَالْآخِرَةِ",
    transliteration:"Allahumma inni as'alukal-'afiyata fid-dunya wal-akhirah",
    translation:"O Allah, I ask You for well-being in this world and in the Hereafter.",
    benefit:"No one has been given anything better than well-being and certainty, so ask Allah for them.",
    repetitionCount:1, sourceReference:"Ibn Majah · 3871" },
  { id:"m10", category:"morning", orderIndex:9,
    arabicText:"سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ\nوَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ",
    transliteration:"Subhanallah, walhamdu lillah, wa la ilaha illallah, wallahu akbar",
    translation:"Glory is to Allah, and praise is to Allah, and none has the right to be worshipped except Allah, and Allah is the Greatest.",
    benefit:"These four phrases are the most beloved words to Allah. It does not matter which one you start with.",
    repetitionCount:33, sourceReference:"Muslim · 2137" },
  { id:"m11", category:"morning", orderIndex:10,
    arabicText:"اللَّهُمَّ عَافِنِي فِي بَدَنِي\nاللَّهُمَّ عَافِنِي فِي سَمْعِي وَبَصَرِي",
    transliteration:"Allahumma 'afini fi badani, Allahumma 'afini fi sam'i wa basari",
    translation:"O Allah, grant me health in my body. O Allah, grant me health in my hearing and sight.",
    benefit:"Abu Bakr (may Allah be pleased with him) used to recite this supplication every morning and evening.",
    repetitionCount:3, sourceReference:"Abu Dawud · 5090" },
  { id:"m12", category:"morning", orderIndex:11,
    arabicText:"اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ\nوَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ",
    transliteration:"Allahumma inni a'udhu bika minal-kufri wal-faqr, wa a'udhu bika min 'adhabil-qabr",
    translation:"O Allah, I seek refuge with You from disbelief and poverty, and I seek refuge with You from the punishment of the grave.",
    benefit:"This supplication protects against three of the greatest trials: disbelief, poverty, and punishment in the grave.",
    repetitionCount:3, sourceReference:"Abu Dawud · 5090" },
  { id:"m13", category:"morning", orderIndex:12,
    arabicText:"حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ\nعَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration:"Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu wa huwa rabbul-'arshil-'azim",
    translation:"Allah is sufficient for me. None has the right to be worshipped except Him. Upon Him I rely and He is the Lord of the Exalted Throne.",
    benefit:"Whoever says this seven times each morning and evening, Allah will take care of whatever concerns them.",
    repetitionCount:7, sourceReference:"Abu Dawud · 5081" },
  { id:"m14", category:"morning", orderIndex:13,
    arabicText:"بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ\nفِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration:"Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'alim",
    translation:"In the name of Allah with whose name nothing is harmed on earth nor in the heavens, and He is the All-Hearing, the All-Knowing.",
    benefit:"Whoever says this three times in the morning will not be struck by any affliction until the evening.",
    repetitionCount:3, sourceReference:"Tirmidhi · 3388" },
  { id:"m15", category:"morning", orderIndex:14,
    arabicText:"اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ\nخَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ",
    transliteration:"Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't",
    translation:"O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant.",
    benefit:"Sayyidul Istighfar — the master supplication for forgiveness. Whoever says it with conviction in the morning and dies that day enters Paradise.",
    repetitionCount:1, sourceReference:"Bukhari · 6306" },
];

const EVENING_AZKAR: Zikr[] = [
  { id:"e1", category:"evening", orderIndex:0,
    arabicText:"أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ\nوَالْحَمْدُ لِلَّهِ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    transliteration:"Amsayna wa amsal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah",
    translation:"We have reached the evening and at this very time unto Allah belongs all sovereignty, and all praise is for Allah.",
    benefit:"The evening version of the morning supplication, declaring Allah's sovereignty as the day draws to a close.",
    repetitionCount:1, sourceReference:"Muslim · 2723" },
  { id:"e2", category:"evening", orderIndex:1,
    arabicText:"اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا\nوَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    transliteration:"Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namutu, wa ilaykal-masir",
    translation:"O Allah, by Your leave we have reached the evening and by Your leave we reach the morning, by You we live and by You we die, and unto You is the final return.",
    benefit:"A reminder at day's end that all affairs belong to Allah, and we return to Him.",
    repetitionCount:1, sourceReference:"Tirmidhi · 3391" },
  { id:"e3", category:"evening", orderIndex:2,
    arabicText:"أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ\nمِنْ شَرِّ مَا خَلَقَ",
    transliteration:"A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    translation:"I seek refuge in the perfect words of Allah from the evil of what He has created.",
    benefit:"Whoever says this three times in the evening will be protected from snake bites and scorpion stings that night.",
    repetitionCount:3, sourceReference:"Muslim · 2709" },
  { id:"e4", category:"evening", orderIndex:3,
    arabicText:"اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ\nوَحَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ أَنَّكَ اللَّهُ",
    transliteration:"Allahumma inni amsaytu ushhiduka wa hamalata 'arshika wa mala'ikataka wa jami'a khalqika annakallah",
    translation:"O Allah, I have reached the evening taking You as witness, and the bearers of Your Throne, Your angels, and all Your creation, that You are Allah.",
    benefit:"Whoever says this four times in the evening, Allah will free a quarter of him from the Fire for each recitation.",
    repetitionCount:4, sourceReference:"Abu Dawud · 5069" },
  { id:"e5", category:"evening", orderIndex:4,
    arabicText:"سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration:"Subhanallahi wa bihamdih",
    translation:"Glory is to Allah and praise is to Him.",
    benefit:"Whoever says this 100 times in the evening will have his sins forgiven even if they are like the foam of the sea.",
    repetitionCount:100, sourceReference:"Bukhari · 6405" },
  { id:"e6", category:"evening", orderIndex:5,
    arabicText:"اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ\nفَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
    transliteration:"Allahumma ma amsa bi min ni'matin faminka wahdaka la shareeka lak, falakal-hamdu wa lakash-shukr",
    translation:"O Allah, what blessing I have reached this evening is from You alone, without partner, so for You is all praise and unto You all thanks.",
    benefit:"Whoever says this in the evening has given thanks for that day.",
    repetitionCount:1, sourceReference:"Abu Dawud · 5073" },
  { id:"e7", category:"evening", orderIndex:6,
    arabicText:"اللَّهُمَّ فَاطِرَ السَّمَوَاتِ وَالأَرْضِ\nعَالِمَ الغَيْبِ وَالشَّهَادَةِ رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ",
    transliteration:"Allahumma fatiras-samawati wal-ard, 'alimal-ghaybi wash-shahadah, rabba kulli shay'in wa malikah",
    translation:"O Allah, Creator of the heavens and earth, Knower of the seen and unseen, Lord and Sovereign of all things.",
    benefit:"The Prophet ﷺ taught this to be recited each morning and evening to renew one's submission to Allah.",
    repetitionCount:1, sourceReference:"Abu Dawud · 5070" },
  { id:"e8", category:"evening", orderIndex:7,
    arabicText:"اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ\nفِي الدُّنْيَا وَالآخِرَةِ",
    transliteration:"Allahumma inni as'alukal-'afwa wal-'afiyata fid-dunya wal-akhirah",
    translation:"O Allah, I ask You for pardon and well-being in this world and the Hereafter.",
    benefit:"Ibn Umar (may Allah be pleased with him) never left these words morning or evening. They gather for you the good of this world and the Hereafter.",
    repetitionCount:1, sourceReference:"Ibn Majah · 3871" },
  { id:"e9", category:"evening", orderIndex:8,
    arabicText:"بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ\nفِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration:"Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'alim",
    translation:"In the name of Allah with whose name nothing is harmed on earth nor in the heavens, and He is the All-Hearing, the All-Knowing.",
    benefit:"Whoever says this three times in the evening will not be struck by any affliction until the morning.",
    repetitionCount:3, sourceReference:"Tirmidhi · 3388" },
  { id:"e10", category:"evening", orderIndex:9,
    arabicText:"حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ\nعَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration:"Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu wa huwa rabbul-'arshil-'azim",
    translation:"Allah is sufficient for me. None has the right to be worshipped except Him. Upon Him I rely and He is the Lord of the Exalted Throne.",
    benefit:"Whoever says this seven times each evening, Allah will take care of whatever concerns them.",
    repetitionCount:7, sourceReference:"Abu Dawud · 5081" },
  { id:"e11", category:"evening", orderIndex:10,
    arabicText:"اللَّهُمَّ عَافِنِي فِي بَدَنِي\nاللَّهُمَّ عَافِنِي فِي سَمْعِي وَبَصَرِي",
    transliteration:"Allahumma 'afini fi badani, Allahumma 'afini fi sam'i wa basari",
    translation:"O Allah, grant me health in my body. O Allah, grant me health in my hearing and sight.",
    benefit:"A supplication for comprehensive wellbeing recited by the righteous every evening.",
    repetitionCount:3, sourceReference:"Abu Dawud · 5090" },
  { id:"e12", category:"evening", orderIndex:11,
    arabicText:"اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ",
    transliteration:"Allahumma salli wa sallim 'ala nabiyyina Muhammad",
    translation:"O Allah, send prayers and peace upon our Prophet Muhammad.",
    benefit:"Sending blessings upon the Prophet ﷺ in the evening is from the Sunnah and brings abundant reward.",
    repetitionCount:10, sourceReference:"Muslim · 408" },
  { id:"e13", category:"evening", orderIndex:12,
    arabicText:"يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ\nأَصْلِحْ لِي شَأْنِي كُلَّهُ وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ",
    transliteration:"Ya Hayyu ya Qayyumu, birahmatika astaghith, aslih li sha'ni kullahu, wa la takilni ila nafsi tarfata 'ayn",
    translation:"O Ever-Living, O Self-Sustaining, by Your mercy I seek assistance. Rectify for me all of my affairs and do not leave me to myself, even for the blink of an eye.",
    benefit:"The Prophet ﷺ taught Fatimah (may Allah be pleased with her) to say this morning and evening as her daily protection.",
    repetitionCount:1, sourceReference:"Hakim · 1/545" },
  { id:"e14", category:"evening", orderIndex:13,
    arabicText:"أَعُوذُ بِاللَّهِ السَّمِيعِ الْعَلِيمِ\nمِنَ الشَّيْطَانِ الرَّجِيمِ",
    transliteration:"A'udhu billahis-sami'il-'alimi minash-shaytanir-rajim",
    translation:"I seek refuge in Allah, the All-Hearing, the All-Knowing, from the outcast Shaytan.",
    benefit:"Seeking refuge from Shaytan in the evening protects one through the night from his whispers and plots.",
    repetitionCount:3, sourceReference:"Tirmidhi · 3392" },
  { id:"e15", category:"evening", orderIndex:14,
    arabicText:"اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ\nخَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ",
    transliteration:"Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't",
    translation:"O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant.",
    benefit:"Sayyidul Istighfar — the master supplication for forgiveness. Whoever says it with conviction in the evening and dies that night enters Paradise.",
    repetitionCount:1, sourceReference:"Bukhari · 6306" },
];

const SLEEP_AZKAR: Zikr[] = [
  { id:"s1", category:"before_sleep", orderIndex:0,
    arabicText:"بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration:"Bismika Allahumma amutu wa ahya",
    translation:"In Your name O Allah, I die and I live.",
    benefit:"The Prophet ﷺ would say this when lying down to sleep, acknowledging that sleep is a minor form of death.",
    repetitionCount:1, sourceReference:"Bukhari · 6312" },
  { id:"s2", category:"before_sleep", orderIndex:1,
    arabicText:"اللَّهُمَّ قِنِي عَذَابَكَ\nyَوْمَ تَبْعَثُ عِبَادَكَ",
    transliteration:"Allahumma qini 'adhabaka yawma tab'athu 'ibadak",
    translation:"O Allah, protect me from Your punishment on the Day when You resurrect Your servants.",
    benefit:"The Prophet ﷺ would say this three times before sleeping, seeking protection from the punishment of the grave.",
    repetitionCount:3, sourceReference:"Abu Dawud · 5045" },
  { id:"s3", category:"before_sleep", orderIndex:2,
    arabicText:"سُبْحَانَ اللَّهِ",
    transliteration:"Subhanallah",
    translation:"Glory is to Allah.",
    benefit:"The Prophet ﷺ told Ali and Fatimah to say SubhanAllah 33 times, Alhamdulillah 33 times, and Allahu Akbar 34 times before sleeping — this is better than a servant for you.",
    repetitionCount:33, sourceReference:"Bukhari · 5362" },
  { id:"s4", category:"before_sleep", orderIndex:3,
    arabicText:"الْحَمْدُ لِلَّهِ",
    transliteration:"Alhamdulillah",
    translation:"All praise is for Allah.",
    benefit:"Part of the pre-sleep tasbih taught by the Prophet ﷺ to his daughter Fatimah. Saying Alhamdulillah 33 times before sleep brings immense blessings.",
    repetitionCount:33, sourceReference:"Bukhari · 5362" },
  { id:"s5", category:"before_sleep", orderIndex:4,
    arabicText:"اللَّهُ أَكْبَرُ",
    transliteration:"Allahu Akbar",
    translation:"Allah is the Greatest.",
    benefit:"The final part of the pre-sleep tasbih: 34 times Allahu Akbar. Better than a servant to help you with your needs.",
    repetitionCount:34, sourceReference:"Bukhari · 5362" },
  { id:"s6", category:"before_sleep", orderIndex:5,
    arabicText:"اللَّهُمَّ بِاسْمِكَ أَحْيَا وَأَمُوتُ",
    transliteration:"Allahumma bismika ahya wa amut",
    translation:"O Allah, with Your name I live and with Your name I die.",
    benefit:"Beginning one's sleep with the name of Allah is a Sunnah act that brings blessings and protection throughout the night.",
    repetitionCount:1, sourceReference:"Bukhari · 6324" },
  { id:"s7", category:"before_sleep", orderIndex:6,
    arabicText:"اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ\nوَفَوَّضْتُ أَمْرِي إِلَيْكَ وَوَجَّهْتُ وَجْهِي إِلَيْكَ",
    transliteration:"Allahumma aslamtu nafsi ilayk, wa fawwadtu amri ilayk, wa wajjahtu wajhi ilayk",
    translation:"O Allah, I submit myself to You, entrust my affairs to You, and turn my face toward You.",
    benefit:"The Prophet ﷺ instructed: If you die this night, you die upon the fitrah.",
    repetitionCount:1, sourceReference:"Bukhari · 247" },
  { id:"s8", category:"before_sleep", orderIndex:7,
    arabicText:"قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ\nلَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    transliteration:"Qul huwa Allahu ahad, Allahus-samad, lam yalid wa lam yulad, wa lam yakun lahu kufuwan ahad",
    translation:"Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent.",
    benefit:"The Prophet ﷺ used to recite Al-Ikhlas, Al-Falaq, and An-Nas three times each before sleeping, then wipe over his body.",
    repetitionCount:3, sourceReference:"Abu Dawud · 5056" },
  { id:"s9", category:"before_sleep", orderIndex:8,
    arabicText:"قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ\nوَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ",
    transliteration:"Qul a'udhu biraббil-falaq, min sharri ma khalaq, wa min sharri ghasiqin idha waqab",
    translation:"Say: I seek refuge in the Lord of daybreak from the evil of that which He created, and from the evil of darkness when it settles.",
    benefit:"Surah Al-Falaq, recited three times before sleep. The Prophet ﷺ said there is no protection like it.",
    repetitionCount:3, sourceReference:"Abu Dawud · 5056" },
  { id:"s10", category:"before_sleep", orderIndex:9,
    arabicText:"قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَهِ النَّاسِ\nمِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ",
    transliteration:"Qul a'udhu birabbin-nas, malikin-nas, ilahin-nas, min sharril-waswasil-khannas",
    translation:"Say: I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer.",
    benefit:"Surah An-Nas, the final protection before sleep. Reciting the last two surahs creates a shield through the night.",
    repetitionCount:3, sourceReference:"Abu Dawud · 5056" },
];

const ALL_AZKAR = [...MORNING_AZKAR, ...EVENING_AZKAR, ...SLEEP_AZKAR];

// ─── Helpers ──────────────────────────────────────────────────────────────────
const getAzkarByCategory = (cat: CategoryId) =>
  ALL_AZKAR.filter(z => z.category === cat).sort((a, b) => a.orderIndex - b.orderIndex);

const ZIKR_LABELS: Record<string, string> = Object.fromEntries(
  ALL_AZKAR.map((z) => [z.id, z.translation.split(".")[0] ?? z.transliteration])
);

export { ALL_AZKAR, EVENING_AZKAR, MORNING_AZKAR, SLEEP_AZKAR, ZIKR_LABELS, getAzkarByCategory };
