import type { ZikrDraft } from "../types";

const reference = "An established wording for this stage of the prayer.";
const referenceArabic = "لفظ ثابت لهذا الموضع من الصلاة.";

export const IN_PRAYER_AZKAR: ZikrDraft[] = [
  {
    id: "in-prayer-introduction",
    category: "in_prayer",
    orderIndex: 0,
    arabicText: "أذكار الصلاة",
    transliteration: "",
    translation: "In-prayer Sunnah supplications",
    benefit:
      "A stage-by-stage reference for established wording within the prayer. Where more than one authentic wording exists, choose one; do not treat every entry as a single required checklist.",
    benefitArabic:
      "مرجع مرتب بحسب مواضع الصلاة للألفاظ الثابتة. عند تعدد الصيغ الصحيحة يُختار منها، ولا تُعامل العناصر كلها كقائمة واجبة في صلاة واحدة.",
    repetitionCount: 1,
    sourceReference: "Editorial scope note; see the cited evidence on each item.",
    sourceReferenceArabic: "تنبيه تحريري؛ يُرجع إلى دليل كل عنصر.",
    isCollectionIntroduction: true,
  },
  {
    id: "in-prayer-opening-forgiveness",
    category: "in_prayer",
    orderIndex: 1,
    arabicText:
      "اللَّهُمَّ بَاعِدْ بَيْنِي وَبَيْنَ خَطَايَايَ كَمَا بَاعَدْتَ بَيْنَ الْمَشْرِقِ وَالْمَغْرِبِ، اللَّهُمَّ نَقِّنِي مِنْ خَطَايَايَ كَمَا يُنَقَّى الثَّوْبُ الْأَبْيَضُ مِنَ الدَّنَسِ، اللَّهُمَّ اغْسِلْ خَطَايَايَ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ",
    transliteration:
      "Allahumma ba'id bayni wa bayna khatayaya kama ba'adta baynal-mashriqi wal-maghrib. Allahumma naqqini min khatayaya kama yunaqqa ath-thawb al-abyadu min ad-danas. Allahummaghsil khatayaya bil-ma'i wath-thalji wal-barad.",
    translation:
      "O Allah, distance me from my sins as You have distanced the East from the West. O Allah, cleanse me of my sins as a white garment is cleansed of filth. O Allah, wash away my sins with water, snow, and hail.",
    benefit: reference,
    benefitArabic: referenceArabic,
    repetitionCount: 1,
    sourceReference: "Sahih al-Bukhari 744.",
    sourceReferenceArabic: "صحيح البخاري ٧٤٤.",
    preferredTiming: "After the opening takbir, before recitation.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/bukhari%3A744",
  },
  {
    id: "in-prayer-opening-praise",
    category: "in_prayer",
    orderIndex: 2,
    arabicText: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ",
    transliteration: "Subhanaka Allahumma wa bihamdika, wa tabarakasmuka, wa ta'ala jadduka, wa la ilaha ghayruk.",
    translation:
      "Glory and praise be to You, O Allah. Blessed is Your name, exalted is Your majesty, and none is worthy of worship but You.",
    benefit:
      "An established alternative opening supplication reported for night prayer; choose one opening formula rather than combining them.",
    benefitArabic:
      "صيغة ثابتة بديلة لدعاء الاستفتاح وردت في صلاة الليل؛ يُختار دعاء استفتاح واحد ولا تُجمع الصيغ على أنها لازمة.",
    repetitionCount: 1,
    sourceReference: "Sunan Abi Dawud 775 (Sahih, al-Albani).",
    sourceReferenceArabic: "سنن أبي داود ٧٧٥ (صحيح، الألباني).",
    preferredTiming: "After the opening takbir in night prayer, before recitation.",
    authenticityNote: "Sahih according to Al-Albani.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/abudawud/2/385",
  },
  {
    id: "in-prayer-ruku-tasbih",
    category: "in_prayer",
    orderIndex: 3,
    arabicText: "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
    transliteration: "Subhana Rabbiyal-'Azim.",
    translation: "Glory be to my Lord, the Magnificent.",
    benefit: "Established glorification in bowing. The reviewed reference gives three repetitions.",
    benefitArabic: "تسبيح ثابت في الركوع، ويذكر المرجع المحقق ثلاث تسبيحات.",
    repetitionCount: 3,
    sourceReference: "Hisn al-Muslim 33; see Al-Albani, Sahih at-Tirmidhi 1/83.",
    sourceReferenceArabic: "حصن المسلم ٣٣؛ وانظر صحيح الترمذي للألباني ١/٨٣.",
    preferredTiming: "While bowing (ruku').",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/hisn%3A33",
  },
  {
    id: "in-prayer-ruku-submission",
    category: "in_prayer",
    orderIndex: 4,
    arabicText:
      "اللَّهُمَّ لَكَ رَكَعْتُ، وَبِكَ آمَنْتُ، وَلَكَ أَسْلَمْتُ، خَشَعَ لَكَ سَمْعِي وَبَصَرِي، وَمُخِّي وَعَظْمِي وَعَصَبِي",
    transliteration:
      "Allahumma laka raka'tu, wa bika amantu, wa laka aslamtu, khasha'a laka sam'i wa basari, wa mukhki wa 'azmi wa 'asabi.",
    translation:
      "O Allah, unto You I bow, in You I believe, and unto You I submit. Submissive to You are my hearing, my sight, my marrow, my bones, and my nerves.",
    benefit: "An authentic, deeply submissive Prophetic supplication in bowing.",
    benefitArabic: "دعاء خضوع وتعظيم نبوي ثابت في الركوع.",
    repetitionCount: 1,
    sourceReference: "Sahih Muslim 771.",
    sourceReferenceArabic: "صحيح مسلم ٧٧١.",
    preferredTiming: "While bowing (ruku').",
    authenticityNote: "Sahih Muslim.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/muslim%3A771",
  },
  {
    id: "in-prayer-ruku-sujud-forgiveness",
    category: "in_prayer",
    orderIndex: 5,
    arabicText: "سُبْحَانَكَ اللَّهُمَّ رَبَّنَا وَبِحَمْدِكَ، اللَّهُمَّ اغْفِرْ لِي",
    transliteration: "Subhanaka Allahumma Rabbana wa bihamdika, Allahummaghfir li.",
    translation: "Glory and praise be to You, O Allah our Lord. O Allah, forgive me.",
    benefit: "A Prophetic supplication said frequently in both bowing and prostration.",
    benefitArabic: "دعاء نبوي كان يكثر منه في الركوع والسجود.",
    repetitionCount: 1,
    sourceReference: "Sahih al-Bukhari 794; Sahih Muslim 484a.",
    sourceReferenceArabic: "صحيح البخاري ٧٩٤؛ صحيح مسلم ٤٨٤أ.",
    preferredTiming: "An alternative supplication in bowing or prostration.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/muslim/4/247",
  },
  {
    id: "in-prayer-ruku-sujud-holy",
    category: "in_prayer",
    orderIndex: 6,
    arabicText: "سُبُّوحٌ قُدُّوسٌ، رَبُّ الْمَلَائِكَةِ وَالرُّوحِ",
    transliteration: "Subbuhun Quddusun, Rabbul-mala'ikati war-ruh.",
    translation: "All-Glorious, All-Holy, Lord of the angels and the Spirit.",
    benefit: "Another established wording used in both bowing and prostration.",
    benefitArabic: "صيغة ثابتة أخرى تُقال في الركوع والسجود.",
    repetitionCount: 1,
    sourceReference: "Sunan Abi Dawud 872 (Sahih, al-Albani); also reported by Muslim.",
    sourceReferenceArabic: "سنن أبي داود ٨٧٢ (صحيح، الألباني)؛ ورواه مسلم.",
    preferredTiming: "An alternative supplication in bowing or prostration.",
    authenticityNote: "Sahih according to Al-Albani.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/abudawud/2/482",
  },
  {
    id: "in-prayer-ruku-sujud-majesty",
    category: "in_prayer",
    orderIndex: 7,
    arabicText: "سُبْحَانَ ذِي الْجَبَرُوتِ وَالْمَلَكُوتِ وَالْكِبْرِيَاءِ وَالْعَظَمَةِ",
    transliteration: "Subhana dhil-jabaruti wal-malakuti wal-kibriya'i wal-'azamah.",
    translation: "Glory be to the Possessor of absolute power, the dominion, grandeur, and supreme majesty.",
    benefit: "A powerful glorification reported in both bowing and prostration during night prayer.",
    benefitArabic: "تسبيح عظيم ثابت في الركوع والسجود في صلاة الليل.",
    repetitionCount: 1,
    sourceReference: "Sunan Abi Dawud 873; Sunan an-Nasa'i 1049.",
    sourceReferenceArabic: "سنن أبي داود ٨٧٣؛ وسنن النسائي ١٠٤٩.",
    preferredTiming: "While bowing or prostrating, especially in night prayer.",
    authenticityNote: "Sahih according to Al-Albani.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/abudawud%3A873",
  },
  {
    id: "in-prayer-rising-praise",
    category: "in_prayer",
    orderIndex: 8,
    arabicText: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا وَلَكَ الْحَمْدُ",
    transliteration: "Sami'a Allahu liman hamidah. Rabbana wa lakal-hamd.",
    translation: "Allah hears the one who praises Him. Our Lord, all praise is for You.",
    benefit:
      "Established wording when rising from bowing; the imam says the first phrase and the worshipper responds with praise according to their prayer role.",
    benefitArabic: "لفظ ثابت عند الرفع من الركوع؛ يقول الإمام التحميد الأول ويتبع المصلي بالحمد بحسب موضعه في الصلاة.",
    repetitionCount: 1,
    sourceReference: "Sahih al-Bukhari 795.",
    sourceReferenceArabic: "صحيح البخاري ٧٩٥.",
    preferredTiming: "On rising from bowing (ruku').",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/bukhari/10/190",
  },
  {
    id: "in-prayer-rising-abundant-praise",
    category: "in_prayer",
    orderIndex: 9,
    arabicText: "رَبَّنَا وَلَكَ الْحَمْدُ، حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ",
    transliteration: "Rabbana wa lakal-hamdu, hamdan kathiran tayyiban mubarakan fih.",
    translation: "Our Lord, all praise is Yours—abundant, good, and blessed praise.",
    benefit: "A praise approved by the Prophet ﷺ; he reported that more than thirty angels hastened to record it.",
    benefitArabic: "حمد أقرّه النبي ﷺ، وأخبر أن بضعة وثلاثين ملكًا ابتدروا كتابته.",
    repetitionCount: 1,
    sourceReference: "Sahih al-Bukhari 799.",
    sourceReferenceArabic: "صحيح البخاري ٧٩٩.",
    preferredTiming: "On rising from bowing (ruku').",
    attributionType: "approved_by_prophet",
    sourceUrl: "https://sunnah.com/bukhari%3A799",
  },
  {
    id: "in-prayer-sujud-tasbih",
    category: "in_prayer",
    orderIndex: 10,
    arabicText: "سُبْحَانَ رَبِّيَ الْأَعْلَى",
    transliteration: "Subhana Rabbiyal-A'la.",
    translation: "Glory be to my Lord, the Most High.",
    benefit: "Established glorification in prostration. The reviewed reference gives three repetitions.",
    benefitArabic: "تسبيح ثابت في السجود، ويذكر المرجع المحقق ثلاث تسبيحات.",
    repetitionCount: 3,
    sourceReference: "Hisn al-Muslim 41; see Al-Albani, Sahih at-Tirmidhi 1/83.",
    sourceReferenceArabic: "حصن المسلم ٤١؛ وانظر صحيح الترمذي للألباني ١/٨٣.",
    preferredTiming: "While prostrating (sujud).",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/hisn%3A41",
  },
  {
    id: "in-prayer-sujud-submission",
    category: "in_prayer",
    orderIndex: 11,
    arabicText:
      "اللَّهُمَّ لَكَ سَجَدْتُ، وَبِكَ آمَنْتُ، وَلَكَ أَسْلَمْتُ، سَجَدَ وَجْهِي لِلَّذِي خَلَقَهُ وَصَوَّرَهُ، وَشَقَّ سَمْعَهُ وَبَصَرَهُ، تَبَارَكَ اللَّهُ أَحْسَنُ الْخَالِقِينَ",
    transliteration:
      "Allahumma laka sajadtu, wa bika amantu, wa laka aslamtu, sajada wajhi lilladhi khalaqahu wa sawwarahu, wa shaqqa sam'ahu wa basarahu, tabarakallahu ahsanul-khaliqin.",
    translation:
      "O Allah, unto You I prostrate, in You I believe, and to You I surrender. My face has prostrated to the One Who created it and fashioned it, and brought forth its hearing and sight. Blessed be Allah, the Best of creators.",
    benefit:
      "A profound Prophetic supplication of prostration affirming complete submission and praise to the Creator.",
    benefitArabic: "دعاء سجود نبوي جليل يجمع بين الاستسلام لله وحمده على نعمة الخلق والسمع والبصر.",
    repetitionCount: 1,
    sourceReference: "Sahih Muslim 771.",
    sourceReferenceArabic: "صحيح مسلم ٧٧١.",
    preferredTiming: "While prostrating (sujud).",
    authenticityNote: "Sahih Muslim.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/muslim%3A771",
  },
  {
    id: "in-prayer-sujud-complete-forgiveness",
    category: "in_prayer",
    orderIndex: 12,
    arabicText:
      "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلَانِيَتَهُ وَسِرَّهُ",
    transliteration:
      "Allahummaghfir li dhanbi kullahu, diqqahu wa jillahu, wa awwalahu wa akhirahu, wa 'alaniyatahu wa sirrahu.",
    translation: "O Allah, forgive all my sins: the small and great, the first and last, the public and the secret.",
    benefit: "A comprehensive Prophetic plea for forgiveness in prostration.",
    benefitArabic: "دعاء نبوي جامع بطلب المغفرة في السجود.",
    repetitionCount: 1,
    sourceReference: "Sahih Muslim 483.",
    sourceReferenceArabic: "صحيح مسلم ٤٨٣.",
    preferredTiming: "An alternative supplication while prostrating (sujud).",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/muslim/4/246",
  },
  {
    id: "in-prayer-sujud-refuge",
    category: "in_prayer",
    orderIndex: 13,
    arabicText:
      "اللَّهُمَّ أَعُوذُ بِرِضَاكَ مِنْ سَخَطِكَ، وَبِمُعَافَاتِكَ مِنْ عُقُوبَتِكَ، وَأَعُوذُ بِكَ مِنْكَ، لَا أُحْصِي ثَنَاءً عَلَيْكَ، أَنْتَ كَمَا أَثْنَيْتَ عَلَى نَفْسِكَ",
    transliteration:
      "Allahumma a'udhu biridaka min sakhatika, wa bimu'afatika min 'uqubatika, wa a'udhu bika minka, la uhsi thana'an 'alayka, anta kama athnayta 'ala nafsik.",
    translation:
      "O Allah, I seek refuge in Your pleasure from Your anger, in Your pardon from Your punishment, and in You from You. I cannot fully praise You; You are as You have praised Yourself.",
    benefit: "A Prophetic supplication reported while he was in prostration during the night prayer.",
    benefitArabic: "دعاء نبوي ورد أنه قاله في السجود من صلاة الليل.",
    repetitionCount: 1,
    sourceReference: "Sahih Muslim 486.",
    sourceReferenceArabic: "صحيح مسلم ٤٨٦.",
    preferredTiming: "An alternative supplication while prostrating (sujud), especially in night prayer.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/muslim%3A486",
  },
  {
    id: "in-prayer-sujud-tilawah",
    category: "in_prayer",
    orderIndex: 14,
    arabicText:
      "سَجَدَ وَجْهِي لِلَّذِي خَلَقَهُ، وَشَقَّ سَمْعَهُ وَبَصَرَهُ، بِحَوْلِهِ وَقُوَّتِهِ، فَتَبَارَكَ اللَّهُ أَحْسَنُ الْخَالِقِينَ",
    transliteration:
      "Sajada wajhi lilladhi khalaqahu, wa shaqqa sam'ahu wa basarahu, bi-hawlihi wa quwwatih, fa-tabarakallahu ahsanul-khaliqin.",
    translation:
      "My face has prostrated to the One Who created it and brought forth its hearing and sight by His might and power. Blessed be Allah, the Best of creators.",
    benefit: "Authentic supplication when performing the prostration of Quran recitation (Sujud at-Tilawah).",
    benefitArabic: "دعاء ثابت عند سجود التلاوة في الصلاة أو خارجها.",
    repetitionCount: 1,
    sourceReference: "Sunan Abi Dawud 1414; Jami' at-Tirmidhi 580.",
    sourceReferenceArabic: "سنن أبي داود ١٤١٤؛ وجامع الترمذي ٥٨٠.",
    preferredTiming: "During the prostration of recitation (sujud at-tilawah).",
    authenticityNote: "Sahih (Abu Dawud & At-Tirmidhi).",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/abudawud%3A1414",
  },
  {
    id: "in-prayer-between-prostrations",
    category: "in_prayer",
    orderIndex: 15,
    arabicText: "اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي وَعَافِنِي وَاهْدِنِي وَارْزُقْنِي",
    transliteration: "Allahummaghfir li warhamni wa 'afini wahdini warzuqni.",
    translation: "O Allah, forgive me, have mercy on me, grant me well-being, guide me, and provide for me.",
    benefit: reference,
    benefitArabic: referenceArabic,
    repetitionCount: 1,
    sourceReference: "Sunan Abi Dawud 850 (Hasan, al-Albani).",
    sourceReferenceArabic: "سنن أبي داود ٨٥٠ (حسن، الألباني).",
    preferredTiming: "While sitting between the two prostrations.",
    authenticityNote: "Hasan according to Al-Albani.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/abudawud/2/460",
  },
  {
    id: "in-prayer-between-prostrations-brief",
    category: "in_prayer",
    orderIndex: 16,
    arabicText: "رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي",
    transliteration: "Rabbighfir li, Rabbighfir li.",
    translation: "My Lord, forgive me. My Lord, forgive me.",
    benefit: "A concise authentic alternative reported in the Prophet’s night prayer.",
    benefitArabic: "صيغة صحيحة موجزة وردت في صلاة النبي ﷺ بالليل.",
    repetitionCount: 1,
    sourceReference: "Sunan Abi Dawud 874 (Sahih, al-Albani).",
    sourceReferenceArabic: "سنن أبي داود ٨٧٤ (صحيح، الألباني).",
    preferredTiming: "While sitting between the two prostrations.",
    authenticityNote: "Sahih according to Al-Albani.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/abudawud/2/484",
  },
  {
    id: "in-prayer-tashahhud",
    category: "in_prayer",
    orderIndex: 17,
    arabicText:
      "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    transliteration:
      "At-tahiyyatu lillahi was-salawatu wat-tayyibat. As-salamu 'alayka ayyuhan-nabiyyu wa rahmatullahi wa barakatuh. As-salamu 'alayna wa 'ala 'ibadillahis-salihin. Ash-hadu an la ilaha illallah wa ash-hadu anna Muhammadan 'abduhu wa rasuluh.",
    translation:
      "All greetings, prayers, and pure words are for Allah. Peace be upon you, O Prophet, and Allah's mercy and blessings. Peace be upon us and Allah's righteous servants. I testify that none is worthy of worship except Allah and that Muhammad is His servant and Messenger.",
    benefit: "The tashahhud wording taught by the Prophet ﷺ in the prayer.",
    benefitArabic: "من صيغة التشهد التي علّمها النبي ﷺ في الصلاة.",
    repetitionCount: 1,
    sourceReference: "Sahih al-Bukhari 831.",
    sourceReferenceArabic: "صحيح البخاري ٨٣١.",
    preferredTiming: "During the sitting for tashahhud.",
    attributionType: "taught_by_prophet",
    sourceUrl: "https://sunnah.com/bukhari/10/225",
  },
  {
    id: "in-prayer-ibrahimiyyah",
    category: "in_prayer",
    orderIndex: 18,
    arabicText:
      "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
    transliteration:
      "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammadin kama sallayta 'ala ali Ibrahima innaka Hamidun Majid. Allahumma barik 'ala Muhammadin wa 'ala ali Muhammadin kama barakta 'ala ali Ibrahima innaka Hamidun Majid.",
    translation:
      "O Allah, send prayers upon Muhammad and the family of Muhammad as You sent prayers upon the family of Ibrahim; You are Praiseworthy, Glorious. O Allah, bless Muhammad and the family of Muhammad as You blessed the family of Ibrahim; You are Praiseworthy, Glorious.",
    benefit: "A Prophetic formula for sending prayers and blessings upon the Prophet ﷺ.",
    benefitArabic: "صيغة نبوية للصلاة والبركة على النبي ﷺ.",
    repetitionCount: 1,
    sourceReference: "Sahih al-Bukhari 6357.",
    sourceReferenceArabic: "صحيح البخاري ٦٣٥٧.",
    preferredTiming: "After the final tashahhud, before supplication and salam.",
    attributionType: "taught_by_prophet",
    sourceUrl: "https://sunnah.com/bukhari/80/54-55",
  },
  {
    id: "in-prayer-before-salam-refuge",
    category: "in_prayer",
    orderIndex: 19,
    arabicText:
      "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ جَهَنَّمَ، وَمِنْ عَذَابِ الْقَبْرِ، وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ، وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ",
    transliteration:
      "Allahumma inni a'udhu bika min 'adhabi Jahannam, wa min 'adhabil-qabr, wa min fitnatil-mahya wal-mamat, wa min sharri fitnatil-Masihid-Dajjal.",
    translation:
      "O Allah, I seek refuge in You from the punishment of Hell, the punishment of the grave, the trials of life and death, and the evil trial of the False Messiah.",
    benefit: "An explicit Prophetic instruction after tashahhud and before salam.",
    benefitArabic: "أمر نبوي صريح بالاستعاذة به بعد التشهد وقبل السلام.",
    repetitionCount: 1,
    sourceReference: "Sahih Muslim 588a.",
    sourceReferenceArabic: "صحيح مسلم ٥٨٨أ.",
    preferredTiming: "After the final tashahhud, before salam.",
    attributionType: "taught_by_prophet",
    sourceUrl: "https://sunnah.com/muslim%3A588a",
  },
  {
    id: "in-prayer-before-salam-self-forgiveness",
    category: "in_prayer",
    orderIndex: 20,
    arabicText:
      "اللَّهُمَّ إِنِّي ظَلَمْتُ نَفْسِي ظُلْمًا كَثِيرًا، وَلَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ، فَاغْفِرْ لِي مَغْفِرَةً مِنْ عِنْدِكَ، وَارْحَمْنِي، إِنَّكَ أَنْتَ الْغَفُورُ الرَّحِيمُ",
    transliteration:
      "Allahumma inni zalamtu nafsi zulman kathiran, wa la yaghfirudh-dhunuba illa anta, faghfir li maghfiratan min 'indika, warhamni, innaka antal-Ghafurur-Rahim.",
    translation:
      "O Allah, I have greatly wronged myself, and none forgives sins but You. Grant me forgiveness from You and have mercy on me; You are the Most Forgiving, Most Merciful.",
    benefit: "A supplication the Prophet ﷺ taught Abu Bakr to say within the prayer.",
    benefitArabic: "دعاء علّمه النبي ﷺ لأبي بكر رضي الله عنه ليدعو به في صلاته.",
    repetitionCount: 1,
    sourceReference: "Sahih al-Bukhari 834; also 6326.",
    sourceReferenceArabic: "صحيح البخاري ٨٣٤؛ وأيضًا ٦٣٢٦.",
    preferredTiming: "After the final tashahhud, before salam.",
    attributionType: "taught_by_prophet",
    sourceUrl: "https://sunnah.com/bukhari%3A834",
  },
  {
    id: "in-prayer-before-salam-comprehensive",
    category: "in_prayer",
    orderIndex: 21,
    arabicText:
      "اللَّهُمَّ بِعِلْمِكَ الْغَيْبَ، وَقُدْرَتِكَ عَلَى الْخَلْقِ، أَحْيِنِي مَا عَلِمْتَ الْحَيَاةَ خَيْرًا لِي، وَتَوَفَّنِي إِذَا عَلِمْتَ الْوَفَاةَ خَيْرًا لِي، اللَّهُمَّ وَأَسْأَلُكَ خَشْيَتَكَ فِي الْغَيْبِ وَالشَّهَادَةِ، وَأَسْأَلُكَ كَلِمَةَ الْحَقِّ فِي الرِّضَا وَالْغَضَبِ، وَأَسْأَلُكَ الْقَصْدَ فِي الْفَقْرِ وَالْغِنَى، وَأَسْأَلُكَ نَعِيمًا لَا يَنْفَدُ، وَأَسْأَلُكَ قُرَّةَ عَيْنٍ لَا تَنْقَطِعُ، وَأَسْأَلُكَ الرِّضَا بَعْدَ الْقَضَاءِ، وَأَسْأَلُكَ بَرْدَ الْعَيْشِ بَعْدَ الْمَوْتِ، وَأَسْأَلُكَ لَذَّةَ النَّظَرِ إِلَى وَجْهِكَ، وَالشَّوْقَ إِلَى لِقَائِكَ، فِي غَيْرِ ضَرَّاءَ مُضِرَّةٍ، وَلَا فِتْنَةٍ مُضِلَّةٍ، اللَّهُمَّ زَيِّنَّا بِزِينَةِ الْإِيمَانِ، وَاجْعَلْنَا هُدَاةً مُهْتَدِينَ",
    transliteration:
      "Allahumma bi-'ilmikal-ghayba, wa qudratika 'alal-khalqi, ahyini ma 'alimtal-hayata khayran li, wa tawaffani idha 'alimtal-wafata khayran li. Allahumma wa as'aluka khashyataka fil-ghaybi wash-shahadah, wa as'aluka kalimatal-haqqi fir-rida wal-ghadab, wa as'alukal-qasda fil-faqri wal-ghina, wa as'aluka na'iman la yanfad, wa as'aluka qurrata 'aynin la tanqati', wa as'alukar-rida ba'dal-qada', wa as'aluka bardal-'ayshi ba'dal-mawt, wa as'aluka ladhdhatan-nazari ila wajhik, wash-shawqa ila liqa'ik, fi ghayri darra'a mudirrah, wa la fitnatin mudillah. Allahumma zayyinna bi-zinatil-iman, waj'alna hudatan muhtadin.",
    translation:
      "O Allah, by Your knowledge of the unseen and Your power over creation, grant me life as long as You know life is good for me, and cause me to die when death is good for me. I ask You for fear of You in secret and in the open, for the word of truth in pleasure and anger, for moderation in poverty and wealth, for bliss that never ends, for the coolness of eyes that never ceases, for contentment after decree, for the coolness of life after death, for the delight of gazing upon Your Face, and for the longing to meet You, without harmful adversity or misguiding trial. O Allah, adorn us with the beauty of faith and make us guides who are rightly guided.",
    benefit:
      "A profoundly comprehensive Prophetic supplication narrated by 'Ammar ibn Yasir, recited before the final salam.",
    benefitArabic: "دعاء جامع عظيم أثره عمار بن ياسر عن النبي ﷺ قبل السلام من الصلاة.",
    repetitionCount: 1,
    sourceReference: "Sunan an-Nasa'i 1305; Musnad Ahmad 4/264.",
    sourceReferenceArabic: "سنن النسائي ١٣٠٥؛ ومسند أحمد ٤/٢٦٤.",
    preferredTiming: "After the final tashahhud, before salam.",
    authenticityNote: "Sahih (al-Albani).",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/nasai%3A1305",
  },
  {
    id: "in-prayer-before-salam-forgiveness",
    category: "in_prayer",
    orderIndex: 22,
    arabicText:
      "اللَّهُمَّ اغْفِرْ لِي مَا قَدَّمْتُ وَمَا أَخَّرْتُ، وَمَا أَسْرَرْتُ وَمَا أَعْلَنْتُ، وَمَا أَسْرَفْتُ، وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي، أَنْتَ الْمُقَدِّمُ وَأَنْتَ الْمُؤَخِّرُ، لَا إِلَهَ إِلَّا أَنْتَ",
    transliteration:
      "Allahummaghfir li ma qaddamtu wa ma akhkhartu, wa ma asrartu wa ma a'lantu, wa ma asraftu, wa ma Anta a'lamu bihi minni, Antal-Muqaddimu wa Antal-Mu'akhkhiru, la ilaha illa Ant.",
    translation:
      "O Allah, forgive me what I have sent forward and what I have held back, what I have concealed and what I have made public, where I have exceeded, and what You know better than I. You are the Advancer and You are the Delayer; none is worthy of worship except You.",
    benefit: "An established Prophetic supplication recited at the conclusion of prayer before salam.",
    benefitArabic: "دعاء استغفار نبوي ثابت كان يقوله ﷺ آخر ما يقول بين التشهد والتسليم.",
    repetitionCount: 1,
    sourceReference: "Sahih Muslim 771.",
    sourceReferenceArabic: "صحيح مسلم ٧٧١.",
    preferredTiming: "After the final tashahhud, before salam.",
    authenticityNote: "Sahih Muslim.",
    attributionType: "said_by_prophet",
    sourceUrl: "https://sunnah.com/muslim%3A771",
  },
  {
    id: "in-prayer-witr-qunut",
    category: "in_prayer",
    orderIndex: 23,
    arabicText:
      "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ، وَقِنِي شَرَّ مَا قَضَيْتَ، إِنَّكَ تَقْضِي وَلَا يُقْضَى عَلَيْكَ، وَإِنَّهُ لَا يَذِلُّ مَنْ وَالَيْتَ، وَلَا يَعِزُّ مَنْ عَادَيْتَ، تَبَارَكْتَ رَبَّنَا وَتَعَالَيْتَ",
    transliteration:
      "Allahumma ihdini fiman hadayt, wa 'afini fiman 'afayt, wa tawallani fiman tawallayt, wa barik li fima a'tayt, wa qini sharra ma qadayt, innaka taqdi wa la yuqda 'alayk, wa innahu la yadhillu man walayt, wa la ya'izzu man 'adayt, tabarakta Rabbana wa ta'alayt.",
    translation:
      "O Allah, guide me among those You have guided, grant me well-being among those You have granted well-being, take me into Your care among those You have taken into Your care, bless what You have given me, and protect me from the evil of what You have decreed. You decree and none decrees over You. Whoever You befriend is not humiliated, and whoever You oppose is not honored. Blessed and Exalted are You, our Lord.",
    benefit: "The Qunut supplication the Prophet ﷺ taught al-Hasan ibn Ali for Witr.",
    benefitArabic: "دعاء القنوت الذي علّمه النبي ﷺ للحسن بن علي رضي الله عنهما في الوتر.",
    repetitionCount: 1,
    sourceReference: "Sunan Abi Dawud 1425 (Sahih, al-Albani).",
    sourceReferenceArabic: "سنن أبي داود ١٤٢٥ (صحيح، الألباني).",
    preferredTiming: "During Qunut in the Witr prayer.",
    authenticityNote: "Sahih according to Al-Albani.",
    attributionType: "taught_by_prophet",
    sourceUrl: "https://sunnah.com/abudawud%3A1425",
  },
];

for (const zikr of IN_PRAYER_AZKAR) {
  if (!zikr.isCollectionIntroduction && !zikr.hadithText) {
    zikr.hadithText = zikr.arabicText;
    zikr.hadithTextEnglish = zikr.translation;
  }
}
