import { matchesSearch, normalizeSearchText } from "./searchNormalization";

export interface PrayerLocationPreset {
  id: string;
  nameEnglish: string;
  nameArabic: string;
  countryEnglish: string;
  countryArabic: string;
  latitude: number;
  longitude: number;
  timeZone: string;
  aliases?: readonly string[];
}

export const PRAYER_LOCATION_PRESETS: readonly PrayerLocationPreset[] = [
  {
    id: "makkah",
    nameEnglish: "Makkah",
    nameArabic: "مكة المكرمة",
    countryEnglish: "Saudi Arabia",
    countryArabic: "السعودية",
    latitude: 21.4225,
    longitude: 39.8262,
    timeZone: "Asia/Riyadh",
    aliases: ["Mecca"],
  },
  {
    id: "madinah",
    nameEnglish: "Madinah",
    nameArabic: "المدينة المنورة",
    countryEnglish: "Saudi Arabia",
    countryArabic: "السعودية",
    latitude: 24.4672,
    longitude: 39.6111,
    timeZone: "Asia/Riyadh",
    aliases: ["Medina"],
  },
  {
    id: "cairo",
    nameEnglish: "Cairo",
    nameArabic: "القاهرة",
    countryEnglish: "Egypt",
    countryArabic: "مصر",
    latitude: 30.0444,
    longitude: 31.2357,
    timeZone: "Africa/Cairo",
  },
  {
    id: "alexandria",
    nameEnglish: "Alexandria",
    nameArabic: "الإسكندرية",
    countryEnglish: "Egypt",
    countryArabic: "مصر",
    latitude: 31.2001,
    longitude: 29.9187,
    timeZone: "Africa/Cairo",
  },
  {
    id: "riyadh",
    nameEnglish: "Riyadh",
    nameArabic: "الرياض",
    countryEnglish: "Saudi Arabia",
    countryArabic: "السعودية",
    latitude: 24.7136,
    longitude: 46.6753,
    timeZone: "Asia/Riyadh",
  },
  {
    id: "jeddah",
    nameEnglish: "Jeddah",
    nameArabic: "جدة",
    countryEnglish: "Saudi Arabia",
    countryArabic: "السعودية",
    latitude: 21.5433,
    longitude: 39.1728,
    timeZone: "Asia/Riyadh",
  },
  {
    id: "dubai",
    nameEnglish: "Dubai",
    nameArabic: "دبي",
    countryEnglish: "United Arab Emirates",
    countryArabic: "الإمارات",
    latitude: 25.2048,
    longitude: 55.2708,
    timeZone: "Asia/Dubai",
    aliases: ["UAE"],
  },
  {
    id: "abu-dhabi",
    nameEnglish: "Abu Dhabi",
    nameArabic: "أبوظبي",
    countryEnglish: "United Arab Emirates",
    countryArabic: "الإمارات",
    latitude: 24.4539,
    longitude: 54.3773,
    timeZone: "Asia/Dubai",
    aliases: ["UAE"],
  },
  {
    id: "doha",
    nameEnglish: "Doha",
    nameArabic: "الدوحة",
    countryEnglish: "Qatar",
    countryArabic: "قطر",
    latitude: 25.2854,
    longitude: 51.531,
    timeZone: "Asia/Qatar",
  },
  {
    id: "kuwait-city",
    nameEnglish: "Kuwait City",
    nameArabic: "مدينة الكويت",
    countryEnglish: "Kuwait",
    countryArabic: "الكويت",
    latitude: 29.3759,
    longitude: 47.9774,
    timeZone: "Asia/Kuwait",
  },
  {
    id: "manama",
    nameEnglish: "Manama",
    nameArabic: "المنامة",
    countryEnglish: "Bahrain",
    countryArabic: "البحرين",
    latitude: 26.2235,
    longitude: 50.5876,
    timeZone: "Asia/Bahrain",
  },
  {
    id: "muscat",
    nameEnglish: "Muscat",
    nameArabic: "مسقط",
    countryEnglish: "Oman",
    countryArabic: "عُمان",
    latitude: 23.588,
    longitude: 58.3829,
    timeZone: "Asia/Muscat",
  },
  {
    id: "amman",
    nameEnglish: "Amman",
    nameArabic: "عمّان",
    countryEnglish: "Jordan",
    countryArabic: "الأردن",
    latitude: 31.9539,
    longitude: 35.9106,
    timeZone: "Asia/Amman",
  },
  {
    id: "jerusalem",
    nameEnglish: "Jerusalem",
    nameArabic: "القدس",
    countryEnglish: "Palestine",
    countryArabic: "فلسطين",
    latitude: 31.7683,
    longitude: 35.2137,
    timeZone: "Asia/Jerusalem",
    aliases: ["Al-Quds"],
  },
  {
    id: "beirut",
    nameEnglish: "Beirut",
    nameArabic: "بيروت",
    countryEnglish: "Lebanon",
    countryArabic: "لبنان",
    latitude: 33.8938,
    longitude: 35.5018,
    timeZone: "Asia/Beirut",
  },
  {
    id: "damascus",
    nameEnglish: "Damascus",
    nameArabic: "دمشق",
    countryEnglish: "Syria",
    countryArabic: "سوريا",
    latitude: 33.5138,
    longitude: 36.2765,
    timeZone: "Asia/Damascus",
  },
  {
    id: "baghdad",
    nameEnglish: "Baghdad",
    nameArabic: "بغداد",
    countryEnglish: "Iraq",
    countryArabic: "العراق",
    latitude: 33.3152,
    longitude: 44.3661,
    timeZone: "Asia/Baghdad",
  },
  {
    id: "sanaa",
    nameEnglish: "Sana'a",
    nameArabic: "صنعاء",
    countryEnglish: "Yemen",
    countryArabic: "اليمن",
    latitude: 15.3694,
    longitude: 44.191,
    timeZone: "Asia/Aden",
    aliases: ["Sanaa"],
  },
  {
    id: "khartoum",
    nameEnglish: "Khartoum",
    nameArabic: "الخرطوم",
    countryEnglish: "Sudan",
    countryArabic: "السودان",
    latitude: 15.5007,
    longitude: 32.5599,
    timeZone: "Africa/Khartoum",
  },
  {
    id: "casablanca",
    nameEnglish: "Casablanca",
    nameArabic: "الدار البيضاء",
    countryEnglish: "Morocco",
    countryArabic: "المغرب",
    latitude: 33.5731,
    longitude: -7.5898,
    timeZone: "Africa/Casablanca",
  },
  {
    id: "algiers",
    nameEnglish: "Algiers",
    nameArabic: "الجزائر",
    countryEnglish: "Algeria",
    countryArabic: "الجزائر",
    latitude: 36.7538,
    longitude: 3.0588,
    timeZone: "Africa/Algiers",
  },
  {
    id: "tunis",
    nameEnglish: "Tunis",
    nameArabic: "تونس",
    countryEnglish: "Tunisia",
    countryArabic: "تونس",
    latitude: 36.8065,
    longitude: 10.1815,
    timeZone: "Africa/Tunis",
  },
  {
    id: "tripoli",
    nameEnglish: "Tripoli",
    nameArabic: "طرابلس",
    countryEnglish: "Libya",
    countryArabic: "ليبيا",
    latitude: 32.8872,
    longitude: 13.1913,
    timeZone: "Africa/Tripoli",
  },
  {
    id: "mogadishu",
    nameEnglish: "Mogadishu",
    nameArabic: "مقديشو",
    countryEnglish: "Somalia",
    countryArabic: "الصومال",
    latitude: 2.0469,
    longitude: 45.3182,
    timeZone: "Africa/Mogadishu",
  },
  {
    id: "istanbul",
    nameEnglish: "Istanbul",
    nameArabic: "إسطنبول",
    countryEnglish: "Türkiye",
    countryArabic: "تركيا",
    latitude: 41.0082,
    longitude: 28.9784,
    timeZone: "Europe/Istanbul",
    aliases: ["Turkey"],
  },
  {
    id: "london",
    nameEnglish: "London",
    nameArabic: "لندن",
    countryEnglish: "United Kingdom",
    countryArabic: "المملكة المتحدة",
    latitude: 51.5074,
    longitude: -0.1278,
    timeZone: "Europe/London",
    aliases: ["UK", "Britain"],
  },
  {
    id: "paris",
    nameEnglish: "Paris",
    nameArabic: "باريس",
    countryEnglish: "France",
    countryArabic: "فرنسا",
    latitude: 48.8566,
    longitude: 2.3522,
    timeZone: "Europe/Paris",
  },
  {
    id: "berlin",
    nameEnglish: "Berlin",
    nameArabic: "برلين",
    countryEnglish: "Germany",
    countryArabic: "ألمانيا",
    latitude: 52.52,
    longitude: 13.405,
    timeZone: "Europe/Berlin",
  },
  {
    id: "madrid",
    nameEnglish: "Madrid",
    nameArabic: "مدريد",
    countryEnglish: "Spain",
    countryArabic: "إسبانيا",
    latitude: 40.4168,
    longitude: -3.7038,
    timeZone: "Europe/Madrid",
  },
  {
    id: "rome",
    nameEnglish: "Rome",
    nameArabic: "روما",
    countryEnglish: "Italy",
    countryArabic: "إيطاليا",
    latitude: 41.9028,
    longitude: 12.4964,
    timeZone: "Europe/Rome",
  },
  {
    id: "moscow",
    nameEnglish: "Moscow",
    nameArabic: "موسكو",
    countryEnglish: "Russia",
    countryArabic: "روسيا",
    latitude: 55.7558,
    longitude: 37.6173,
    timeZone: "Europe/Moscow",
  },
  {
    id: "new-york",
    nameEnglish: "New York",
    nameArabic: "نيويورك",
    countryEnglish: "United States",
    countryArabic: "الولايات المتحدة",
    latitude: 40.7128,
    longitude: -74.006,
    timeZone: "America/New_York",
    aliases: ["NYC", "USA"],
  },
  {
    id: "chicago",
    nameEnglish: "Chicago",
    nameArabic: "شيكاغو",
    countryEnglish: "United States",
    countryArabic: "الولايات المتحدة",
    latitude: 41.8781,
    longitude: -87.6298,
    timeZone: "America/Chicago",
    aliases: ["USA"],
  },
  {
    id: "los-angeles",
    nameEnglish: "Los Angeles",
    nameArabic: "لوس أنجلوس",
    countryEnglish: "United States",
    countryArabic: "الولايات المتحدة",
    latitude: 34.0522,
    longitude: -118.2437,
    timeZone: "America/Los_Angeles",
    aliases: ["LA", "USA"],
  },
  {
    id: "toronto",
    nameEnglish: "Toronto",
    nameArabic: "تورونتو",
    countryEnglish: "Canada",
    countryArabic: "كندا",
    latitude: 43.6532,
    longitude: -79.3832,
    timeZone: "America/Toronto",
  },
  {
    id: "sao-paulo",
    nameEnglish: "São Paulo",
    nameArabic: "ساو باولو",
    countryEnglish: "Brazil",
    countryArabic: "البرازيل",
    latitude: -23.5505,
    longitude: -46.6333,
    timeZone: "America/Sao_Paulo",
    aliases: ["Sao Paulo"],
  },
  {
    id: "karachi",
    nameEnglish: "Karachi",
    nameArabic: "كراتشي",
    countryEnglish: "Pakistan",
    countryArabic: "باكستان",
    latitude: 24.8607,
    longitude: 67.0011,
    timeZone: "Asia/Karachi",
  },
  {
    id: "islamabad",
    nameEnglish: "Islamabad",
    nameArabic: "إسلام آباد",
    countryEnglish: "Pakistan",
    countryArabic: "باكستان",
    latitude: 33.6844,
    longitude: 73.0479,
    timeZone: "Asia/Karachi",
  },
  {
    id: "dhaka",
    nameEnglish: "Dhaka",
    nameArabic: "دكا",
    countryEnglish: "Bangladesh",
    countryArabic: "بنغلاديش",
    latitude: 23.8103,
    longitude: 90.4125,
    timeZone: "Asia/Dhaka",
  },
  {
    id: "jakarta",
    nameEnglish: "Jakarta",
    nameArabic: "جاكرتا",
    countryEnglish: "Indonesia",
    countryArabic: "إندونيسيا",
    latitude: -6.2088,
    longitude: 106.8456,
    timeZone: "Asia/Jakarta",
  },
  {
    id: "kuala-lumpur",
    nameEnglish: "Kuala Lumpur",
    nameArabic: "كوالالمبور",
    countryEnglish: "Malaysia",
    countryArabic: "ماليزيا",
    latitude: 3.139,
    longitude: 101.6869,
    timeZone: "Asia/Kuala_Lumpur",
  },
  {
    id: "singapore",
    nameEnglish: "Singapore",
    nameArabic: "سنغافورة",
    countryEnglish: "Singapore",
    countryArabic: "سنغافورة",
    latitude: 1.3521,
    longitude: 103.8198,
    timeZone: "Asia/Singapore",
  },
  {
    id: "delhi",
    nameEnglish: "Delhi",
    nameArabic: "دلهي",
    countryEnglish: "India",
    countryArabic: "الهند",
    latitude: 28.6139,
    longitude: 77.209,
    timeZone: "Asia/Kolkata",
    aliases: ["New Delhi"],
  },
  {
    id: "sydney",
    nameEnglish: "Sydney",
    nameArabic: "سيدني",
    countryEnglish: "Australia",
    countryArabic: "أستراليا",
    latitude: -33.8688,
    longitude: 151.2093,
    timeZone: "Australia/Sydney",
  },
] as const;

export const POPULAR_PRAYER_LOCATION_IDS = ["makkah", "madinah", "cairo", "riyadh", "dubai", "london"] as const;

export function searchPrayerLocations(query: string, limit = 8): PrayerLocationPreset[] {
  const normalizedQuery = normalizeSearchText(query);
  const source = normalizedQuery
    ? PRAYER_LOCATION_PRESETS.filter((location) =>
        [
          location.nameEnglish,
          location.nameArabic,
          location.countryEnglish,
          location.countryArabic,
          location.timeZone,
          ...(location.aliases ?? []),
        ].some((value) => matchesSearch(value, normalizedQuery)),
      )
    : POPULAR_PRAYER_LOCATION_IDS.map((id) => PRAYER_LOCATION_PRESETS.find((location) => location.id === id)!).filter(
        Boolean,
      );

  return source.slice(0, Math.max(0, limit));
}
