/**
 * Mushaf page data and QCF v2 page fonts.
 *
 * Reference (DEC-089): the King Fahd Complex Madani Mushaf, 15 lines per page,
 * 604 pages, set in the official QCF v2 per-page glyph fonts.
 *
 * Both halves of that reference now ship with the app. `public/data/mushaf` is
 * generated by `scripts/prepare-mushaf-pages.mjs` and carries the reference
 * line numbers *and* the `code_v2` glyph for every word, so turning a page no
 * longer costs a call to api.quran.com — it used to cost one request plus an
 * 1800 ms abort timer before the page could settle. Only the page font is still
 * remote, and it is kept in Cache Storage after its first load so that repeat
 * and offline reads are instant.
 */

export type MushafWordTuple = [
  position: number,
  lineNumber: number,
  isEnd: number,
  semanticText: string,
  qcfCode?: string,
];

export interface MushafVerseData {
  k: string;
  w: MushafWordTuple[];
}

const QCF_FONT_ROOT = "https://verses.quran.foundation/fonts/quran/hafs/v2/woff2";
export const FONT_CACHE_NAME = "azkar-qcf-fonts-v1";
export const MUSHAF_CACHE_NAME = "azkar-mushaf-v3";
const MAX_MEMORY_PAGES = 128;

const pageCache = new Map<number, MushafVerseData[]>();
const pendingPages = new Map<number, Promise<MushafVerseData[]>>();
const readyFonts = new Set<number>();
const pendingFonts = new Map<number, Promise<boolean>>();

export function getMushafPageUrl(page: number) {
  const base = import.meta.env.BASE_URL || "/";
  return `${base.endsWith("/") ? base : `${base}/`}data/mushaf/${page}.json?v=3`;
}

export function getQcfFontUrl(page: number) {
  return `${QCF_FONT_ROOT}/p${page}.woff2`;
}

export function getQcfFontFamily(page: number) {
  return `qcf-v2-page-${page}`;
}

/** Rejects anything that is not the shipped page shape, so a truncated or
 *  mis-served file falls back rather than rendering a broken page. */
export function parseMushafPage(value: unknown): MushafVerseData[] | null {
  if (!Array.isArray(value) || value.length === 0) return null;

  const parsed: MushafVerseData[] = [];
  for (const verse of value) {
    if (!verse || typeof verse !== "object") return null;
    const { k, w } = verse as { k?: unknown; w?: unknown };
    if (typeof k !== "string" || !Array.isArray(w) || w.length === 0) return null;

    const words: MushafWordTuple[] = [];
    for (const word of w) {
      if (!Array.isArray(word)) return null;
      const [position, lineNumber, isEnd, text, qcfCode] = word as unknown[];
      if (
        typeof position !== "number" ||
        typeof lineNumber !== "number" ||
        lineNumber < 1 ||
        lineNumber > 15 ||
        typeof isEnd !== "number" ||
        typeof text !== "string"
      ) {
        return null;
      }
      words.push(
        typeof qcfCode === "string"
          ? [position, lineNumber, isEnd, text, qcfCode]
          : [position, lineNumber, isEnd, text],
      );
    }
    parsed.push({ k, w: words });
  }

  return parsed;
}

/** A page renders in QCF only when every one of its words carries a glyph. A
 *  half-glyph page would mix two typefaces on the same line. */
export function pageHasQcfGlyphs(page: readonly MushafVerseData[]): boolean {
  return page.every((verse) => verse.w.every((word) => typeof word[4] === "string" && word[4].length > 0));
}

export function getCachedMushafPage(page: number): MushafVerseData[] | undefined {
  return pageCache.get(page);
}

export function isQcfFontReady(page: number): boolean {
  return readyFonts.has(page);
}

function rememberPage(page: number, data: MushafVerseData[]) {
  pageCache.delete(page);
  pageCache.set(page, data);
  while (pageCache.size > MAX_MEMORY_PAGES) {
    const oldest = pageCache.keys().next().value;
    if (oldest === undefined) break;
    pageCache.delete(oldest);
  }
}

/**
 * Deliberately unabortable. The same promise is shared by the reader and by the
 * neighbour prefetch, so letting one consumer's AbortSignal cancel it would let
 * a fast double tap cancel the page the reader is about to show.
 */
export function loadMushafPage(page: number): Promise<MushafVerseData[]> {
  const cached = pageCache.get(page);
  if (cached) return Promise.resolve(cached);

  const pending = pendingPages.get(page);
  if (pending) return pending;

  const request = (async () => {
    const url = getMushafPageUrl(page);
    let response: Response | undefined;

    if (typeof caches !== "undefined") {
      try {
        const cache = await caches.open(MUSHAF_CACHE_NAME);
        response = await cache.match(url);
      } catch {
        /* Fall back to fetch */
      }
    }

    if (!response) {
      response = await fetch(url);
      if (response.ok && typeof caches !== "undefined") {
        try {
          const cache = await caches.open(MUSHAF_CACHE_NAME);
          await cache.put(url, response.clone());
        } catch {
          /* ignore cache store errors */
        }
      }
    }

    if (!response.ok) throw new Error(`Mushaf page ${page} request failed with HTTP ${response.status}`);
    const parsed = parseMushafPage(await response.json());
    if (!parsed) throw new Error(`Mushaf page ${page} did not match the expected shape`);
    rememberPage(page, parsed);
    return parsed;
  })().finally(() => {
    pendingPages.delete(page);
  });

  pendingPages.set(page, request);
  return request;
}

export function canonicalAyahText(pages: ReadonlyArray<ReadonlyArray<MushafVerseData>>, verseKey: string) {
  const words = new Map<number, string>();
  for (const page of pages) {
    for (const verse of page) {
      if (verse.k !== verseKey) continue;
      for (const [position, , isEnd, text] of verse.w) {
        if (!isEnd) words.set(position, text);
      }
    }
  }
  return [...words.entries()]
    .sort(([a], [b]) => a - b)
    .map(([, text]) => text)
    .join(" ");
}

/**
 * Loads the complete reviewed Uthmani ayah, including the rare case where an
 * ayah crosses a page boundary. QCF glyphs are never copied: they are private
 * code points for drawing, while this returns the semantic text shipped beside
 * each word.
 */
export async function loadCanonicalAyahText(verseKey: string, pageNumber: number) {
  const pages = new Map<number, MushafVerseData[]>();
  const current = await loadMushafPage(pageNumber);
  if (!current.some((verse) => verse.k === verseKey)) throw new Error(`Ayah ${verseKey} is not on page ${pageNumber}`);
  pages.set(pageNumber, current);

  let previousPage = pageNumber;
  while (previousPage > 1 && pages.get(previousPage)?.[0]?.k === verseKey) {
    previousPage -= 1;
    const previous = await loadMushafPage(previousPage);
    pages.set(previousPage, previous);
    if (previous.at(-1)?.k !== verseKey) break;
  }

  let nextPage = pageNumber;
  while (nextPage < 604 && pages.get(nextPage)?.at(-1)?.k === verseKey) {
    nextPage += 1;
    const next = await loadMushafPage(nextPage);
    pages.set(nextPage, next);
    if (next[0]?.k !== verseKey) break;
  }

  const text = canonicalAyahText(
    [...pages.entries()].sort(([a], [b]) => a - b).map(([, page]) => page),
    verseKey,
  );
  if (!text) throw new Error(`Ayah ${verseKey} has no semantic text`);
  return text;
}

async function openFontCache(): Promise<Cache | null> {
  if (typeof caches === "undefined") return null;
  try {
    return await caches.open(FONT_CACHE_NAME);
  } catch {
    return null;
  }
}

const injectedStyles = new Set<number>();

export function injectFontFaceRule(page: number) {
  if (typeof document === "undefined" || injectedStyles.has(page)) return;
  injectedStyles.add(page);
  const family = getQcfFontFamily(page);
  const primaryUrl = getQcfFontUrl(page);
  const secondaryUrl = `https://quran.com/fonts/quran/hafs/v2/woff2/p${page}.woff2`;

  const style = document.createElement("style");
  style.setAttribute("data-qcf-page", String(page));
  style.textContent = `
    @font-face {
      font-family: '${family}';
      src: url('${primaryUrl}') format('woff2'),
           url('${secondaryUrl}') format('woff2');
      font-display: swap;
    }
  `;
  document.head.appendChild(style);
}

async function createFontFace(page: number): Promise<FontFace> {
  const family = getQcfFontFamily(page);
  const primaryUrl = getQcfFontUrl(page);
  const secondaryUrl = `https://quran.com/fonts/quran/hafs/v2/woff2/p${page}.woff2`;
  const cache = await openFontCache();

  if (cache) {
    try {
      let response = await cache.match(primaryUrl);
      if (!response) {
        response = await cache.match(secondaryUrl);
      }
      if (!response) {
        try {
          const network = await fetch(primaryUrl);
          if (network.ok) {
            await cache.put(primaryUrl, network.clone());
            response = network;
          }
        } catch {
          const fallbackNet = await fetch(secondaryUrl);
          if (fallbackNet.ok) {
            await cache.put(primaryUrl, fallbackNet.clone());
            response = fallbackNet;
          }
        }
      }
      if (response) return new FontFace(family, await response.arrayBuffer());
    } catch {
      /* Fall through to the plain URL source below. */
    }
  }

  return new FontFace(family, `url(${primaryUrl}), url(${secondaryUrl})`);
}

type FontLoadListener = (page: number) => void;
const fontLoadListeners = new Set<FontLoadListener>();

export function subscribeQcfFontLoaded(listener: FontLoadListener): () => void {
  fontLoadListeners.add(listener);
  return () => {
    fontLoadListeners.delete(listener);
  };
}

export function loadQcfFont(page: number): Promise<boolean> {
  if (page < 1 || page > 604) return Promise.resolve(false);
  injectFontFaceRule(page);

  if (typeof FontFace === "undefined" || typeof document === "undefined" || !document.fonts) {
    readyFonts.add(page);
    return Promise.resolve(true);
  }
  if (readyFonts.has(page)) return Promise.resolve(true);

  const pending = pendingFonts.get(page);
  if (pending) return pending;

  const request = (async () => {
    try {
      const face = await createFontFace(page);
      const loaded = await face.load();
      document.fonts.add(loaded);
      readyFonts.add(page);
      for (const listener of fontLoadListeners) {
        try {
          listener(page);
        } catch {
          /* ignore listener errors */
        }
      }
      return true;
    } catch {
      return false;
    }
  })().finally(() => {
    pendingFonts.delete(page);
  });

  pendingFonts.set(page, request);
  return request;
}

/**
 * Caches this app no longer routes anything to.
 *
 * DEC-089 dropped the two Workbox runtime routes that fed them, and Workbox
 * only tidies up its own precache — so every browser that had visited before
 * that release still carries them, holding page data we now ship and fonts we
 * now store ourselves. Nothing reads them again, so they are pure dead weight
 * in the reader's storage quota.
 */
const RETIRED_CACHES = ["azkar-qcf-page-data-v1", "azkar-qcf-page-fonts-v1", "azkar-mushaf-v1", "azkar-mushaf-v2"];

export async function discardRetiredCaches(): Promise<string[]> {
  if (typeof caches === "undefined") return [];
  const discarded: string[] = [];
  for (const name of RETIRED_CACHES) {
    try {
      if (await caches.delete(name)) discarded.push(name);
    } catch {
      /* A browser that will not let go of a cache is not worth failing over. */
    }
  }
  return discarded;
}

/** Warms a neighbouring page without ever surfacing its failure. */
export function prefetchMushafPage(page: number) {
  if (page < 1 || page > 604) return;
  void loadMushafPage(page).catch(() => undefined);
  void loadQcfFont(page);
}
