// Generated by scripts/generate-relevant-now-verses.mjs from api.alquran.cloud.
// Arabic: Uthmani text; English: public-domain Pickthall translation.
// Do not edit by hand — curation lives in relevantNowLibrary.ts.

export interface RelevantNowVerse {
  id: string;
  reference: string;
  referenceArabic: string;
  surahEnglish: string;
  surahArabic: string;
  arabic: string;
  english: string;
}

export const RELEVANT_NOW_VERSES: readonly RelevantNowVerse[] = [
  {
    id: "Q01",
    reference: "Qur'an 4:103",
    referenceArabic: "القرآن ٤:١٠٣",
    surahEnglish: "An-Nisa",
    surahArabic: "سُورَةُ النِّسَاءِ",
    arabic:
      "فَإِذَا قَضَيْتُمُ ٱلصَّلَوٰةَ فَٱذْكُرُوا۟ ٱللَّهَ قِيَٰمًۭا وَقُعُودًۭا وَعَلَىٰ جُنُوبِكُمْ ۚ فَإِذَا ٱطْمَأْنَنتُمْ فَأَقِيمُوا۟ ٱلصَّلَوٰةَ ۚ إِنَّ ٱلصَّلَوٰةَ كَانَتْ عَلَى ٱلْمُؤْمِنِينَ كِتَٰبًۭا مَّوْقُوتًۭا ﴿١٠٣﴾",
    english:
      "When ye have performed the act of worship, remember Allah, standing, sitting and reclining. And when ye are in safety, observe proper worship. Worship at fixed times hath been enjoined on the believers.",
  },
  {
    id: "Q02",
    reference: "Qur'an 29:45",
    referenceArabic: "القرآن ٢٩:٤٥",
    surahEnglish: "Al-Ankabut",
    surahArabic: "سُورَةُ العَنكَبُوتِ",
    arabic:
      "ٱتْلُ مَآ أُوحِىَ إِلَيْكَ مِنَ ٱلْكِتَٰبِ وَأَقِمِ ٱلصَّلَوٰةَ ۖ إِنَّ ٱلصَّلَوٰةَ تَنْهَىٰ عَنِ ٱلْفَحْشَآءِ وَٱلْمُنكَرِ ۗ وَلَذِكْرُ ٱللَّهِ أَكْبَرُ ۗ وَٱللَّهُ يَعْلَمُ مَا تَصْنَعُونَ ﴿٤٥﴾",
    english:
      "Recite that which hath been inspired in thee of the Scripture, and establish worship. Lo! worship preserveth from lewdness and iniquity, but verily remembrance of Allah is more important. And Allah knoweth what ye do.",
  },
  {
    id: "Q03",
    reference: "Qur'an 17:78",
    referenceArabic: "القرآن ١٧:٧٨",
    surahEnglish: "Al-Isra",
    surahArabic: "سُورَةُ الإِسۡرَاءِ",
    arabic:
      "أَقِمِ ٱلصَّلَوٰةَ لِدُلُوكِ ٱلشَّمْسِ إِلَىٰ غَسَقِ ٱلَّيْلِ وَقُرْءَانَ ٱلْفَجْرِ ۖ إِنَّ قُرْءَانَ ٱلْفَجْرِ كَانَ مَشْهُودًۭا ﴿٧٨﴾",
    english:
      "Establish worship at the going down of the sun until the dark of night, and (the recital of) the Qur'an at dawn. Lo! (the recital of) the Qur'an at dawn is ever witnessed.",
  },
  {
    id: "Q04",
    reference: "Qur'an 33:41-42",
    referenceArabic: "القرآن ٣٣:٤١-٤٢",
    surahEnglish: "Al-Ahzab",
    surahArabic: "سُورَةُ الأَحۡزَابِ",
    arabic:
      "يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱذْكُرُوا۟ ٱللَّهَ ذِكْرًۭا كَثِيرًۭا ﴿٤١﴾ وَسَبِّحُوهُ بُكْرَةًۭ وَأَصِيلًا ﴿٤٢﴾",
    english: "O ye who believe! Remember Allah with much remembrance. And glorify Him early and late.",
  },
  {
    id: "Q05",
    reference: "Qur'an 30:17-18",
    referenceArabic: "القرآن ٣٠:١٧-١٨",
    surahEnglish: "Ar-Rum",
    surahArabic: "سُورَةُ الرُّومِ",
    arabic:
      "فَسُبْحَٰنَ ٱللَّهِ حِينَ تُمْسُونَ وَحِينَ تُصْبِحُونَ ﴿١٧﴾ وَلَهُ ٱلْحَمْدُ فِى ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ وَعَشِيًّۭا وَحِينَ تُظْهِرُونَ ﴿١٨﴾",
    english:
      "So glory be to Allah when ye enter the night and when ye enter the morning - Unto Him be praise in the heavens and the earth! - and at the sun's decline and in the noonday.",
  },
  {
    id: "Q06",
    reference: "Qur'an 2:152",
    referenceArabic: "القرآن ٢:١٥٢",
    surahEnglish: "Al-Baqarah",
    surahArabic: "سُورَةُ البَقَرَةِ",
    arabic: "فَٱذْكُرُونِىٓ أَذْكُرْكُمْ وَٱشْكُرُوا۟ لِى وَلَا تَكْفُرُونِ ﴿١٥٢﴾",
    english: "Therefore remember Me, I will remember you. Give thanks to Me, and reject not Me.",
  },
  {
    id: "Q07",
    reference: "Qur'an 13:28",
    referenceArabic: "القرآن ١٣:٢٨",
    surahEnglish: "Ar-Ra'd",
    surahArabic: "سُورَةُ الرَّعۡدِ",
    arabic:
      "ٱلَّذِينَ ءَامَنُوا۟ وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ ٱللَّهِ ۗ أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ ﴿٢٨﴾",
    english:
      "Who have believed and whose hearts have rest in the remembrance of Allah. Verily in the remembrance of Allah do hearts find rest!",
  },
  {
    id: "Q08",
    reference: "Qur'an 2:238",
    referenceArabic: "القرآن ٢:٢٣٨",
    surahEnglish: "Al-Baqarah",
    surahArabic: "سُورَةُ البَقَرَةِ",
    arabic: "حَٰفِظُوا۟ عَلَى ٱلصَّلَوَٰتِ وَٱلصَّلَوٰةِ ٱلْوُسْطَىٰ وَقُومُوا۟ لِلَّهِ قَٰنِتِينَ ﴿٢٣٨﴾",
    english: "Be guardians of your prayers, and of the midmost prayer, and stand up with devotion to Allah.",
  },
  {
    id: "Q09",
    reference: "Qur'an 50:39-40",
    referenceArabic: "القرآن ٥٠:٣٩-٤٠",
    surahEnglish: "Qaf",
    surahArabic: "سُورَةُ قٓ",
    arabic:
      "فَٱصْبِرْ عَلَىٰ مَا يَقُولُونَ وَسَبِّحْ بِحَمْدِ رَبِّكَ قَبْلَ طُلُوعِ ٱلشَّمْسِ وَقَبْلَ ٱلْغُرُوبِ ﴿٣٩﴾ وَمِنَ ٱلَّيْلِ فَسَبِّحْهُ وَأَدْبَٰرَ ٱلسُّجُودِ ﴿٤٠﴾",
    english:
      "Therefor (O Muhammad) bear with what they say, and hymn the praise of thy Lord before the rising and before the setting of the sun; And in the night-time hymn His praise, and after the (prescribed) prostrations.",
  },
  {
    id: "Q10",
    reference: "Qur'an 20:130",
    referenceArabic: "القرآن ٢٠:١٣٠",
    surahEnglish: "Ta-Ha",
    surahArabic: "سُورَةُ طه",
    arabic:
      "فَٱصْبِرْ عَلَىٰ مَا يَقُولُونَ وَسَبِّحْ بِحَمْدِ رَبِّكَ قَبْلَ طُلُوعِ ٱلشَّمْسِ وَقَبْلَ غُرُوبِهَا ۖ وَمِنْ ءَانَآئِ ٱلَّيْلِ فَسَبِّحْ وَأَطْرَافَ ٱلنَّهَارِ لَعَلَّكَ تَرْضَىٰ ﴿١٣٠﴾",
    english:
      "Therefor (O Muhammad), bear with what they say, and celebrate the praise of thy Lord ere the rising of the sun and ere the going down thereof. And glorify Him some hours of the night and at the two ends of the day, that thou mayst find acceptance.",
  },
  {
    id: "Q11",
    reference: "Qur'an 11:114",
    referenceArabic: "القرآن ١١:١١٤",
    surahEnglish: "Hud",
    surahArabic: "سُورَةُ هُودٍ",
    arabic:
      "وَأَقِمِ ٱلصَّلَوٰةَ طَرَفَىِ ٱلنَّهَارِ وَزُلَفًۭا مِّنَ ٱلَّيْلِ ۚ إِنَّ ٱلْحَسَنَٰتِ يُذْهِبْنَ ٱلسَّيِّـَٔاتِ ۚ ذَٰلِكَ ذِكْرَىٰ لِلذَّٰكِرِينَ ﴿١١٤﴾",
    english:
      "Establish worship at the two ends of the day and in some watches of the night. Lo! good deeds annul ill-deeds. This is reminder for the mindful.",
  },
  {
    id: "Q12",
    reference: "Qur'an 17:79",
    referenceArabic: "القرآن ١٧:٧٩",
    surahEnglish: "Al-Isra",
    surahArabic: "سُورَةُ الإِسۡرَاءِ",
    arabic:
      "وَمِنَ ٱلَّيْلِ فَتَهَجَّدْ بِهِۦ نَافِلَةًۭ لَّكَ عَسَىٰٓ أَن يَبْعَثَكَ رَبُّكَ مَقَامًۭا مَّحْمُودًۭا ﴿٧٩﴾",
    english:
      "And some part of the night awake for it, a largess for thee. It may be that thy Lord will raise thee to a praised estate.",
  },
  {
    id: "Q13",
    reference: "Qur'an 25:64",
    referenceArabic: "القرآن ٢٥:٦٤",
    surahEnglish: "Al-Furqan",
    surahArabic: "سُورَةُ الفُرۡقَانِ",
    arabic: "وَٱلَّذِينَ يَبِيتُونَ لِرَبِّهِمْ سُجَّدًۭا وَقِيَٰمًۭا ﴿٦٤﴾",
    english: "And who spend the night before their Lord, prostrate and standing,",
  },
  {
    id: "Q14",
    reference: "Qur'an 73:20",
    referenceArabic: "القرآن ٧٣:٢٠",
    surahEnglish: "Al-Muzzammil",
    surahArabic: "سُورَةُ المُزَّمِّلِ",
    arabic:
      "۞ إِنَّ رَبَّكَ يَعْلَمُ أَنَّكَ تَقُومُ أَدْنَىٰ مِن ثُلُثَىِ ٱلَّيْلِ وَنِصْفَهُۥ وَثُلُثَهُۥ وَطَآئِفَةٌۭ مِّنَ ٱلَّذِينَ مَعَكَ ۚ وَٱللَّهُ يُقَدِّرُ ٱلَّيْلَ وَٱلنَّهَارَ ۚ عَلِمَ أَن لَّن تُحْصُوهُ فَتَابَ عَلَيْكُمْ ۖ فَٱقْرَءُوا۟ مَا تَيَسَّرَ مِنَ ٱلْقُرْءَانِ ۚ عَلِمَ أَن سَيَكُونُ مِنكُم مَّرْضَىٰ ۙ وَءَاخَرُونَ يَضْرِبُونَ فِى ٱلْأَرْضِ يَبْتَغُونَ مِن فَضْلِ ٱللَّهِ ۙ وَءَاخَرُونَ يُقَٰتِلُونَ فِى سَبِيلِ ٱللَّهِ ۖ فَٱقْرَءُوا۟ مَا تَيَسَّرَ مِنْهُ ۚ وَأَقِيمُوا۟ ٱلصَّلَوٰةَ وَءَاتُوا۟ ٱلزَّكَوٰةَ وَأَقْرِضُوا۟ ٱللَّهَ قَرْضًا حَسَنًۭا ۚ وَمَا تُقَدِّمُوا۟ لِأَنفُسِكُم مِّنْ خَيْرٍۢ تَجِدُوهُ عِندَ ٱللَّهِ هُوَ خَيْرًۭا وَأَعْظَمَ أَجْرًۭا ۚ وَٱسْتَغْفِرُوا۟ ٱللَّهَ ۖ إِنَّ ٱللَّهَ غَفُورٌۭ رَّحِيمٌۢ ﴿٢٠﴾",
    english:
      "Lo! thy Lord knoweth how thou keepest vigil sometimes nearly two-thirds of the night, or (sometimes) half or a third thereof, as do a party of those with thee. Allah measureth the night and the day. He knoweth that ye count it not, and turneth unto you in mercy. Recite, then, of the Qur'an that which is easy for you. He knoweth that there are sick folk among you, while others travel in the land in search of Allah's bounty, and others (still) are fighting for the cause of Allah. So recite of it that which is easy (for you), and establish worship and pay the poor-due, and (so) lend unto Allah a goodly loan. Whatsoever good ye send before you for your souls, ye will find it with Allah, better and greater in the recompense. And seek forgiveness of Allah. Lo! Allah is Forgiving, Merciful.",
  },
  {
    id: "Q15",
    reference: "Qur'an 3:190-191",
    referenceArabic: "القرآن ٣:١٩٠-١٩١",
    surahEnglish: "Al-Imran",
    surahArabic: "سُورَةُ آلِ عِمۡرَانَ",
    arabic:
      "إِنَّ فِى خَلْقِ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ وَٱخْتِلَٰفِ ٱلَّيْلِ وَٱلنَّهَارِ لَءَايَٰتٍۢ لِّأُو۟لِى ٱلْأَلْبَٰبِ ﴿١٩٠﴾ ٱلَّذِينَ يَذْكُرُونَ ٱللَّهَ قِيَٰمًۭا وَقُعُودًۭا وَعَلَىٰ جُنُوبِهِمْ وَيَتَفَكَّرُونَ فِى خَلْقِ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ رَبَّنَا مَا خَلَقْتَ هَٰذَا بَٰطِلًۭا سُبْحَٰنَكَ فَقِنَا عَذَابَ ٱلنَّارِ ﴿١٩١﴾",
    english:
      "Lo! In the creation of the heavens and the earth and (in) the difference of night and day are tokens (of His Sovereignty) for men of understanding, Such as remember Allah, standing, sitting, and reclining, and consider the creation of the heavens and the earth, (and say): Our Lord! Thou createdst not this in vain. Glory be to Thee! Preserve us from the doom of Fire.",
  },
  {
    id: "Q16",
    reference: "Qur'an 2:255",
    referenceArabic: "القرآن ٢:٢٥٥",
    surahEnglish: "Al-Baqarah",
    surahArabic: "سُورَةُ البَقَرَةِ",
    arabic:
      "ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌۭ وَلَا نَوْمٌۭ ۚ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ مَن ذَا ٱلَّذِى يَشْفَعُ عِندَهُۥٓ إِلَّا بِإِذْنِهِۦ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَىْءٍۢ مِّنْ عِلْمِهِۦٓ إِلَّا بِمَا شَآءَ ۚ وَسِعَ كُرْسِيُّهُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ ۖ وَلَا يَـُٔودُهُۥ حِفْظُهُمَا ۚ وَهُوَ ٱلْعَلِىُّ ٱلْعَظِيمُ ﴿٢٥٥﴾",
    english:
      "Allah! There is no deity save Him, the Alive, the Eternal. Neither slumber nor sleep overtaketh Him. Unto Him belongeth whatsoever is in the heavens and whatsoever is in the earth. Who is he that intercedeth with Him save by His leave? He knoweth that which is in front of them and that which is behind them, while they encompass nothing of His knowledge save what He will. His throne includeth the heavens and the earth, and He is never weary of preserving them. He is the Sublime, the Tremendous.",
  },
  {
    id: "Q17",
    reference: "Qur'an 2:285-286",
    referenceArabic: "القرآن ٢:٢٨٥-٢٨٦",
    surahEnglish: "Al-Baqarah",
    surahArabic: "سُورَةُ البَقَرَةِ",
    arabic:
      "ءَامَنَ ٱلرَّسُولُ بِمَآ أُنزِلَ إِلَيْهِ مِن رَّبِّهِۦ وَٱلْمُؤْمِنُونَ ۚ كُلٌّ ءَامَنَ بِٱللَّهِ وَمَلَٰٓئِكَتِهِۦ وَكُتُبِهِۦ وَرُسُلِهِۦ لَا نُفَرِّقُ بَيْنَ أَحَدٍۢ مِّن رُّسُلِهِۦ ۚ وَقَالُوا۟ سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ ٱلْمَصِيرُ ﴿٢٨٥﴾ لَا يُكَلِّفُ ٱللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا ٱكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَآ إِن نَّسِينَآ أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَآ إِصْرًۭا كَمَا حَمَلْتَهُۥ عَلَى ٱلَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِۦ ۖ وَٱعْفُ عَنَّا وَٱغْفِرْ لَنَا وَٱرْحَمْنَآ ۚ أَنتَ مَوْلَىٰنَا فَٱنصُرْنَا عَلَى ٱلْقَوْمِ ٱلْكَٰفِرِينَ ﴿٢٨٦﴾",
    english:
      "The messenger believeth in that which hath been revealed unto him from his Lord and (so do) believers. Each one believeth in Allah and His angels and His scriptures and His messengers - We make no distinction between any of His messengers - and they say: We hear, and we obey. (Grant us) Thy forgiveness, our Lord. Unto Thee is the journeying. Allah tasketh not a soul beyond its scope. For it (is only) that which it hath earned, and against it (only) that which it hath deserved. Our Lord! Condemn us not if we forget, or miss the mark! Our Lord! Lay not on us such a burden as thou didst lay on those before us! Our Lord! Impose not on us that which we have not the strength to bear! Pardon us, absolve us and have mercy on us, Thou, our Protector, and give us victory over the disbelieving folk.",
  },
  {
    id: "Q18",
    reference: "Qur'an 62:9-10",
    referenceArabic: "القرآن ٦٢:٩-١٠",
    surahEnglish: "Al-Jumu'ah",
    surahArabic: "سُورَةُ الجُمُعَةِ",
    arabic:
      "يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ إِذَا نُودِىَ لِلصَّلَوٰةِ مِن يَوْمِ ٱلْجُمُعَةِ فَٱسْعَوْا۟ إِلَىٰ ذِكْرِ ٱللَّهِ وَذَرُوا۟ ٱلْبَيْعَ ۚ ذَٰلِكُمْ خَيْرٌۭ لَّكُمْ إِن كُنتُمْ تَعْلَمُونَ ﴿٩﴾ فَإِذَا قُضِيَتِ ٱلصَّلَوٰةُ فَٱنتَشِرُوا۟ فِى ٱلْأَرْضِ وَٱبْتَغُوا۟ مِن فَضْلِ ٱللَّهِ وَٱذْكُرُوا۟ ٱللَّهَ كَثِيرًۭا لَّعَلَّكُمْ تُفْلِحُونَ ﴿١٠﴾",
    english:
      "O ye who believe! When the call is heard for the prayer of the day of congregation, haste unto remembrance of Allah and leave your trading. That is better for you if ye did but know. And when the prayer is ended, then disperse in the land and seek of Allah's bounty, and remember Allah much, that ye may be successful.",
  },
];
