import type { AppLanguage } from "../types";

export type BenefitSection = "quran" | "hadith" | "derived";
export type DerivedBenefitGroup = "forgiveness" | "reward" | "protection" | "paradise" | "heart";

interface LocalizedText {
  ar: string;
  en: string;
}

export interface BenefitEvidence {
  id: string;
  kind: Exclude<BenefitSection, "derived">;
  title: LocalizedText;
  text: LocalizedText;
  source: LocalizedText;
  sourceUrl: string;
}

export interface DerivedZikrBenefit {
  id: string;
  evidenceId: string;
  group: DerivedBenefitGroup;
  zikr: LocalizedText;
  benefit: LocalizedText;
}

const quran = (id: string, reference: string, arabic: string, meaning: string, sourceUrl: string): BenefitEvidence => ({
  id,
  kind: "quran",
  title: { ar: reference.replace("Qur'an", "القرآن"), en: reference },
  text: { ar: arabic, en: meaning },
  source: { ar: reference.replace("Qur'an", "القرآن الكريم"), en: reference },
  sourceUrl,
});

const hadith = (
  id: string,
  zikrAr: string,
  zikrEn: string,
  claimAr: string,
  claimEn: string,
  sourceAr: string,
  sourceEn: string,
  sourceUrl: string,
): BenefitEvidence => ({
  id,
  kind: "hadith",
  title: { ar: zikrAr, en: zikrEn },
  text: { ar: claimAr, en: claimEn },
  source: { ar: sourceAr, en: sourceEn },
  sourceUrl,
});

export const QURAN_DHIKR_EVIDENCE: readonly BenefitEvidence[] = [
  quran(
    "quran-13-28",
    "Qur'an 13:28",
    "الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللَّهِ ۗ أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
    "Those who believe and whose hearts find comfort in the remembrance of Allah. Surely in the remembrance of Allah do hearts find comfort.",
    "https://quran.com/13/28",
  ),
  quran(
    "quran-2-152",
    "Qur'an 2:152",
    "فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ",
    "Remember Me; I will remember you. Be thankful to Me, and do not be ungrateful.",
    "https://quran.com/2/152",
  ),
  quran(
    "quran-33-35",
    "Qur'an 33:35",
    "وَالذَّاكِرِينَ اللَّهَ كَثِيرًا وَالذَّاكِرَاتِ أَعَدَّ اللَّهُ لَهُم مَّغْفِرَةً وَأَجْرًا عَظِيمًا",
    "For the men and women who remember Allah often, Allah has prepared forgiveness and a great reward.",
    "https://quran.com/33/35",
  ),
  quran(
    "quran-62-10",
    "Qur'an 62:10",
    "وَاذْكُرُوا اللَّهَ كَثِيرًا لَّعَلَّكُمْ تُفْلِحُونَ",
    "Remember Allah often so that you may succeed.",
    "https://quran.com/62/10",
  ),
  quran(
    "quran-8-45",
    "Qur'an 8:45",
    "يَا أَيُّهَا الَّذِينَ آمَنُوا إِذَا لَقِيتُمْ فِئَةً فَاثْبُتُوا وَاذْكُرُوا اللَّهَ كَثِيرًا لَّعَلَّكُمْ تُفْلِحُونَ",
    "Believers are commanded to stand firm and remember Allah often when facing difficulty, so that they may succeed.",
    "https://quran.com/8/45",
  ),
  quran(
    "quran-3-191",
    "Qur'an 3:191",
    "الَّذِينَ يَذْكُرُونَ اللَّهَ قِيَامًا وَقُعُودًا وَعَلَىٰ جُنُوبِهِمْ",
    "They remember Allah while standing, sitting, and lying on their sides.",
    "https://quran.com/3/191",
  ),
  quran(
    "quran-33-41",
    "Qur'an 33:41",
    "يَا أَيُّهَا الَّذِينَ آمَنُوا اذْكُرُوا اللَّهَ ذِكْرًا كَثِيرًا",
    "O believers, remember Allah with frequent remembrance.",
    "https://quran.com/33/41",
  ),
];

export const HADITH_DHIKR_EVIDENCE: readonly BenefitEvidence[] = [
  hadith(
    "h-subhanallah-100",
    "سُبْحَانَ اللهِ وَبِحَمْدِهِ × ١٠٠",
    "SubhanAllahi wa bihamdih ×100",
    "تُحَطُّ خطاياه وإن كانت مثل زبد البحر.",
    "Sins are erased even if they are like the foam of the sea.",
    "صحيح البخاري ٦٤٠٥؛ صحيح مسلم ٢٦٩١",
    "Sahih al-Bukhari 6405; Sahih Muslim 2691",
    "https://dorar.net/hadith/sharh/10615",
  ),
  hadith(
    "h-subhanallah-am-pm",
    "سُبْحَانَ اللهِ وَبِحَمْدِهِ صباحًا ومساءً × ١٠٠",
    "SubhanAllahi wa bihamdih morning and evening ×100",
    "لا يأتي أحد يوم القيامة بأفضل مما جاء به إلا من قال مثل قوله أو زاد عليه.",
    "No one brings something better on the Day of Resurrection except one who says the same or more.",
    "صحيح مسلم ٢٦٩٢",
    "Sahih Muslim 2692",
    "https://dorar.net/hadith/sharh/37184",
  ),
  hadith(
    "h-two-phrases",
    "سُبْحَانَ اللهِ وَبِحَمْدِهِ، سُبْحَانَ اللهِ العَظِيمِ",
    "SubhanAllahi wa bihamdih, SubhanAllahil-Azim",
    "كلمتان خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن.",
    "Two phrases light on the tongue, heavy on the Scale, and beloved to the Most Merciful.",
    "صحيح البخاري ٦٦٨٢؛ صحيح مسلم ٢٦٩٤",
    "Sahih al-Bukhari 6682; Sahih Muslim 2694",
    "https://dorar.net/h/4DZspCuR",
  ),
  hadith(
    "h-palm",
    "سُبْحَانَ اللهِ العَظِيمِ وَبِحَمْدِهِ",
    "SubhanAllahil-Azimi wa bihamdih",
    "تُغرس له نخلة في الجنة.",
    "A palm tree is planted for the one who says it in Paradise.",
    "جامع الترمذي ٣٤٦٤؛ صححه الألباني",
    "Jami at-Tirmidhi 3464; authenticated by al-Albani",
    "https://dorar.net/hadith/sharh/84447",
  ),
  hadith(
    "h-four-phrases",
    "سُبْحَانَ اللهِ، وَالْحَمْدُ للهِ، وَلَا إِلَهَ إِلَّا اللهُ، وَاللهُ أَكْبَرُ",
    "SubhanAllah, Alhamdulillah, La ilaha illa Allah, Allahu Akbar",
    "هذه الكلمات أحب إلى النبي ﷺ مما طلعت عليه الشمس.",
    "These four phrases were more beloved to the Prophet ﷺ than everything upon which the sun rises.",
    "صحيح مسلم ٢٦٩٥",
    "Sahih Muslim 2695",
    "https://dorar.net/hadith/sharh/20506",
  ),
  hadith(
    "h-tahlil-100",
    "لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ... × ١٠٠",
    "La ilaha illa Allah wahdahu la sharika lah… ×100",
    "له عدل عشر رقاب، ومائة حسنة، ومحو مائة سيئة، وحرز من الشيطان حتى يمسي، ولا يأتي أحد بأفضل إلا من زاد.",
    "It brings the reward of freeing ten slaves, one hundred good deeds, erases one hundred sins, protects from Satan until evening, and none brings better except one who does more.",
    "صحيح البخاري ٣٢٩٣؛ صحيح مسلم ٢٦٩١",
    "Sahih al-Bukhari 3293; Sahih Muslim 2691",
    "https://dorar.net/h/Sx0ZLO6u?osoul=1",
  ),
  hadith(
    "h-hawqalah",
    "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ",
    "La hawla wa la quwwata illa billah",
    "كنز من كنوز الجنة.",
    "A treasure from the treasures of Paradise.",
    "صحيح مسلم ٢٧٠٤",
    "Sahih Muslim 2704",
    "https://dorar.net/h/vfqk0U79?osoul=1",
  ),
  hadith(
    "h-sayyid",
    "سَيِّدُ الاسْتِغْفَار",
    "Sayyid al-Istighfar",
    "من قاله موقنًا به نهارًا فمات قبل المساء فهو من أهل الجنة، وكذلك ليلًا قبل الصباح.",
    "Whoever says it with certainty by day and dies before evening is among the people of Paradise; likewise by night before morning.",
    "صحيح البخاري ٦٣٠٦",
    "Sahih al-Bukhari 6306",
    "https://dorar.net/h/wYm87auc?osoul=1",
  ),
  hadith(
    "h-juwayriyyah",
    "سُبْحَانَ اللهِ وَبِحَمْدِهِ، عَدَدَ خَلْقِهِ... × ٣",
    "SubhanAllahi wa bihamdih, adada khalqihi… ×3",
    "تزن هذه الكلمات ما قيل من الذكر منذ الصباح.",
    "These words weigh as much as the remembrance recited throughout the morning.",
    "صحيح مسلم ٢٧٢٦",
    "Sahih Muslim 2726",
    "https://dorar.net/h/KuBvklqY?osoul=1",
  ),
  hadith(
    "h-after-prayer",
    "تسبيح دبر الصلاة: ٣٣، ٣٣، ٣٣ ثم التهليل",
    "Post-prayer dhikr: 33, 33, 33, then tahlil",
    "تُغفر خطاياه وإن كانت مثل زبد البحر.",
    "Sins are forgiven even if they are like the foam of the sea.",
    "صحيح مسلم ٥٩٧",
    "Sahih Muslim 597",
    "https://dorar.net/hadith/sharh/23604",
  ),
  hadith(
    "h-salawat",
    "الصلاة على النبي ﷺ",
    "Sending salah upon the Prophet ﷺ",
    "من صلى على النبي ﷺ واحدة صلى الله عليه بها عشرًا.",
    "For one salah upon the Prophet ﷺ, Allah sends ten upon the person.",
    "صحيح مسلم ٤٠٨",
    "Sahih Muslim 408",
    "https://dorar.net/h/boq0Hbsx?osoul=1",
  ),
  hadith(
    "h-bismillah",
    "بِسْمِ اللهِ الَّذِي لَا يَضُرُّ... × ٣ صباحًا ومساءً",
    "Bismillah alladhi la yadurr… ×3 morning and evening",
    "لا يضره شيء حتى يمسي أو يصبح.",
    "Nothing harms the one who says it until evening or morning.",
    "سنن أبي داود ٥٠٨٨؛ الترمذي ٣٣٨٨؛ صححه الألباني",
    "Sunan Abi Dawud 5088; Tirmidhi 3388; authenticated by al-Albani",
    "https://dorar.net/h/0nQmCpgK",
  ),
  hadith(
    "h-three-quls",
    "الإخلاص والفلق والناس × ٣ صباحًا ومساءً",
    "Al-Ikhlas, Al-Falaq, and An-Nas ×3 morning and evening",
    "تكفي من كل شيء.",
    "They suffice against everything.",
    "سنن أبي داود ٥٠٨٢؛ الترمذي ٣٥٧٥؛ صححه الألباني",
    "Sunan Abi Dawud 5082; Tirmidhi 3575; authenticated by al-Albani",
    "https://dorar.net/h/4HhZknUQ",
  ),
  hadith(
    "h-kursi",
    "آية الكرسي عند النوم",
    "Ayat al-Kursi at bedtime",
    "يبقى من الله حافظ، ولا يقربه شيطان حتى يصبح.",
    "A guardian from Allah remains, and Satan does not approach until morning.",
    "صحيح البخاري ٢٣١١",
    "Sahih al-Bukhari 2311",
    "https://dorar.net/h/6PBFMcnT?osoul=1",
  ),
  hadith(
    "h-baqarah-last-two",
    "آخر آيتين من سورة البقرة ليلًا",
    "The last two verses of Al-Baqarah at night",
    "من قرأهما في ليلة كفتاه.",
    "Whoever recites them at night, they suffice him.",
    "صحيح البخاري ٥٠٠٩؛ صحيح مسلم ٨٠٨",
    "Sahih al-Bukhari 5009; Sahih Muslim 808",
    "https://dorar.net/h/Y6lzAdUt",
  ),
  hadith(
    "h-place",
    "أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    "A'udhu bi kalimatillahit-tammati min sharri ma khalaq",
    "لا يضره شيء حتى يرتحل من منزله ذلك.",
    "Nothing harms the person at that place until they leave.",
    "صحيح مسلم ٢٧٠٨",
    "Sahih Muslim 2708",
    "https://dorar.net/hadith/sharh/20531",
  ),
  hadith(
    "h-yunus",
    "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
    "La ilaha illa Anta, subhanaka inni kuntu minaz-zalimin",
    "ما دعا بها مسلم في شيء قط إلا استجاب الله له.",
    "No Muslim supplicates with it concerning anything except that Allah answers.",
    "جامع الترمذي ٣٥٠٥؛ القرآن ٢١:٨٧",
    "Jami at-Tirmidhi 3505; Qur'an 21:87",
    "https://dorar.net/h/Eg2I0Z7f?osoul=1",
  ),
  hadith(
    "h-raditu",
    "رَضِيتُ بِاللهِ رَبًّا، وَبِالإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ رَسُولًا",
    "Raditu billahi Rabban, wa bil-Islami dinan, wa bi-Muhammadin Rasulan",
    "وجبت له الجنة.",
    "Paradise becomes due for the one who says it.",
    "سنن أبي داود ١٥٢٩؛ يشهد له صحيح مسلم ١٨٨٤؛ صححه الألباني",
    "Sunan Abi Dawud 1529; supported by Sahih Muslim 1884; authenticated by al-Albani",
    "https://dorar.net/hadith/sharh/66201",
  ),
  hadith(
    "h-fatima",
    "تسبيح فاطمة عند النوم: ٣٣، ٣٣، ٣٤",
    "Tasbih Fatimah at bedtime: 33, 33, 34",
    "هو خير لعلي وفاطمة رضي الله عنهما من خادم.",
    "It was taught to Ali and Fatimah, may Allah be pleased with them, as better for them than a servant.",
    "صحيح البخاري ٣١١٣؛ صحيح مسلم ٢٧٢٧",
    "Sahih al-Bukhari 3113; Sahih Muslim 2727",
    "https://dorar.net/hadith/sharh/23046",
  ),
  hadith(
    "h-living-heart",
    "ذكر الله",
    "Remembering Allah",
    "مثل الذي يذكر ربه والذي لا يذكر ربه مثل الحي والميت.",
    "The one who remembers his Lord and the one who does not are compared to the living and the dead.",
    "صحيح البخاري ٦٤٠٧",
    "Sahih al-Bukhari 6407",
    "https://dorar.net/hadith/sharh/10599",
  ),
  hadith(
    "h-gatherings",
    "مجالس ذكر الله",
    "Gatherings that remember Allah",
    "تحفهم الملائكة، وتغشاهم الرحمة، وتنزل عليهم السكينة، ويذكرهم الله فيمن عنده.",
    "The angels surround them, mercy covers them, tranquility descends, and Allah mentions them among those with Him.",
    "صحيح مسلم ٢٧٠٠",
    "Sahih Muslim 2700",
    "https://dorar.net/hadith/sharh/40044",
  ),
];

const derived = (
  id: string,
  evidenceId: string,
  group: DerivedBenefitGroup,
  zikrAr: string,
  zikrEn: string,
  benefitAr: string,
  benefitEn: string,
): DerivedZikrBenefit => ({
  id,
  evidenceId,
  group,
  zikr: { ar: zikrAr, en: zikrEn },
  benefit: { ar: benefitAr, en: benefitEn },
});

export const DERIVED_ZIKR_BENEFITS: readonly DerivedZikrBenefit[] = [
  derived(
    "d-01",
    "h-subhanallah-100",
    "forgiveness",
    "سُبْحَانَ اللهِ وَبِحَمْدِهِ × ١٠٠",
    "SubhanAllahi wa bihamdih ×100",
    "حط الخطايا ولو كانت مثل زبد البحر.",
    "Sins are erased even if they are like the foam of the sea.",
  ),
  derived(
    "d-02",
    "h-subhanallah-am-pm",
    "reward",
    "سُبْحَانَ اللهِ وَبِحَمْدِهِ صباحًا ومساءً",
    "SubhanAllahi wa bihamdih morning and evening",
    "لا يأتي أحد بأفضل منه إلا من قال مثله أو زاد.",
    "No one brings better except one who says the same or more.",
  ),
  derived(
    "d-03",
    "h-two-phrases",
    "reward",
    "التسبيحتان",
    "The two phrases of tasbih",
    "خفيفتان على اللسان.",
    "They are light on the tongue.",
  ),
  derived(
    "d-04",
    "h-two-phrases",
    "reward",
    "التسبيحتان",
    "The two phrases of tasbih",
    "ثقيلتان في الميزان.",
    "They are heavy on the Scale.",
  ),
  derived(
    "d-05",
    "h-two-phrases",
    "heart",
    "التسبيحتان",
    "The two phrases of tasbih",
    "حبيبتان إلى الرحمن.",
    "They are beloved to the Most Merciful.",
  ),
  derived(
    "d-06",
    "h-palm",
    "paradise",
    "سُبْحَانَ اللهِ العَظِيمِ وَبِحَمْدِهِ",
    "SubhanAllahil-Azimi wa bihamdih",
    "غرس نخلة في الجنة.",
    "A palm tree is planted in Paradise.",
  ),
  derived(
    "d-07",
    "h-four-phrases",
    "reward",
    "التسبيح والتحميد والتهليل والتكبير",
    "Tasbih, tahmid, tahlil, and takbir",
    "أحب إلى النبي ﷺ مما طلعت عليه الشمس.",
    "More beloved to the Prophet ﷺ than everything upon which the sun rises.",
  ),
  derived(
    "d-08",
    "h-tahlil-100",
    "reward",
    "التهليل الكامل × ١٠٠",
    "The complete tahlil ×100",
    "ثواب عدل عشر رقاب.",
    "Reward equivalent to freeing ten slaves.",
  ),
  derived(
    "d-09",
    "h-tahlil-100",
    "reward",
    "التهليل الكامل × ١٠٠",
    "The complete tahlil ×100",
    "كتابة مائة حسنة.",
    "One hundred good deeds are recorded.",
  ),
  derived(
    "d-10",
    "h-tahlil-100",
    "forgiveness",
    "التهليل الكامل × ١٠٠",
    "The complete tahlil ×100",
    "محو مائة سيئة.",
    "One hundred sins are erased.",
  ),
  derived(
    "d-11",
    "h-tahlil-100",
    "protection",
    "التهليل الكامل × ١٠٠",
    "The complete tahlil ×100",
    "حرز من الشيطان حتى المساء.",
    "Protection from Satan until evening.",
  ),
  derived(
    "d-12",
    "h-tahlil-100",
    "reward",
    "التهليل الكامل × ١٠٠",
    "The complete tahlil ×100",
    "لا يأتي أحد بأفضل إلا من عمل أكثر.",
    "No one brings better except one who does more.",
  ),
  derived(
    "d-13",
    "h-hawqalah",
    "paradise",
    "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ",
    "La hawla wa la quwwata illa billah",
    "كنز من كنوز الجنة.",
    "A treasure from the treasures of Paradise.",
  ),
  derived(
    "d-14",
    "h-sayyid",
    "paradise",
    "سيد الاستغفار بيقين",
    "Sayyid al-Istighfar with certainty",
    "بشارة الجنة لمن مات قبل نهاية فترة قوله نهارًا أو ليلًا.",
    "The promise of Paradise for one who dies before the end of the day or night period in which it was said.",
  ),
  derived(
    "d-15",
    "h-juwayriyyah",
    "reward",
    "ذكر جويرية × ٣",
    "The dhikr of Juwayriyyah ×3",
    "يزن ذكر صباح كامل كما ورد في الحديث.",
    "It weighs as much as a morning of remembrance, as stated in the hadith.",
  ),
  derived(
    "d-16",
    "h-after-prayer",
    "forgiveness",
    "ذكر دبر الصلاة",
    "Post-prayer dhikr",
    "غفران الخطايا ولو كانت مثل زبد البحر.",
    "Forgiveness of sins even if they are like the foam of the sea.",
  ),
  derived(
    "d-17",
    "h-salawat",
    "reward",
    "الصلاة على النبي ﷺ",
    "Sending salah upon the Prophet ﷺ",
    "يصلي الله على العبد بها عشرًا.",
    "Allah sends ten blessings for one salah.",
  ),
  derived(
    "d-18",
    "h-bismillah",
    "protection",
    "بِسْمِ اللهِ الَّذِي لَا يَضُرُّ... × ٣",
    "Bismillah alladhi la yadurr… ×3",
    "حفظ من الضرر حتى الفترة التالية صباحًا أو مساءً.",
    "Protection from harm until the next morning or evening period.",
  ),
  derived(
    "d-19",
    "h-three-quls",
    "protection",
    "سور الإخلاص والفلق والناس × ٣",
    "Al-Ikhlas, Al-Falaq, and An-Nas ×3",
    "تكفي من كل شيء.",
    "They suffice against everything.",
  ),
  derived(
    "d-20",
    "h-kursi",
    "protection",
    "آية الكرسي عند النوم",
    "Ayat al-Kursi at bedtime",
    "حافظ من الله حتى الصباح.",
    "A guardian from Allah remains until morning.",
  ),
  derived(
    "d-21",
    "h-kursi",
    "protection",
    "آية الكرسي عند النوم",
    "Ayat al-Kursi at bedtime",
    "لا يقرب الشيطان حتى الصباح.",
    "Satan does not approach until morning.",
  ),
  derived(
    "d-22",
    "h-baqarah-last-two",
    "protection",
    "آخر آيتين من البقرة ليلًا",
    "The last two verses of Al-Baqarah at night",
    "تكفيان قارئهما في ليلته.",
    "They suffice the one who recites them that night.",
  ),
  derived(
    "d-23",
    "h-place",
    "protection",
    "الاستعاذة بكلمات الله عند نزول مكان",
    "Seeking refuge in Allah's perfect words at a place",
    "لا يضره شيء حتى يرحل من ذلك المكان.",
    "Nothing harms the person until they leave that place.",
  ),
  derived(
    "d-24",
    "h-yunus",
    "heart",
    "دعاء يونس عليه السلام",
    "The supplication of Yunus",
    "وعد بالاستجابة عند الدعاء به.",
    "A promise of response when supplicating with it.",
  ),
  derived(
    "d-25",
    "h-raditu",
    "paradise",
    "رَضِيتُ بِاللهِ رَبًّا...",
    "Raditu billahi Rabban…",
    "وجوب الجنة كما جاء في الحديث.",
    "Paradise becomes due, as stated in the hadith.",
  ),
  derived(
    "d-26",
    "h-fatima",
    "reward",
    "تسبيح فاطمة عند النوم",
    "Tasbih Fatimah at bedtime",
    "خير من خادم لعلي وفاطمة رضي الله عنهما.",
    "Better than a servant for Ali and Fatimah, may Allah be pleased with them.",
  ),
  derived(
    "d-27",
    "h-living-heart",
    "heart",
    "ذكر الله",
    "Remembering Allah",
    "حياة للقلب في التشبيه النبوي.",
    "Life for the heart in the Prophet's comparison.",
  ),
  derived(
    "d-28",
    "h-gatherings",
    "heart",
    "مجالس الذكر",
    "Gatherings of remembrance",
    "تحفها الملائكة.",
    "The angels surround them.",
  ),
  derived(
    "d-29",
    "h-gatherings",
    "heart",
    "مجالس الذكر",
    "Gatherings of remembrance",
    "تغشاها الرحمة.",
    "Mercy covers them.",
  ),
  derived(
    "d-30",
    "h-gatherings",
    "heart",
    "مجالس الذكر",
    "Gatherings of remembrance",
    "تنزل عليها السكينة.",
    "Tranquility descends upon them.",
  ),
];

export function localizeBenefitText(value: LocalizedText, language: AppLanguage) {
  return value[language];
}

export function getBenefitEvidence(id: string) {
  return HADITH_DHIKR_EVIDENCE.find((item) => item.id === id);
}
