/**
 * Product icon contract.
 *
 * Every interface icon is sourced from the official Untitled UI line icon
 * package. Legacy aliases keep call sites concise while ensuring the rendered
 * SVGs all come from one design system.
 */
export {
  ActivityHeart as Leaf,
  AlignRight,
  AlertTriangle,
  ArrowLeft,
  ArrowNext,
  ArrowPrevious,
  ArrowRight,
  BarChart03 as BarChart3,
  BatteryFull,
  Bell01 as Bell,
  BookOpen01 as BookOpen,
  Check,
  Check as CheckIcon,
  CheckCircle as CheckCircle2,
  Clock,
  ChevronDown,
  ChevronDown as ChevronDownIcon,
  ChevronLeft,
  ChevronNext,
  ChevronNext as ChevronRightIcon,
  ChevronPrevious,
  ChevronPrevious as ChevronLeftIcon,
  ChevronRight,
  ChevronUp,
  ChevronUp as ChevronUpIcon,
  Circle as CircleIcon,
  CloudOff,
  Contrast01 as Contrast,
  DotsGrid as GripVerticalIcon,
  DotsHorizontal as MoreHorizontal,
  DotsHorizontal as MoreHorizontalIcon,
  Download01 as Download,
  Eye,
  File06 as FileText,
  Heart,
  Headphones01 as Headphones,
  HelpCircle,
  Home01 as Home,
  InfoCircle as Info,
  Globe01 as Globe,
  LayoutLeft as PanelLeftIcon,
  LinkExternal01 as ExternalLink,
  Menu02 as Menu,
  MessageChatCircle as MessageChat,
  Minus as MinusIcon,
  Moon01 as Moon,
  MoonStar,
  PauseCircle as Pause,
  Phone,
  Phone01 as Smartphone,
  Play,
  RefreshCcw01 as RotateCcw,
  SearchMd as Search,
  SearchMd as SearchIcon,
  Settings01 as Settings,
  Share07 as Share2,
  Signal03 as Signal,
  SkipBack,
  SkipForward,
  Stars01 as Stars,
  Star01 as Star,
  Stars01 as Sparkles,
  Sun,
  SwitchHorizontal01 as SwitchHorizontal,
  TrendUp01 as Sprout,
  Type01 as TypeIcon,
  VolumeMax as Volume2,
  VolumeX,
  Wifi,
  XClose as X,
  XClose as XIcon,
  Zap as Flame,
} from "@untitledui/icons";
