/**
 * Product icon contract.
 *
 * Every interface icon is sourced from the official Untitled UI line icon
 * package. Legacy aliases keep call sites concise while ensuring the rendered
 * SVGs all come from one design system.
 */
export {
  ActivityHeart as Leaf,
  AlignRight,
  AlertTriangle,
  Announcement01 as Announcement,
  ArrowLeft,
  ArrowNext,
  ArrowPrevious,
  ArrowRight,
  BarChart03 as BarChart3,
  BatteryFull,
  Bell01 as Bell,
  BookOpen01 as BookOpen,
  Check,
  Check as CheckIcon,
  CheckCircle as CheckCircle2,
  Calendar,
  Clock,
  ChevronDown,
  ChevronDown as ChevronDownIcon,
  ChevronLeft,
  ChevronNext,
  ChevronNext as ChevronRightIcon,
  ChevronPrevious,
  Bookmark,
  BookmarkAdd,
  BookmarkCheck,
  Brush01 as Brush,
  ChevronPrevious as ChevronLeftIcon,
  ChevronRight,
  ChevronUp,
  ChevronUp as ChevronUpIcon,
  Circle as CircleIcon,
  CloudOff,
  CloudSun02 as CloudSun,
  Contrast01 as Contrast,
  Copy04 as Copy,
  Database01 as Database,
  DotsGrid as GripVerticalIcon,
  DotsHorizontal as MoreHorizontal,
  DotsHorizontal as MoreHorizontalIcon,
  DotsVertical as MoreVertical,
  DotsVertical as MoreVerticalIcon,
  Download01 as Download,
  Eye,
  EyeOff,
  File06 as FileText,
  Heart,
  Headphones01 as Headphones,
  HelpCircle,
  Home01 as Home,
  InfoCircle as Info,
  Globe01 as Globe,
  LayoutLeft as PanelLeftIcon,
  LinkExternal01 as ExternalLink,
  Lock01 as Lock,
  List,
  LogOut01 as LogOut,
  MarkerPin01 as MapPin,
  Maximize01 as Maximize,
  Menu02 as Menu,
  MessageChatCircle as MessageChat,
  Minimize01 as Minimize,
  Minus,
  Minus as MinusIcon,
  Moon01 as Moon,
  MoonStar,
  PauseCircle as Pause,
  Plus,
  Phone,
  Phone01 as Smartphone,
  Play,
  RefreshCcw01 as RotateCcw,
  // Distinct from RotateCcw, which the design system reserves for reset/restart.
  ReverseLeft as Undo,
  Route,
  SearchMd as Search,
  SearchMd as SearchIcon,
  Settings01 as Settings,
  Share07 as Share2,
  Signal03 as Signal,
  SkipBack,
  SkipForward,
  Stars01 as Stars,
  Star01 as Star,
  Stars01 as Sparkles,
  Sliders01 as SlidersHorizontal,
  Sun,
  Sunrise,
  Sunset,
  SwitchHorizontal01 as SwitchHorizontal,
  // Word meanings, which used to borrow BookOpen from the benefit sheet: two
  // different actions cannot share one glyph and stay legible.
  Translate01 as Translate,
  TrendUp01 as Sprout,
  Type01 as TypeIcon,
  Type01 as Type,
  User01 as User,
  VolumeMax as Volume2,
  VolumeX,
  Wifi,
  Heart as Coffee,
  Building02 as Building,
  Droplets01 as Droplets,
  Dropper,
  Map01 as Plane,
  XClose as X,
  XClose as XIcon,
  Zap,
  Zap as Flame,
  Zap as Spark,
} from "@untitledui/icons";
