import { APPROVED_AUDIO_ASSIGNMENTS } from "./audioAssignments";
import type { AudioCatalog, AudioAsset, AudioSourceRecord } from "./audioTypes";
import { validateAudioCatalog } from "./validateAudioCatalog";
import { FRIDAY_KAHF } from "../content/fridayKahf";
import { createArabicTextFingerprint } from "./arabicMatching";

export const AUDIO_MANIFEST_VERSION = 3;

const kahfText = FRIDAY_KAHF[0]!.arabicText;
const kahfFingerprint = createArabicTextFingerprint(kahfText);

export const AUDIO_SOURCES: Readonly<Record<string, AudioSourceRecord>> = Object.freeze({
  "internal-upload": {
    id: "internal-upload",
    name: "Internal Upload",
    attribution: "Recitation by Muhammad Al-Shara",
    licenseName: "Publicly distributed",
    licenseEvidence: "N/A",
  },
  "internal-upload-abdullah-muhammad": {
    id: "internal-upload-abdullah-muhammad",
    name: "Azkarapp owner-supplied recordings",
    attribution: "Recitation by Abdullah Muhammad",
    licenseName: "Owner-authorized internal upload",
    licenseEvidence: "internal:owner-upload-2026-09-12",
  },
});

export const AUDIO_ASSETS: Readonly<Record<string, AudioAsset>> = Object.freeze({
  "quran-018": {
    id: "quran-018",
    titleArabic: "سورة الكهف",
    titleEnglish: "Surah Al-Kahf",
    contentKind: "quran",
    kind: "sequence",
    canonicalArabicText: kahfText,
    normalizedTextHash: kahfFingerprint,
    requiredQuranRange: {
      surah: 18,
      ayahStart: 1,
      ayahEnd: 110,
    },
    segments: [
      {
        id: "quran-018-complete",
        order: 1,
        transcriptArabic: kahfText,
        normalizedTranscriptHash: kahfFingerprint,
        quranReference: {
          surah: 18,
          ayahStart: 1,
          ayahEnd: 110,
        },
        variants: [
          {
            id: "quran-018-voice-muhammad-alshara-v1",
            voiceId: "muhammad-alshara",
            voiceName: "Muhammad Al-Shara",
            relativePath: "quran/friday-kahf/muhammad-alshara/v1/friday-kahf.mp3",
            mimeType: "audio/mpeg",
            durationMs: 1931376,
            byteSize: 77256100,
            sha256: "1551ea74e07229f36bee297efa0ca8c169425bab3acf7c247e99453ffdebe6b4",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "muhammad-alshara",
    reviewStatus: "approved",
    reviewNotes: "Local test version.",
    reviewedBy: "Tester",
    reviewedAt: "2026-08-29T00:00:00.000Z",
    version: 1,
  },
  "evening-e-hm-76a": {
    id: "evening-e-hm-76a",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "قُلْ هُوَ ٱللَّهُ أَحَدٌ ﴿١﴾ ٱللَّهُ ٱلصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُولَدْ ﴿٣﴾ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ ﴿٤﴾",
    normalizedTextHash: "arabic-v1-a1ccb7894c44de94",
    segments: [
      {
        id: "evening-e-hm-76a-segment-1",
        order: 1,
        transcriptArabic:
          "قُلْ هُوَ ٱللَّهُ أَحَدٌ ﴿١﴾ ٱللَّهُ ٱلصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُولَدْ ﴿٣﴾ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ ﴿٤﴾",
        normalizedTranscriptHash: "arabic-v1-a1ccb7894c44de94",
        variants: [
          {
            id: "evening-e-hm-76a-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-76a.wav",
            mimeType: "audio/wav",
            durationMs: 109032,
            byteSize: 1744556,
            sha256: "7edc735f78d45d52592f42edd858314317257b75b63f552b180702d5ef682198",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-76b": {
    id: "evening-e-hm-76b",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ﴿١﴾ مِن شَرِّ مَا خَلَقَ ﴿٢﴾ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ﴿٣﴾ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ ﴿٤﴾ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ ﴿٥﴾",
    normalizedTextHash: "arabic-v1-6866bb11b4c808e3",
    segments: [
      {
        id: "evening-e-hm-76b-segment-1",
        order: 1,
        transcriptArabic:
          "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ﴿١﴾ مِن شَرِّ مَا خَلَقَ ﴿٢﴾ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ﴿٣﴾ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ ﴿٤﴾ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ ﴿٥﴾",
        normalizedTranscriptHash: "arabic-v1-6866bb11b4c808e3",
        variants: [
          {
            id: "evening-e-hm-76b-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-76b.wav",
            mimeType: "audio/wav",
            durationMs: 169740,
            byteSize: 2715884,
            sha256: "4cc4775c176cb74c1ad551ef7769a9f3858c7a6b76d1f130122f7525578ee3ba",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-76c": {
    id: "evening-e-hm-76c",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ﴿١﴾ مَلِكِ ٱلنَّاسِ ﴿٢﴾ إِلَٰهِ ٱلنَّاسِ ﴿٣﴾ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ﴿٤﴾ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ﴿٥﴾ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ ﴿٦﴾",
    normalizedTextHash: "arabic-v1-33fb8cf055162a14",
    segments: [
      {
        id: "evening-e-hm-76c-segment-1",
        order: 1,
        transcriptArabic:
          "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ﴿١﴾ مَلِكِ ٱلنَّاسِ ﴿٢﴾ إِلَٰهِ ٱلنَّاسِ ﴿٣﴾ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ﴿٤﴾ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ﴿٥﴾ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ ﴿٦﴾",
        normalizedTranscriptHash: "arabic-v1-33fb8cf055162a14",
        variants: [
          {
            id: "evening-e-hm-76c-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-76c.wav",
            mimeType: "audio/wav",
            durationMs: 222240,
            byteSize: 3555884,
            sha256: "2b3f9907fb7a2ce2d35641b18506cf3a0ed86e1ad715a5835e14b21b2164c1b6",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-77e": {
    id: "evening-e-hm-77e",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ. رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا. رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ. رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ.",
    normalizedTextHash: "arabic-v1-f4ad9fbd03e97e88",
    segments: [
      {
        id: "evening-e-hm-77e-segment-1",
        order: 1,
        transcriptArabic:
          "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ. رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا. رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ. رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ.",
        normalizedTranscriptHash: "arabic-v1-f4ad9fbd03e97e88",
        variants: [
          {
            id: "evening-e-hm-77e-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-77e.wav",
            mimeType: "audio/wav",
            durationMs: 328920,
            byteSize: 5262764,
            sha256: "6e404ac58dccfc4e3ecd5132654cf820930598ad87f8a1fc95672f9a0278f859",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-78e": {
    id: "evening-e-hm-78e",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ.",
    normalizedTextHash: "arabic-v1-0a93330a86bddd19",
    segments: [
      {
        id: "evening-e-hm-78e-segment-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ.",
        normalizedTranscriptHash: "arabic-v1-0a93330a86bddd19",
        variants: [
          {
            id: "evening-e-hm-78e-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-78e.wav",
            mimeType: "audio/wav",
            durationMs: 77280,
            byteSize: 1236524,
            sha256: "31bf23f648f2f43d84f5854f795958a42fab979d458137024d29641b1333c52d",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-79": {
    id: "evening-e-hm-79",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي، فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ.",
    normalizedTextHash: "arabic-v1-4e506d770dd76d2a",
    segments: [
      {
        id: "evening-e-hm-79-segment-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي، فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ.",
        normalizedTranscriptHash: "arabic-v1-4e506d770dd76d2a",
        variants: [
          {
            id: "evening-e-hm-79-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-79.wav",
            mimeType: "audio/wav",
            durationMs: 225960,
            byteSize: 3615404,
            sha256: "1ab7482ff6c4a17e5c0bad8e22ff2da637798fd7f4bcbbac673449de9b4c8e02",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-80e": {
    id: "evening-e-hm-80e",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ، وَأُشْهِدُ حَمَلَةَ عَرْشِكَ، وَمَلاَئِكَتَكَ، وَجَمِيعَ خَلْقِكَ، أَنَّكَ أَنْتَ اللَّهُ لاَ إِلَهَ إِلاَّ أَنْتَ وَحْدَكَ لاَ شَرِيكَ لَكَ، وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ.",
    normalizedTextHash: "arabic-v1-f01c4cf71d01146a",
    segments: [
      {
        id: "evening-e-hm-80e-segment-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ، وَأُشْهِدُ حَمَلَةَ عَرْشِكَ، وَمَلاَئِكَتَكَ، وَجَمِيعَ خَلْقِكَ، أَنَّكَ أَنْتَ اللَّهُ لاَ إِلَهَ إِلاَّ أَنْتَ وَحْدَكَ لاَ شَرِيكَ لَكَ، وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ.",
        normalizedTranscriptHash: "arabic-v1-f01c4cf71d01146a",
        variants: [
          {
            id: "evening-e-hm-80e-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-80e.wav",
            mimeType: "audio/wav",
            durationMs: 150552,
            byteSize: 2408876,
            sha256: "507d2d37584fe170e97a2c8d77299332671babcf366faf7bb933cd408ab4dda8",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-81e": {
    id: "evening-e-hm-81e",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ، أَوْ بِأَحَدٍ مِنْ خَلْقِكَ، فَمِنْكَ وَحْدَكَ لاَ شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ.",
    normalizedTextHash: "arabic-v1-8f134325a3382f70",
    segments: [
      {
        id: "evening-e-hm-81e-segment-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ، أَوْ بِأَحَدٍ مِنْ خَلْقِكَ، فَمِنْكَ وَحْدَكَ لاَ شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ.",
        normalizedTranscriptHash: "arabic-v1-8f134325a3382f70",
        variants: [
          {
            id: "evening-e-hm-81e-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-81e.wav",
            mimeType: "audio/wav",
            durationMs: 104820,
            byteSize: 1677164,
            sha256: "3bbb5dfd039aa761cd182ac00ec9ec779a9faf70fdd72c33ca4ec43afb891586",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-82": {
    id: "evening-e-hm-82",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لاَ إِلَهَ إِلاَّ أَنْتَ. اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لاَ إِلَهَ إِلاَّ أَنْتَ.",
    normalizedTextHash: "arabic-v1-d16702927b4a9fe3",
    segments: [
      {
        id: "evening-e-hm-82-segment-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لاَ إِلَهَ إِلاَّ أَنْتَ. اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لاَ إِلَهَ إِلاَّ أَنْتَ.",
        normalizedTranscriptHash: "arabic-v1-d16702927b4a9fe3",
        variants: [
          {
            id: "evening-e-hm-82-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-82.wav",
            mimeType: "audio/wav",
            durationMs: 171720,
            byteSize: 2747564,
            sha256: "b03271176fc9ebf7259f370e286f32b955272c63b6349695353d9589c5020a2e",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-83": {
    id: "evening-e-hm-83",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "حَسْبِيَ اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ.",
    normalizedTextHash: "arabic-v1-07e2a27e31f0ec4c",
    segments: [
      {
        id: "evening-e-hm-83-segment-1",
        order: 1,
        transcriptArabic:
          "حَسْبِيَ اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ.",
        normalizedTranscriptHash: "arabic-v1-07e2a27e31f0ec4c",
        variants: [
          {
            id: "evening-e-hm-83-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-83.wav",
            mimeType: "audio/wav",
            durationMs: 69300,
            byteSize: 1108844,
            sha256: "e446c6b95cd2591e69f6e7119912854ff07a9b05359c988ba15f646adeb88339",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-84": {
    id: "evening-e-hm-84",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ. اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي. اللَّهُمَّ اسْتُرْ عَوْرَاتِي، وَآمِنْ رَوْعَاتِي. اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ، وَمِنْ خَلْفِي، وَعَنْ يَمِينِي، وَعَنْ شِمَالِي، وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي.",
    normalizedTextHash: "arabic-v1-d0befc8354f283c4",
    segments: [
      {
        id: "evening-e-hm-84-segment-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ. اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي. اللَّهُمَّ اسْتُرْ عَوْرَاتِي، وَآمِنْ رَوْعَاتِي. اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ، وَمِنْ خَلْفِي، وَعَنْ يَمِينِي، وَعَنْ شِمَالِي، وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي.",
        normalizedTranscriptHash: "arabic-v1-d0befc8354f283c4",
        variants: [
          {
            id: "evening-e-hm-84-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-84.wav",
            mimeType: "audio/wav",
            durationMs: 256680,
            byteSize: 4106924,
            sha256: "2bfd365072b5083681f3395c02c05dc6e352388f3e15e0c0e331115f045c1a8b",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-85": {
    id: "evening-e-hm-85",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ، فَاطِرَ السَّمَاوَاتِ وَالأَرْضِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ أَنْتَ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ، وَأَنْ أَقْتَرِفَ عَلَى نَفْسِي سُوءًا، أَوْ أَجُرَّهُ إِلَى مُسْلِمٍ.",
    normalizedTextHash: "arabic-v1-4e2146a65189281a",
    segments: [
      {
        id: "evening-e-hm-85-segment-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ، فَاطِرَ السَّمَاوَاتِ وَالأَرْضِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ أَنْتَ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ، وَأَنْ أَقْتَرِفَ عَلَى نَفْسِي سُوءًا، أَوْ أَجُرَّهُ إِلَى مُسْلِمٍ.",
        normalizedTranscriptHash: "arabic-v1-4e2146a65189281a",
        variants: [
          {
            id: "evening-e-hm-85-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-85.wav",
            mimeType: "audio/wav",
            durationMs: 202980,
            byteSize: 3247724,
            sha256: "70dd7e4d2169e82e97784a0dab4d0a605037f05fb62fa96c8985eb300332778a",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-86": {
    id: "evening-e-hm-86",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ.",
    normalizedTextHash: "arabic-v1-3396778f42f9865c",
    segments: [
      {
        id: "evening-e-hm-86-segment-1",
        order: 1,
        transcriptArabic:
          "بِسْمِ اللَّهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ.",
        normalizedTranscriptHash: "arabic-v1-3396778f42f9865c",
        variants: [
          {
            id: "evening-e-hm-86-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-86.wav",
            mimeType: "audio/wav",
            durationMs: 83772,
            byteSize: 1340396,
            sha256: "1d7e59984c7a74dd8819fbf3add398a6f56762fe40b71e3f53ed228c662fcd47",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-87": {
    id: "evening-e-hm-87",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلاَمِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا.",
    normalizedTextHash: "arabic-v1-3ac1ef8f8cedba64",
    segments: [
      {
        id: "evening-e-hm-87-segment-1",
        order: 1,
        transcriptArabic: "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلاَمِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا.",
        normalizedTranscriptHash: "arabic-v1-3ac1ef8f8cedba64",
        variants: [
          {
            id: "evening-e-hm-87-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-87.wav",
            mimeType: "audio/wav",
            durationMs: 77292,
            byteSize: 1236716,
            sha256: "925bbeb88c73a47f39a41967b24682eacdeeeaf3700d0d889de36b15f0a66065",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-88": {
    id: "evening-e-hm-88",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "يَا حَيُّ يَا قَيُّومُ، بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلاَ تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ.",
    normalizedTextHash: "arabic-v1-9779a5e922187b01",
    segments: [
      {
        id: "evening-e-hm-88-segment-1",
        order: 1,
        transcriptArabic:
          "يَا حَيُّ يَا قَيُّومُ، بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلاَ تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ.",
        normalizedTranscriptHash: "arabic-v1-9779a5e922187b01",
        variants: [
          {
            id: "evening-e-hm-88-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-88.wav",
            mimeType: "audio/wav",
            durationMs: 98040,
            byteSize: 1568684,
            sha256: "fe398cf73425959d341c97fc5aaaaa3aa37df862a230fdf64857c371c43f7fad",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-89e": {
    id: "evening-e-hm-89e",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ رَبِّ الْعَالَمِينَ. اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذِهِ اللَّيْلَةِ: فَتْحَهَا، وَنَصْرَهَا، وَنُورَهَا، وَبَرَكَتَهَا، وَهُدَاهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِيهَا وَشَرِّ مَا بَعْدَهَا.",
    normalizedTextHash: "arabic-v1-59cd9921227220f8",
    segments: [
      {
        id: "evening-e-hm-89e-segment-1",
        order: 1,
        transcriptArabic:
          "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ رَبِّ الْعَالَمِينَ. اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذِهِ اللَّيْلَةِ: فَتْحَهَا، وَنَصْرَهَا، وَنُورَهَا، وَبَرَكَتَهَا، وَهُدَاهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِيهَا وَشَرِّ مَا بَعْدَهَا.",
        normalizedTranscriptHash: "arabic-v1-59cd9921227220f8",
        variants: [
          {
            id: "evening-e-hm-89e-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-89e.wav",
            mimeType: "audio/wav",
            durationMs: 175080,
            byteSize: 2801324,
            sha256: "fa630fa7f5db2615d61951124c997adb432fea4e4e3ba42398b2d9502ac5d2cf",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-90e": {
    id: "evening-e-hm-90e",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "أَمْسَيْنَا عَلَى فِطْرَةِ الإِسْلاَمِ، وَعَلَى كَلِمَةِ الإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ ﷺ، وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ، حَنِيفًا مُسْلِمًا، وَمَا كَانَ مِنَ الْمُشْرِكِينَ.",
    normalizedTextHash: "arabic-v1-0dff60d64991d0c2",
    segments: [
      {
        id: "evening-e-hm-90e-segment-1",
        order: 1,
        transcriptArabic:
          "أَمْسَيْنَا عَلَى فِطْرَةِ الإِسْلاَمِ، وَعَلَى كَلِمَةِ الإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ ﷺ، وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ، حَنِيفًا مُسْلِمًا، وَمَا كَانَ مِنَ الْمُشْرِكِينَ.",
        normalizedTranscriptHash: "arabic-v1-0dff60d64991d0c2",
        variants: [
          {
            id: "evening-e-hm-90e-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-90e.wav",
            mimeType: "audio/wav",
            durationMs: 158160,
            byteSize: 2530604,
            sha256: "8d5728735ad62b89b8d7814976730a1f781f74866d090c2a8b31d8e06dd87902",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-91": {
    id: "evening-e-hm-91",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ.",
    normalizedTextHash: "arabic-v1-f37d0886dde3188a",
    segments: [
      {
        id: "evening-e-hm-91-segment-1",
        order: 1,
        transcriptArabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ.",
        normalizedTranscriptHash: "arabic-v1-f37d0886dde3188a",
        variants: [
          {
            id: "evening-e-hm-91-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-91.wav",
            mimeType: "audio/wav",
            durationMs: 28680,
            byteSize: 458924,
            sha256: "d8a955ce62ce89037c4e61bbf5d686e75205c7e44f9577cf2c7efc2aea4b75ed",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-92": {
    id: "evening-e-hm-92",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ.",
    normalizedTextHash: "arabic-v1-5bec6983c26d3505",
    segments: [
      {
        id: "evening-e-hm-92-segment-1",
        order: 1,
        transcriptArabic:
          "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ.",
        normalizedTranscriptHash: "arabic-v1-5bec6983c26d3505",
        variants: [
          {
            id: "evening-e-hm-92-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-92.wav",
            mimeType: "audio/wav",
            durationMs: 81240,
            byteSize: 1299884,
            sha256: "628e9e61ced01f1fd73d75a6f25c2a10498e8877e55ba54392680e1ae5e92ead",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-96": {
    id: "evening-e-hm-96",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ.",
    normalizedTextHash: "arabic-v1-663a9cdf8d02bb6a",
    segments: [
      {
        id: "evening-e-hm-96-segment-1",
        order: 1,
        transcriptArabic: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ.",
        normalizedTranscriptHash: "arabic-v1-663a9cdf8d02bb6a",
        variants: [
          {
            id: "evening-e-hm-96-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-96.wav",
            mimeType: "audio/wav",
            durationMs: 31320,
            byteSize: 501164,
            sha256: "4d8202df6bc5801c9a272bee31152c9871806e41ff91a671033b6953854d93c0",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-97": {
    id: "evening-e-hm-97",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ.",
    normalizedTextHash: "arabic-v1-0644ebe1e31ee746",
    segments: [
      {
        id: "evening-e-hm-97-segment-1",
        order: 1,
        transcriptArabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ.",
        normalizedTranscriptHash: "arabic-v1-0644ebe1e31ee746",
        variants: [
          {
            id: "evening-e-hm-97-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-97.wav",
            mimeType: "audio/wav",
            durationMs: 50520,
            byteSize: 808364,
            sha256: "1e2542ef60a7ff2b7926cd662dd533add800b9faf74c85fc2e63b30c5267cb22",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-98": {
    id: "evening-e-hm-98",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ.",
    normalizedTextHash: "arabic-v1-022097dd98deb966",
    segments: [
      {
        id: "evening-e-hm-98-segment-1",
        order: 1,
        transcriptArabic: "اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ.",
        normalizedTranscriptHash: "arabic-v1-022097dd98deb966",
        variants: [
          {
            id: "evening-e-hm-98-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-98.wav",
            mimeType: "audio/wav",
            durationMs: 38400,
            byteSize: 614444,
            sha256: "ba29d446dc30fd44b9a43475700a711843d56299ad5e68c1a6c1115bb1ca2750",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "evening-e-hm-75a": {
    id: "evening-e-hm-75a",
    titleArabic: "أذكار المساء",
    titleEnglish: "Evening Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "الْحَمْدُ لِلَّهِ وَحْدَهُ، وَالصَّلاَةُ وَالسَّلاَمُ عَلَى مَنْ لاَ نَبِيَّ بَعْدَهُ",
    normalizedTextHash: "arabic-v1-9731a937ee9198b8",
    segments: [
      {
        id: "evening-e-hm-75a-segment-1",
        order: 1,
        transcriptArabic: "الْحَمْدُ لِلَّهِ وَحْدَهُ، وَالصَّلاَةُ وَالسَّلاَمُ عَلَى مَنْ لاَ نَبِيَّ بَعْدَهُ",
        normalizedTranscriptHash: "arabic-v1-9731a937ee9198b8",
        variants: [
          {
            id: "evening-e-hm-75a-voice-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "Abdullah Muhammad",
            relativePath: "azkar/evening/abdullah-muhammad/v1/e-hm-75a.wav",
            mimeType: "audio/wav",
            durationMs: 437652,
            byteSize: 7002476,
            sha256: "69796ece483837a9e67b8512768fe3fb74964029b4100b433e424f04ba098512",
            sourceId: "internal-upload",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewNotes: "Evening Azkar uploaded directly as WAV.",
    reviewedBy: "System",
    reviewedAt: new Date().toISOString(),
    version: 1,
  },
  "s-hm-108": {
    id: "s-hm-108",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا، وَكَفَانَا، وَآوَانَا، فَكَمْ مِمَّنْ لَا كَافِيَ لَهُ وَلَا مُؤْوِيَ.",
    normalizedTextHash: "arabic-v1-6d0d5bce7e83bacd",
    segments: [
      {
        id: "s-hm-108-1",
        order: 1,
        transcriptArabic:
          "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا، وَكَفَانَا، وَآوَانَا، فَكَمْ مِمَّنْ لَا كَافِيَ لَهُ وَلَا مُؤْوِيَ.",
        normalizedTranscriptHash: "arabic-v1-6d0d5bce7e83bacd",
        variants: [
          {
            id: "s-hm-108-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-108.mp3",
            mimeType: "audio/mpeg",
            durationMs: 14424,
            byteSize: 576960,
            sha256: "e6e1cc6be223a99a9e8f42a147987cf25063bb6a65d12976ed40c8db5ae3dddb",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-106-alhamdulillah": {
    id: "s-hm-106-alhamdulillah",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "الْحَمْدُ لِلَّهِ",
    normalizedTextHash: "arabic-v1-c7c5262d50ab3434",
    segments: [
      {
        id: "s-hm-106-alhamdulillah-1",
        order: 1,
        transcriptArabic: "الْحَمْدُ لِلَّهِ",
        normalizedTranscriptHash: "arabic-v1-c7c5262d50ab3434",
        variants: [
          {
            id: "s-hm-106-alhamdulillah-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-106-alhamdulillah.mp3",
            mimeType: "audio/mpeg",
            durationMs: 12528,
            byteSize: 501120,
            sha256: "ccbdaeaeab307a9293f416f6ffc9081381541665b196f8e6d1b59cfe4613d1f2",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-106-allahu-akbar": {
    id: "s-hm-106-allahu-akbar",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "اللَّهُ أَكْبَرُ",
    normalizedTextHash: "arabic-v1-c0b8dab3c44bf324",
    segments: [
      {
        id: "s-hm-106-allahu-akbar-1",
        order: 1,
        transcriptArabic: "اللَّهُ أَكْبَرُ",
        normalizedTranscriptHash: "arabic-v1-c0b8dab3c44bf324",
        variants: [
          {
            id: "s-hm-106-allahu-akbar-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-106-allahu-akbar.mp3",
            mimeType: "audio/mpeg",
            durationMs: 10680,
            byteSize: 427200,
            sha256: "17171b84b34e8c60631d6e1ddd481dea71ee49da58339f88440d423756c13976",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-111": {
    id: "s-hm-111",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ، وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ.",
    normalizedTextHash: "arabic-v1-8931c813e0d554c5",
    segments: [
      {
        id: "s-hm-111-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ، وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ.",
        normalizedTranscriptHash: "arabic-v1-8931c813e0d554c5",
        variants: [
          {
            id: "s-hm-111-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-111.mp3",
            mimeType: "audio/mpeg",
            durationMs: 37008,
            byteSize: 1480320,
            sha256: "8c8fe6eea2627fbf6dd541b3041b03d32e21abd46c1f066f5ca3c235db69b18c",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-107": {
    id: "s-hm-107",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "اللَّهُمَّ رَبَّ السَّمَاوَاتِ السَّبْعِ وَرَبَّ الْعَرْشِ الْعَظِيمِ، رَبَّنَا وَرَبَّ كُلِّ شَيْءٍ، فَالِقَ الْحَبِّ وَالنَّوَى، وَمُنْزِلَ التَّوْرَاةِ وَالْإِنْجِيلِ وَالْفُرْقَانِ، أَعُوذُ بِكَ مِنْ شَرِّ كُلِّ شَيْءٍ أَنْتَ آخِذٌ بِنَاصِيَتِهِ. اللَّهُمَّ أَنْتَ الْأَوَّلُ فَلَيْسَ قَبْلَكَ شَيْءٌ، وَأَنْتَ الْآخِرُ فَلَيْسَ بَعْدَكَ شَيْءٌ، وَأَنْتَ الظَّاهِرُ فَلَيْسَ فَوْقَكَ شَيْءٌ، وَأَنْتَ الْبَاطِنُ فَلَيْسَ دُونَكَ شَيْءٌ، اقْضِ عَنَّا الدَّيْنَ، وَأَغْنِنَا مِنَ الْفَقْرِ.",
    normalizedTextHash: "arabic-v1-0ec13e1f0f41c748",
    segments: [
      {
        id: "s-hm-107-1",
        order: 1,
        transcriptArabic:
          "اللَّهُمَّ رَبَّ السَّمَاوَاتِ السَّبْعِ وَرَبَّ الْعَرْشِ الْعَظِيمِ، رَبَّنَا وَرَبَّ كُلِّ شَيْءٍ، فَالِقَ الْحَبِّ وَالنَّوَى، وَمُنْزِلَ التَّوْرَاةِ وَالْإِنْجِيلِ وَالْفُرْقَانِ، أَعُوذُ بِكَ مِنْ شَرِّ كُلِّ شَيْءٍ أَنْتَ آخِذٌ بِنَاصِيَتِهِ. اللَّهُمَّ أَنْتَ الْأَوَّلُ فَلَيْسَ قَبْلَكَ شَيْءٌ، وَأَنْتَ الْآخِرُ فَلَيْسَ بَعْدَكَ شَيْءٌ، وَأَنْتَ الظَّاهِرُ فَلَيْسَ فَوْقَكَ شَيْءٌ، وَأَنْتَ الْبَاطِنُ فَلَيْسَ دُونَكَ شَيْءٌ، اقْضِ عَنَّا الدَّيْنَ، وَأَغْنِنَا مِنَ الْفَقْرِ.",
        normalizedTranscriptHash: "arabic-v1-0ec13e1f0f41c748",
        variants: [
          {
            id: "s-hm-107-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-107.mp3",
            mimeType: "audio/mpeg",
            durationMs: 60888,
            byteSize: 2435520,
            sha256: "837451a0fd355e6fb8f374d923584c63a5ca82f00e21499a3044b3a19d33ddb3",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-104": {
    id: "s-hm-104",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ.",
    normalizedTextHash: "arabic-v1-1ce4e44a241072a0",
    segments: [
      {
        id: "s-hm-104-1",
        order: 1,
        transcriptArabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ.",
        normalizedTranscriptHash: "arabic-v1-1ce4e44a241072a0",
        variants: [
          {
            id: "s-hm-104-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-104.mp3",
            mimeType: "audio/mpeg",
            durationMs: 6480,
            byteSize: 259200,
            sha256: "26b3c48415a065b7c4a10a1fc8ff31e16af5a1541a0ae78979288c84653ad503",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-105": {
    id: "s-hm-105",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا.",
    normalizedTextHash: "arabic-v1-acef5633a8a68975",
    segments: [
      {
        id: "s-hm-105-1",
        order: 1,
        transcriptArabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا.",
        normalizedTranscriptHash: "arabic-v1-acef5633a8a68975",
        variants: [
          {
            id: "s-hm-105-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-105.mp3",
            mimeType: "audio/mpeg",
            durationMs: 5400,
            byteSize: 216000,
            sha256: "ff0272420787eaeb13a4ce909120a78f83c87a2efb5809ff22a2c8138aeab038",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-102": {
    id: "s-hm-102",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText:
      "بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، فَإِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ.",
    normalizedTextHash: "arabic-v1-481ac0b858dc8875",
    segments: [
      {
        id: "s-hm-102-1",
        order: 1,
        transcriptArabic:
          "بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، فَإِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ.",
        normalizedTranscriptHash: "arabic-v1-481ac0b858dc8875",
        variants: [
          {
            id: "s-hm-102-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-102.mp3",
            mimeType: "audio/mpeg",
            durationMs: 19056,
            byteSize: 762240,
            sha256: "493f14b4d23c169bdbeaa11f89c088bcec568cee2732b33af5480adc2060c64d",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-106-subhanallah": {
    id: "s-hm-106-subhanallah",
    titleArabic: "أذكار النوم",
    titleEnglish: "Before Sleep Azkar",
    contentKind: "dua",
    kind: "single",
    canonicalArabicText: "سُبْحَانَ اللَّهِ",
    normalizedTextHash: "arabic-v1-6f5aed765decb8c2",
    segments: [
      {
        id: "s-hm-106-subhanallah-1",
        order: 1,
        transcriptArabic: "سُبْحَانَ اللَّهِ",
        normalizedTranscriptHash: "arabic-v1-6f5aed765decb8c2",
        variants: [
          {
            id: "s-hm-106-subhanallah-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-106-subhanallah.mp3",
            mimeType: "audio/mpeg",
            durationMs: 11232,
            byteSize: 449280,
            sha256: "594893c784164a5d3efbca0071f37122ddb8c278da09a5d26a330ed47d486215",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-110b": {
    id: "s-hm-110b",
    titleArabic: "الْمُلْك",
    titleEnglish: "Al-Mulk",
    contentKind: "quran",
    kind: "single",
    canonicalArabicText:
      "تَبَٰرَكَ ٱلَّذِى بِيَدِهِ ٱلْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌ ﴿١﴾ ٱلَّذِى خَلَقَ ٱلْمَوْتَ وَٱلْحَيَوٰةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًۭا ۚ وَهُوَ ٱلْعَزِيزُ ٱلْغَفُورُ ﴿٢﴾ ٱلَّذِى خَلَقَ سَبْعَ سَمَٰوَٰتٍۢ طِبَاقًۭا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَٰنِ مِن تَفَٰوُتٍۢ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍۢ ﴿٣﴾ ثُمَّ ٱرْجِعِ ٱلْبَصَرَ كَرَّتَيْنِ يَنقَلِبْ إِلَيْكَ ٱلْبَصَرُ خَاسِئًۭا وَهُوَ حَسِيرٌۭ ﴿٤﴾ وَلَقَدْ زَيَّنَّا ٱلسَّمَآءَ ٱلدُّنْيَا بِمَصَٰبِيحَ وَجَعَلْنَٰهَا رُجُومًۭا لِّلشَّيَٰطِينِ ۖ وَأَعْتَدْنَا لَهُمْ عَذَابَ ٱلسَّعِيرِ ﴿٥﴾ وَلِلَّذِينَ كَفَرُوا۟ بِرَبِّهِمْ عَذَابُ جَهَنَّمَ ۖ وَبِئْسَ ٱلْمَصِيرُ ﴿٦﴾ إِذَآ أُلْقُوا۟ فِيهَا سَمِعُوا۟ لَهَا شَهِيقًۭا وَهِىَ تَفُورُ ﴿٧﴾ تَكَادُ تَمَيَّزُ مِنَ ٱلْغَيْظِ ۖ كُلَّمَآ أُلْقِىَ فِيهَا فَوْجٌۭ سَأَلَهُمْ خَزَنَتُهَآ أَلَمْ يَأْتِكُمْ نَذِيرٌۭ ﴿٨﴾ قَالُوا۟ بَلَىٰ قَدْ جَآءَنَا نَذِيرٌۭ فَكَذَّبْنَا وَقُلْنَا مَا نَزَّلَ ٱللَّهُ مِن شَىْءٍ إِنْ أَنتُمْ إِلَّا فِى ضَلَٰلٍۢ كَبِيرٍۢ ﴿٩﴾ وَقَالُوا۟ لَوْ كُنَّا نَسْمَعُ أَوْ نَعْقِلُ مَا كُنَّا فِىٓ أَصْحَٰبِ ٱلسَّعِيرِ ﴿١٠﴾ فَٱعْتَرَفُوا۟ بِذَنۢبِهِمْ فَسُحْقًۭا لِّأَصْحَٰبِ ٱلسَّعِيرِ ﴿١١﴾ إِنَّ ٱلَّذِينَ يَخْشَوْنَ رَبَّهُم بِٱلْغَيْبِ لَهُم مَّغْفِرَةٌۭ وَأَجْرٌۭ كَبِيرٌۭ ﴿١٢﴾ وَأَسِرُّوا۟ قَوْلَكُمْ أَوِ ٱجْهَرُوا۟ بِهِۦٓ ۖ إِنَّهُۥ عَلِيمٌۢ بِذَاتِ ٱلصُّدُورِ ﴿١٣﴾ أَلَا يَعْلَمُ مَنْ خَلَقَ وَهُوَ ٱللَّطِيفُ ٱلْخَبِيرُ ﴿١٤﴾ هُوَ ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ ذَلُولًۭا فَٱمْشُوا۟ فِى مَنَاكِبِهَا وَكُلُوا۟ مِن رِّزْقِهِۦ ۖ وَإِلَيْهِ ٱلنُّشُورُ ﴿١٥﴾ ءَأَمِنتُم مَّن فِى ٱلسَّمَآءِ أَن يَخْسِفَ بِكُمُ ٱلْأَرْضَ فَإِذَا هِىَ تَمُورُ ﴿١٦﴾ أَمْ أَمِنتُم مَّن فِى ٱلسَّمَآءِ أَن يُرْسِلَ عَلَيْكُمْ حَاصِبًۭا ۖ فَسَتَعْلَمُونَ كَيْفَ نَذِيرِ ﴿١٧﴾ وَلَقَدْ كَذَّبَ ٱلَّذِينَ مِن قَبْلِهِمْ فَكَيْفَ كَانَ نَكِيرِ ﴿١٨﴾ أَوَلَمْ يَرَوْا۟ إِلَى ٱلطَّيْرِ فَوْقَهُمْ صَٰٓفَّٰتٍۢ وَيَقْبِضْنَ ۚ مَا يُمْسِكُهُنَّ إِلَّا ٱلرَّحْمَٰنُ ۚ إِنَّهُۥ بِكُلِّ شَىْءٍۭ بَصِيرٌ ﴿١٩﴾ أَمَّنْ هَٰذَا ٱلَّذِى هُوَ جُندٌۭ لَّكُمْ يَنصُرُكُم مِّن دُونِ ٱلرَّحْمَٰنِ ۚ إِنِ ٱلْكَٰفِرُونَ إِلَّا فِى غُرُورٍ ﴿٢٠﴾ أَمَّنْ هَٰذَا ٱلَّذِى يَرْزُقُكُمْ إِنْ أَمْسَكَ رِزْقَهُۥ ۚ بَل لَّجُّوا۟ فِى عُتُوٍّۢ وَنُفُورٍ ﴿٢١﴾ أَفَمَن يَمْشِى مُكِبًّا عَلَىٰ وَجْهِهِۦٓ أَهْدَىٰٓ أَمَّن يَمْشِى سَوِيًّا عَلَىٰ صِرَٰطٍۢ مُّسْتَقِيمٍۢ ﴿٢٢﴾ قُلْ هُوَ ٱلَّذِىٓ أَنشَأَكُمْ وَجَعَلَ لَكُمُ ٱلسَّمْعَ وَٱلْأَبْصَٰرَ وَٱلْأَفْـِٔدَةَ ۖ قَلِيلًۭا مَّا تَشْكُرُونَ ﴿٢٣﴾ قُلْ هُوَ ٱلَّذِى ذَرَأَكُمْ فِى ٱلْأَرْضِ وَإِلَيْهِ تُحْشَرُونَ ﴿٢٤﴾ وَيَقُولُونَ مَتَىٰ هَٰذَا ٱلْوَعْدُ إِن كُنتُمْ صَٰدِقِينَ ﴿٢٥﴾ قُلْ إِنَّمَا ٱلْعِلْمُ عِندَ ٱللَّهِ وَإِنَّمَآ أَنَا۠ نَذِيرٌۭ مُّبِينٌۭ ﴿٢٦﴾ فَلَمَّا رَأَوْهُ زُلْفَةًۭ سِيٓـَٔتْ وُجُوهُ ٱلَّذِينَ كَفَرُوا۟ وَقِيلَ هَٰذَا ٱلَّذِى كُنتُم بِهِۦ تَدَّعُونَ ﴿٢٧﴾ قُلْ أَرَءَيْتُمْ إِنْ أَهْلَكَنِىَ ٱللَّهُ وَمَن مَّعِىَ أَوْ رَحِمَنَا فَمَن يُجِيرُ ٱلْكَٰفِرِينَ مِنْ عَذَابٍ أَلِيمٍۢ ﴿٢٨﴾ قُلْ هُوَ ٱلرَّحْمَٰنُ ءَامَنَّا بِهِۦ وَعَلَيْهِ تَوَكَّلْنَا ۖ فَسَتَعْلَمُونَ مَنْ هُوَ فِى ضَلَٰلٍۢ مُّبِينٍۢ ﴿٢٩﴾ قُلْ أَرَءَيْتُمْ إِنْ أَصْبَحَ مَآؤُكُمْ غَوْرًۭا فَمَن يَأْتِيكُم بِمَآءٍۢ مَّعِينٍۭ ﴿٣٠﴾",
    normalizedTextHash: "arabic-v1-c661c0e0c3af6d20",
    segments: [
      {
        id: "s-hm-110b-1",
        order: 1,
        transcriptArabic:
          "تَبَٰرَكَ ٱلَّذِى بِيَدِهِ ٱلْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌ ﴿١﴾ ٱلَّذِى خَلَقَ ٱلْمَوْتَ وَٱلْحَيَوٰةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًۭا ۚ وَهُوَ ٱلْعَزِيزُ ٱلْغَفُورُ ﴿٢﴾ ٱلَّذِى خَلَقَ سَبْعَ سَمَٰوَٰتٍۢ طِبَاقًۭا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَٰنِ مِن تَفَٰوُتٍۢ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍۢ ﴿٣﴾ ثُمَّ ٱرْجِعِ ٱلْبَصَرَ كَرَّتَيْنِ يَنقَلِبْ إِلَيْكَ ٱلْبَصَرُ خَاسِئًۭا وَهُوَ حَسِيرٌۭ ﴿٤﴾ وَلَقَدْ زَيَّنَّا ٱلسَّمَآءَ ٱلدُّنْيَا بِمَصَٰبِيحَ وَجَعَلْنَٰهَا رُجُومًۭا لِّلشَّيَٰطِينِ ۖ وَأَعْتَدْنَا لَهُمْ عَذَابَ ٱلسَّعِيرِ ﴿٥﴾ وَلِلَّذِينَ كَفَرُوا۟ بِرَبِّهِمْ عَذَابُ جَهَنَّمَ ۖ وَبِئْسَ ٱلْمَصِيرُ ﴿٦﴾ إِذَآ أُلْقُوا۟ فِيهَا سَمِعُوا۟ لَهَا شَهِيقًۭا وَهِىَ تَفُورُ ﴿٧﴾ تَكَادُ تَمَيَّزُ مِنَ ٱلْغَيْظِ ۖ كُلَّمَآ أُلْقِىَ فِيهَا فَوْجٌۭ سَأَلَهُمْ خَزَنَتُهَآ أَلَمْ يَأْتِكُمْ نَذِيرٌۭ ﴿٨﴾ قَالُوا۟ بَلَىٰ قَدْ جَآءَنَا نَذِيرٌۭ فَكَذَّبْنَا وَقُلْنَا مَا نَزَّلَ ٱللَّهُ مِن شَىْءٍ إِنْ أَنتُمْ إِلَّا فِى ضَلَٰلٍۢ كَبِيرٍۢ ﴿٩﴾ وَقَالُوا۟ لَوْ كُنَّا نَسْمَعُ أَوْ نَعْقِلُ مَا كُنَّا فِىٓ أَصْحَٰبِ ٱلسَّعِيرِ ﴿١٠﴾ فَٱعْتَرَفُوا۟ بِذَنۢبِهِمْ فَسُحْقًۭا لِّأَصْحَٰبِ ٱلسَّعِيرِ ﴿١١﴾ إِنَّ ٱلَّذِينَ يَخْشَوْنَ رَبَّهُم بِٱلْغَيْبِ لَهُم مَّغْفِرَةٌۭ وَأَجْرٌۭ كَبِيرٌۭ ﴿١٢﴾ وَأَسِرُّوا۟ قَوْلَكُمْ أَوِ ٱجْهَرُوا۟ بِهِۦٓ ۖ إِنَّهُۥ عَلِيمٌۢ بِذَاتِ ٱلصُّدُورِ ﴿١٣﴾ أَلَا يَعْلَمُ مَنْ خَلَقَ وَهُوَ ٱللَّطِيفُ ٱلْخَبِيرُ ﴿١٤﴾ هُوَ ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ ذَلُولًۭا فَٱمْشُوا۟ فِى مَنَاكِبِهَا وَكُلُوا۟ مِن رِّزْقِهِۦ ۖ وَإِلَيْهِ ٱلنُّشُورُ ﴿١٥﴾ ءَأَمِنتُم مَّن فِى ٱلسَّمَآءِ أَن يَخْسِفَ بِكُمُ ٱلْأَرْضَ فَإِذَا هِىَ تَمُورُ ﴿١٦﴾ أَمْ أَمِنتُم مَّن فِى ٱلسَّمَآءِ أَن يُرْسِلَ عَلَيْكُمْ حَاصِبًۭا ۖ فَسَتَعْلَمُونَ كَيْفَ نَذِيرِ ﴿١٧﴾ وَلَقَدْ كَذَّبَ ٱلَّذِينَ مِن قَبْلِهِمْ فَكَيْفَ كَانَ نَكِيرِ ﴿١٨﴾ أَوَلَمْ يَرَوْا۟ إِلَى ٱلطَّيْرِ فَوْقَهُمْ صَٰٓفَّٰتٍۢ وَيَقْبِضْنَ ۚ مَا يُمْسِكُهُنَّ إِلَّا ٱلرَّحْمَٰنُ ۚ إِنَّهُۥ بِكُلِّ شَىْءٍۭ بَصِيرٌ ﴿١٩﴾ أَمَّنْ هَٰذَا ٱلَّذِى هُوَ جُندٌۭ لَّكُمْ يَنصُرُكُم مِّن دُونِ ٱلرَّحْمَٰنِ ۚ إِنِ ٱلْكَٰفِرُونَ إِلَّا فِى غُرُورٍ ﴿٢٠﴾ أَمَّنْ هَٰذَا ٱلَّذِى يَرْزُقُكُمْ إِنْ أَمْسَكَ رِزْقَهُۥ ۚ بَل لَّجُّوا۟ فِى عُتُوٍّۢ وَنُفُورٍ ﴿٢١﴾ أَفَمَن يَمْشِى مُكِبًّا عَلَىٰ وَجْهِهِۦٓ أَهْدَىٰٓ أَمَّن يَمْشِى سَوِيًّا عَلَىٰ صِرَٰطٍۢ مُّسْتَقِيمٍۢ ﴿٢٢﴾ قُلْ هُوَ ٱلَّذِىٓ أَنشَأَكُمْ وَجَعَلَ لَكُمُ ٱلسَّمْعَ وَٱلْأَبْصَٰرَ وَٱلْأَفْـِٔدَةَ ۖ قَلِيلًۭا مَّا تَشْكُرُونَ ﴿٢٣﴾ قُلْ هُوَ ٱلَّذِى ذَرَأَكُمْ فِى ٱلْأَرْضِ وَإِلَيْهِ تُحْشَرُونَ ﴿٢٤﴾ وَيَقُولُونَ مَتَىٰ هَٰذَا ٱلْوَعْدُ إِن كُنتُمْ صَٰدِقِينَ ﴿٢٥﴾ قُلْ إِنَّمَا ٱلْعِلْمُ عِندَ ٱللَّهِ وَإِنَّمَآ أَنَا۠ نَذِيرٌۭ مُّبِينٌۭ ﴿٢٦﴾ فَلَمَّا رَأَوْهُ زُلْفَةًۭ سِيٓـَٔتْ وُجُوهُ ٱلَّذِينَ كَفَرُوا۟ وَقِيلَ هَٰذَا ٱلَّذِى كُنتُم بِهِۦ تَدَّعُونَ ﴿٢٧﴾ قُلْ أَرَءَيْتُمْ إِنْ أَهْلَكَنِىَ ٱللَّهُ وَمَن مَّعِىَ أَوْ رَحِمَنَا فَمَن يُجِيرُ ٱلْكَٰفِرِينَ مِنْ عَذَابٍ أَلِيمٍۢ ﴿٢٨﴾ قُلْ هُوَ ٱلرَّحْمَٰنُ ءَامَنَّا بِهِۦ وَعَلَيْهِ تَوَكَّلْنَا ۖ فَسَتَعْلَمُونَ مَنْ هُوَ فِى ضَلَٰلٍۢ مُّبِينٍۢ ﴿٢٩﴾ قُلْ أَرَءَيْتُمْ إِنْ أَصْبَحَ مَآؤُكُمْ غَوْرًۭا فَمَن يَأْتِيكُم بِمَآءٍۢ مَّعِينٍۭ ﴿٣٠﴾",
        normalizedTranscriptHash: "arabic-v1-c661c0e0c3af6d20",
        variants: [
          {
            id: "s-hm-110b-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-110b.mp3",
            mimeType: "audio/mpeg",
            durationMs: 429264,
            byteSize: 17170560,
            sha256: "5aa6ef9f13ea737bdfdb3ebcda699ba5c1700d6d83d98f6668f4b686727a7555",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
  "s-hm-109a": {
    id: "s-hm-109a",
    titleArabic: "الْكَافِرُون",
    titleEnglish: "Al-Kafirun",
    contentKind: "quran",
    kind: "single",
    canonicalArabicText:
      "قُلْ يَٰٓأَيُّهَا ٱلْكَٰفِرُونَ ﴿١﴾ لَآ أَعْبُدُ مَا تَعْبُدُونَ ﴿٢﴾ وَلَآ أَنتُمْ عَٰبِدُونَ مَآ أَعْبُدُ ﴿٣﴾ وَلَآ أَنَا۠ عَابِدٌۭ مَّا عَبَدتُّمْ ﴿٤﴾ وَلَآ أَنتُمْ عَٰبِدُونَ مَآ أَعْبُدُ ﴿٥﴾ لَكُمْ دِينُكُمْ وَلِىَ دِينِ ﴿٦﴾",
    normalizedTextHash: "arabic-v1-bb85bb074a939fee",
    segments: [
      {
        id: "s-hm-109a-1",
        order: 1,
        transcriptArabic:
          "قُلْ يَٰٓأَيُّهَا ٱلْكَٰفِرُونَ ﴿١﴾ لَآ أَعْبُدُ مَا تَعْبُدُونَ ﴿٢﴾ وَلَآ أَنتُمْ عَٰبِدُونَ مَآ أَعْبُدُ ﴿٣﴾ وَلَآ أَنَا۠ عَابِدٌۭ مَّا عَبَدتُّمْ ﴿٤﴾ وَلَآ أَنتُمْ عَٰبِدُونَ مَآ أَعْبُدُ ﴿٥﴾ لَكُمْ دِينُكُمْ وَلِىَ دِينِ ﴿٦﴾",
        normalizedTranscriptHash: "arabic-v1-bb85bb074a939fee",
        variants: [
          {
            id: "s-hm-109a-abdullah-muhammad-v1",
            voiceId: "abdullah-muhammad",
            voiceName: "عبد الله محمد",
            relativePath: "azkar/before_sleep/abdullah-muhammad/v1/s-hm-109a.mp3",
            mimeType: "audio/mpeg",
            durationMs: 37680,
            byteSize: 1507200,
            sha256: "1f5f9b2d74775d7cbc47a021274fa784416fda0daba0cc6ef08cbcc68dcc19a0",
            sourceId: "internal-upload-abdullah-muhammad",
            reviewStatus: "approved",
          },
        ],
      },
    ],
    defaultVoiceId: "abdullah-muhammad",
    reviewStatus: "approved",
    reviewedBy: "Ahmed Mahdy",
    reviewedAt: "2026-09-13T00:00:00.000Z",
    reviewNotes: "Owner-supplied revised recording approved for the before-sleep collection.",
    version: 1,
  },
});

export const AUDIO_CATALOG: AudioCatalog = Object.freeze({
  version: AUDIO_MANIFEST_VERSION,
  sources: AUDIO_SOURCES,
  assets: AUDIO_ASSETS,
  assignments: APPROVED_AUDIO_ASSIGNMENTS,
});

import { ALL_AZKAR } from "../content/azkar";
import { COMPREHENSIVE_DUAS } from "../content/comprehensiveDuas";
const manifestIssues = validateAudioCatalog(AUDIO_CATALOG, [...ALL_AZKAR, ...COMPREHENSIVE_DUAS, ...FRIDAY_KAHF]);
if (manifestIssues.length > 0) {
  throw new Error(`Invalid audio manifest: ${manifestIssues.map((issue) => issue.code).join(", ")}`);
}
